"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ENGLISH_QWERTY, HINDI_INPUT_SYSTEMS, type ExamPreset, type TypingLesson } from "@/lib/typing-curriculum";
import { MY_MATTERS_KEY, parseMatterList, type MyTestMatter } from "@/lib/typing-matters";
import { ConfigurableTypingExam } from "../../_components/configurable-typing-exam";
import { LessonWorkspace } from "../../_components/lesson-workspace";

export default function MyMatterPage(){const params=useParams<{matterId:string}>();const [matter,setMatter]=useState<MyTestMatter|null|undefined>(undefined);useEffect(()=>{const timer=setTimeout(()=>{try{setMatter(parseMatterList(JSON.parse(localStorage.getItem(MY_MATTERS_KEY)??"[]")).find(item=>item.id===params.matterId)??null)}catch{setMatter(null)}},0);return()=>clearTimeout(timer)},[params.matterId]);if(matter===undefined)return <p className="p-8">Loading matter…</p>;if(!matter)return <p className="p-8 font-bold text-red-700">Matter not found.</p>;if(matter.mode==="learn"){const lesson:TypingLesson={id:`matter-${matter.id}`,order:1,title:matter.title,shortDescription:"Your uploaded guided lesson",category:"passages",targetKeys:[],content:matter.passage,timedContent:matter.passage,unlockAccuracy:matter.requiredAccuracy};return <LessonWorkspace lesson={lesson}/>;}const baseSystem=matter.language==="English"?ENGLISH_QWERTY:HINDI_INPUT_SYSTEMS.find(item=>item.id===matter.inputSystemId)??HINDI_INPUT_SYSTEMS[0];const system=baseSystem.inputEncoding==="krutidev-legacy"?{...baseSystem,passageOverride:matter.passage}:baseSystem;const preset:ExamPreset={id:`matter-${matter.id}`,slug:`matter-${matter.id}`,title:matter.title,subtitle:`My Matter · ${matter.mode}`,category:matter.mode==="stenography"?"stenography":"typing",language:matter.language,script:system.script,inputEncoding:system.inputEncoding,durationSeconds:matter.durationSeconds,passage:matter.passage,fontLabel:system.fontLabel,fontStack:system.fontStack,fontClassName:"font-sans",layoutLabel:system.keyboardLayout,keyboardLayout:system.keyboardLayout,inputSystems:[system],speedRequirement:matter.requiredWpm,accuracyRequirement:matter.requiredAccuracy,backspaceMode:matter.backspaceMode,wordMethod:matter.wordMethod,highlightMode:matter.highlightMode,scoringProfile:{fullErrorPenalty:1,halfErrorPenalty:.5,minorSpellingMaxDistance:1,passNetWpm:matter.requiredWpm,passAccuracy:matter.requiredAccuracy}};return <ConfigurableTypingExam preset={preset} mode={matter.mode==="practice"?"practice":"exam"} customPreset={matter.mode==="exam"} matterPreset/>;}
