import Link from "next/link";
import { signOut } from "@/app/auth/actions";
import { requireStudent } from "@/lib/auth";

export default async function StudentPage() {
  const { user, profile } = await requireStudent();
  const firstName = profile.full_name?.trim().split(/\s+/u)[0] || "Student";
  return <main className="min-h-screen bg-[#f2f5fa]"><header className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute -left-16 top-0 h-64 w-64 rounded-full bg-blue-600/25 blur-3xl"/><div className="absolute right-0 bottom-0 h-64 w-64 rounded-full bg-violet-600/20 blur-3xl"/><div className="relative mx-auto max-w-6xl px-5 py-8"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-300">Samradhi Classes</p><h1 className="mt-2 text-3xl font-black">Welcome, {firstName}</h1><p className="mt-1 text-sm text-slate-300">{user.email}</p></div><form action={signOut}><button className="rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-sm font-black backdrop-blur transition hover:bg-white hover:text-slate-900">Sign out</button></form></div></div></header><section className="mx-auto max-w-6xl px-5 py-8"><div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><Link href="/typing" className="group relative overflow-hidden rounded-3xl bg-gradient-to-br from-blue-700 via-indigo-700 to-violet-700 p-7 text-white shadow-xl transition duration-300 hover:-translate-y-1 hover:shadow-2xl"><div className="absolute -right-12 -top-12 h-44 w-44 rounded-full bg-white/10"/><div className="relative"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/15 text-2xl font-black backdrop-blur">⌨</span><p className="mt-6 text-xs font-black uppercase tracking-[0.2em] text-blue-200">Your learning workspace</p><h2 className="mt-2 text-3xl font-black">Typing Hub</h2><p className="mt-3 max-w-xl text-sm leading-6 text-blue-100">Learn English and Hindi typing, practise custom lessons, take tests, and track your accuracy and speed.</p><span className="mt-6 inline-flex items-center rounded-xl bg-white px-5 py-3 text-sm font-black text-blue-700 transition group-hover:translate-x-1">Open Typing Hub →</span></div></Link><aside className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-600">Student profile</p><h2 className="mt-2 text-xl font-black text-slate-950">Account active</h2><div className="mt-5 space-y-3"><Status label="Access" value="Typing Hub enabled"/><Status label="Role" value="Student"/><Status label="Progress" value="Saved on this device"/></div><Link href="/account/security" className="mt-6 block rounded-xl bg-slate-100 px-4 py-3 text-center text-sm font-black text-slate-700 hover:bg-slate-200">Account security</Link></aside></div><section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-slate-950">Recent activity</h2><p className="mt-2 text-sm text-slate-500">Your completed tests and learning milestones will appear here as you practise.</p></section></section></main>;
}

function Status({label,value}:{label:string;value:string}) { return <div className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-3"><span className="text-xs font-bold text-slate-500">{label}</span><strong className="text-xs text-slate-900">{value}</strong></div>; }
