import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { slugifyTest, validateManagedTest } from "../lib/admin-tests.ts";

const base={title:"Production Test",description:"Description",slug:"production-test",language:"English",inputSystemId:"english-qwerty",mode:"exam",durationSeconds:600,passage:"This is a sufficiently long English typing passage for validation.",requiredWpm:30,requiredAccuracy:90,backspaceMode:"full",wordMethod:"characters",highlightMode:"character",visibility:"public",examCategory:"rajasthan-ldc"};
test("managed test validation accepts a complete configuration",()=>assert.deepEqual(validateManagedTest(base).errors,[]));
test("test links are generated automatically from English and Hindi titles",()=>{assert.equal(slugifyTest("English Speed Test"),"english-speed-test");assert.equal(slugifyTest("हिंदी टाइपिंग टेस्ट"),"हिंदी-टाइपिंग-टेस्ट")});
// 70 minutes, not 60 -- lib/admin-tests.ts raised this cap to cover
// researched stenography categories whose real transcription time runs to
// 70 minutes (RSMSSB Hindi, Rajasthan HC Steno Hindi -- see
// lib/stenography-categories.ts); a category's own force-applied duration
// used to fail this check with no visible field for the admin to fix.
test("managed tests enforce duration and encoding",()=>{assert.match(validateManagedTest({...base,durationSeconds:4260}).errors.join(" "),/1 and 70/);assert.match(validateManagedTest({...base,language:"Hindi",inputSystemId:"hindi-krutidev-010",passage:"यह यूनिकोड हिन्दी का पर्याप्त लंबा परीक्षण पाठ है।"}).errors.join(" "),/Convert to Kruti Dev/)});
// legacyTitle must trip the *real* LEGACY_SIGNAL patterns (lib/hindi-font-
// converter.ts), not the bare "d"/"D" that pattern used to also match on --
// that was itself a bug (fixed alongside this test): a lone "d"/"D" is
// degenerately common in ordinary text (e.g. any title containing the word
// "Hindi"), unlike every other alternative here, which need a specific
// multi-character Kruti Dev garbage sequence.
test("Hindi titles remain Unicode even when passage encoding is Kruti Dev",()=>{const legacyPassage="Hkkjr dh f'k{kk vkSj vkfFkZd fodkl ij ;g i;kZIr yack ijh{k.k ikB gSA";const legacyTitle="Hkkjr dh f'k{kk vkSj fodkl";assert.match(validateManagedTest({...base,title:legacyTitle,language:"Hindi",inputSystemId:"hindi-krutidev-010",passage:legacyPassage}).errors.join(" "),/titles must use Unicode/);assert.doesNotMatch(validateManagedTest({...base,title:"ब्रिक्स अध्यक्षता",language:"Hindi",inputSystemId:"hindi-krutidev-010",passage:legacyPassage}).errors.join(" "),/titles must use Unicode/);assert.doesNotMatch(validateManagedTest({...base,title:"Hindi Practice Test",language:"Hindi",inputSystemId:"hindi-krutidev-010",passage:legacyPassage}).errors.join(" "),/titles must use Unicode/,"a plain English title containing the word \"Hindi\" must not be flagged as legacy-encoded -- regression test for the [dD][kZ]? bug");});
test("migration requires AAL2 and immutable version references",()=>{const sql=readFileSync(new URL("../supabase/migrations/202608160003_admin_test_management.sql",import.meta.url),"utf8");assert.match(sql,/auth\.jwt\(\)->>'aal'\) = 'aal2'/);assert.match(sql,/test_version_id uuid not null references public\.test_versions\(id\) on delete restrict/);assert.match(sql,/revoke update, delete on public\.test_versions/);assert.match(sql,/current_version_id = test_version_id/)});
test("service role is absent from managed test code",()=>{for(const path of ["../app/admin/tests/actions.ts","../app/tests/actions.ts","../lib/admin-tests.ts"]){assert.doesNotMatch(readFileSync(new URL(path,import.meta.url),"utf8"),/service.role|SUPABASE_SERVICE_ROLE_KEY/i)}});

test("migration preserves legacy visibility using durable unmanaged state",()=>{const sql=readFileSync(new URL("../supabase/migrations/202608160003_admin_test_management.sql",import.meta.url),"utf8");assert.match(sql,/update public\.tests set visibility='public'[\s\S]*where status='published'[\s\S]*current_version_id is null[\s\S]*current_version_number=0/);assert.doesNotMatch(sql,/admin_test_migration_state|create temporary table/i);assert.doesNotMatch(sql,/update public\.tests set visibility='public'[\s\S]*where status in \([^)]*draft/i);assert.match(sql,/default 'private'/)});
test("migration backfills exactly one version and a valid current reference",()=>{const sql=readFileSync(new URL("../supabase/migrations/202608160003_admin_test_management.sql",import.meta.url),"utf8");assert.match(sql,/unique\(test_id, version_number\)/);assert.match(sql,/select t\.id,1,/);assert.match(sql,/where not exists\(select 1 from public\.test_versions v where v\.test_id=t\.id\)/);assert.match(sql,/set current_version_id=v\.id,current_version_number=v\.version_number/);assert.match(sql,/every test must reference a valid immutable version/)});
test("backfill does not rewrite legacy identity or content fields",()=>{const sql=readFileSync(new URL("../supabase/migrations/202608160003_admin_test_management.sql",import.meta.url),"utf8");const backfill=sql.slice(sql.indexOf("-- Durable legacy marker"),sql.indexOf("create index if not exists tests_admin_catalog"));assert.doesNotMatch(backfill,/update public\.tests\s+(?:t\s+)?set\s+(?:title|slug|duration_seconds|content|settings|id)\s*=/i);for(const field of ["t.id","t.title","t.duration_seconds","t.content->>'passage'","t.settings"])assert.match(backfill,new RegExp(field.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))});
test("preflight is read-only and reports live compatibility without content",()=>{const sql=readFileSync(new URL("../supabase/preflight/202608160003_admin_test_management_preflight.sql",import.meta.url),"utf8");assert.doesNotMatch(sql,/^\s*(insert|update|delete|drop|truncate|alter|create)\b/im);assert.match(sql,/test_count_by_status/);assert.match(sql,/published_test_count/);assert.match(sql,/managed_table_presence/);assert.doesNotMatch(sql,/content->>|select[^;]*(?:email|password|passage)/i)});
test("enum-only failed attempt can rerun without temporary state or duplicate versions",()=>{const sql=readFileSync(new URL("../supabase/migrations/202608160003_admin_test_management.sql",import.meta.url),"utf8");assert.match(sql,/alter type public\.test_status add value if not exists 'unpublished'/);assert.doesNotMatch(sql,/\btemp(?:orary)?\b/i);assert.match(sql,/where not exists\(select 1 from public\.test_versions v where v\.test_id=t\.id\)/);assert.match(sql,/unique\(test_id, version_number\)/)});
test("published-version policy qualifies outer columns and preserves AAL2 access",()=>{const sql=readFileSync(new URL("../supabase/migrations/202608230002_fix_published_version_read_policy.sql",import.meta.url),"utf8");assert.match(sql,/related_test\.id = public\.test_versions\.test_id/);assert.match(sql,/related_test\.current_version_id = public\.test_versions\.id/);assert.match(sql,/related_test\.status = 'published'/);assert.match(sql,/related_test\.visibility = 'public'/);assert.match(sql,/or public\.is_aal2_admin\(\)/);assert.doesNotMatch(sql,/t\.id = test_id|t\.current_version_id = id/)});
test("published-version policy preflight is read-only and checks qualified columns",()=>{const sql=readFileSync(new URL("../supabase/preflight/202608230002_fix_published_version_read_policy_preflight.sql",import.meta.url),"utf8");assert.doesNotMatch(sql,/^\s*(insert|update|delete|drop|truncate|alter|create)\b/im);assert.match(sql,/test_versions\.test_id/);assert.match(sql,/test_versions\.id/);assert.match(sql,/is_aal2_admin/)});
