import test from "node:test";
import assert from "node:assert/strict";
import { DEFAULT_PLATFORM_PREFERENCES, migrateTypingPlatformSettings, parsePlatformPreferences, resolveAttemptSettings } from "../lib/typing-platform-settings.ts";

test("migrates legacy settings and font keys into one versioned store", () => { const store=migrateTypingPlatformSettings(null,{"rssb-ldc-typing-settings":{highlightMode:"highlight",backspaceMode:"word",wordMethod:"spaces",autoScroll:false},"samradhi-typing-font-sizes-v1-latin-unicode":{originalSize:24,typingSize:22,linked:true}}); assert.equal(store.version,2); assert.equal(store.preferences.highlightMode,"character"); assert.equal(store.preferences.backspaceMode,"word"); assert.equal(store.preferences.autoScroll,false); assert.equal(store.preferences.fonts.latin.originalSize,24); });
test("invalid universal settings safely use defaults",()=>{const parsed=parsePlatformPreferences({highlightMode:"bad",backspaceMode:"all",wordMethod:"letters",fonts:{latin:{originalSize:99}}});assert.equal(parsed.highlightMode,DEFAULT_PLATFORM_PREFERENCES.highlightMode);assert.equal(parsed.fonts.latin.originalSize,20)});
test("scrollbar visibility is stored as a student preference",()=>{assert.equal(parsePlatformPreferences({showScrollbar:false}).showScrollbar,false);assert.equal(parsePlatformPreferences({}).showScrollbar,true)});
test("saved custom duration is restricted to one through sixty minutes",()=>{assert.equal(parsePlatformPreferences({durationMinutes:1}).durationMinutes,1);assert.equal(parsePlatformPreferences({durationMinutes:60}).durationMinutes,60);assert.equal(parsePlatformPreferences({durationMinutes:0}).durationMinutes,10);assert.equal(parsePlatformPreferences({durationMinutes:61}).durationMinutes,10);assert.equal(parsePlatformPreferences({durationMinutes:2.5}).durationMinutes,10)});
test("official preset rules remain isolated from global defaults",()=>{const global={...DEFAULT_PLATFORM_PREFERENCES,backspaceMode:"disabled",wordMethod:"spaces"};const official=resolveAttemptSettings(global,{backspaceMode:"full",wordMethod:"characters"},"official");const custom=resolveAttemptSettings(global,{backspaceMode:"full",wordMethod:"characters"},"custom");assert.equal(official.backspaceMode,"full");assert.equal(official.wordMethod,"characters");assert.equal(custom.backspaceMode,"disabled");assert.equal(custom.wordMethod,"spaces");assert.equal(official.highlightMode,global.highlightMode)});
