import assert from"node:assert/strict";import test from"node:test";import{Window}from"happy-dom";import{adjustParagraphIndent,applyParagraphStyle,changeEditorRangeCase,clearEditorRangeFormatting,replaceEditorText,selectedEditorBlocks,snapshotPaintStyle,wrapEditorRange}from"../lib/word-editor-dom.ts";

function documentWithMatter(){const window=new Window(),document=window.document;document.body.innerHTML='<div id="editor" contenteditable="true"><p id="p1" style="margin-right:0in">Alpha beta</p><p id="p2" style="margin-right:0in">Gamma delta</p><p id="p3">Omega</p></div>';return{window,document,editor:document.querySelector("#editor")}}

test("multi-paragraph Range scope returns every intersected block and no unrelated block",()=>{const{document,editor}=documentWithMatter(),range=document.createRange();range.setStart(document.querySelector("#p1").firstChild,6);range.setEnd(document.querySelector("#p2").firstChild,5);assert.deepEqual(selectedEditorBlocks(editor,range).map(block=>block.id),["p1","p2"])});

// Real reported bug: setting line spacing (a paragraph-level style applied
// via selectedBlocks()/selectedEditorBlocks()) on a collapsed cursor placed
// in paragraph one also applied it to paragraph two. Range.intersectsNode()
// -- previously used for every case, collapsed or not -- is documented to
// be ambiguous for a collapsed range sitting at a block boundary; a
// collapsed cursor must always resolve to exactly the one block it's
// actually in, regardless of where inside that block it sits.
test("a collapsed cursor (no real selection) resolves to exactly the one block it's in, never a neighboring block",()=>{const{document,editor}=documentWithMatter();
 const midP1=document.createRange();midP1.setStart(document.querySelector("#p1").firstChild,5);midP1.collapse(true);assert.deepEqual(selectedEditorBlocks(editor,midP1).map(block=>block.id),["p1"]);
 const endOfP1Text=document.createRange();endOfP1Text.setStart(document.querySelector("#p1").firstChild,10);endOfP1Text.collapse(true);assert.deepEqual(selectedEditorBlocks(editor,endOfP1Text).map(block=>block.id),["p1"]);
 const startOfP2=document.createRange();startOfP2.setStart(document.querySelector("#p2").firstChild,0);startOfP2.collapse(true);assert.deepEqual(selectedEditorBlocks(editor,startOfP2).map(block=>block.id),["p2"]);
 const onP1ElementItself=document.createRange();onP1ElementItself.setStart(document.querySelector("#p1"),1);onP1ElementItself.collapse(true);assert.deepEqual(selectedEditorBlocks(editor,onP1ElementItself).map(block=>block.id),["p1"]);
});

test("applying line spacing to a collapsed cursor's paragraph never touches the next paragraph",()=>{const{document,editor}=documentWithMatter(),cursor=document.createRange();cursor.setStart(document.querySelector("#p1").firstChild,10);cursor.collapse(true);const blocks=selectedEditorBlocks(editor,cursor);assert.equal(applyParagraphStyle(blocks,{lineHeight:"2.5"}),true);assert.equal(document.querySelector("#p1").style.lineHeight,"2.5");assert.equal(document.querySelector("#p2").style.lineHeight,"")});

test("exact point styles wrap only selected characters and preserve paragraph margins",()=>{const{document}=documentWithMatter(),paragraph=document.querySelector("#p1"),range=document.createRange();range.setStart(paragraph.firstChild,0);range.setEnd(paragraph.firstChild,5);const wrapped=wrapEditorRange(range,{fontFamily:"Arial",fontSize:"14pt",fontWeight:"700",color:"rgb(192, 0, 0)"});assert.ok(wrapped);assert.equal(paragraph.textContent,"Alpha beta");assert.equal(wrapped.span.textContent,"Alpha");assert.equal(wrapped.span.style.fontSize,"14pt");assert.equal(wrapped.span.style.fontFamily,"Arial");assert.equal(paragraph.style.marginRight,"0in")});

test("paragraph formatting applies to all selected blocks without touching the third paragraph",()=>{const{document,editor}=documentWithMatter(),range=document.createRange();range.setStart(document.querySelector("#p1").firstChild,2);range.setEnd(document.querySelector("#p2").firstChild,3);const blocks=selectedEditorBlocks(editor,range);assert.equal(applyParagraphStyle(blocks,{textAlign:"justify",marginLeft:"0.5in",lineHeight:"1.5",backgroundColor:"rgb(255, 255, 0)",border:"1px solid rgb(0, 0, 0)"}),true);for(const block of blocks){assert.equal(block.style.textAlign,"justify");assert.equal(block.style.marginLeft,"0.5in");assert.equal(block.style.lineHeight,"1.5")}assert.equal(document.querySelector("#p3").getAttribute("style"),null)});

test("Format Painter snapshots reviewed character properties and applies them to a destination Range",()=>{const{window,document}=documentWithMatter(),source=document.createElement("span");source.style.cssText="font: italic 700 16pt Arial; color: rgb(1, 2, 3); background-color: rgb(255, 255, 0); text-decoration: underline double; vertical-align: super";source.textContent="Source";document.querySelector("#p1").replaceChildren(source,document.createTextNode(" beta"));const paint=snapshotPaintStyle(window.getComputedStyle(source)),target=document.querySelector("#p2").firstChild,range=document.createRange();range.setStart(target,0);range.setEnd(target,5);const wrapped=wrapEditorRange(range,paint);assert.ok(wrapped);assert.equal(wrapped.span.textContent,"Gamma");assert.equal(wrapped.span.style.fontFamily,paint.fontFamily);assert.equal(wrapped.span.style.fontSize,paint.fontSize);assert.equal(document.querySelector("#p2").style.marginRight,"0in")});

test("case conversion and clear formatting preserve selected text and paragraph measurements",()=>{const{document}=documentWithMatter(),paragraph=document.querySelector("#p1"),range=document.createRange();range.setStart(paragraph.firstChild,0);range.setEnd(paragraph.firstChild,10);let selected=changeEditorRangeCase(range,"title");assert.equal(paragraph.textContent,"Alpha Beta");assert.equal(paragraph.style.marginRight,"0in");const styled=wrapEditorRange(selected,{fontWeight:"700",fontStyle:"italic"});assert.ok(styled);selected=clearEditorRangeFormatting(styled.range);assert.equal(selected.toString(),"Alpha Beta");assert.equal(paragraph.querySelector("span"),null);assert.equal(paragraph.style.marginRight,"0in")});

test("indent changes every selected paragraph using canonical inches and clamps at zero",()=>{const{document,editor}=documentWithMatter(),range=document.createRange();range.setStart(document.querySelector("#p1").firstChild,0);range.setEnd(document.querySelector("#p2").firstChild,2);const blocks=selectedEditorBlocks(editor,range);document.querySelector("#p1").style.marginLeft="72pt";document.querySelector("#p2").style.marginLeft="96px";adjustParagraphIndent(blocks,1);assert.equal(document.querySelector("#p1").style.marginLeft,"1.25in");assert.equal(document.querySelector("#p2").style.marginLeft,"1.25in");adjustParagraphIndent(blocks,-1,2);assert.equal(document.querySelector("#p1").style.marginLeft,"0in");assert.equal(document.querySelector("#p3").style.marginLeft,"")});

test("replace changes text nodes without rewriting paragraph elements or measurements",()=>{const{document,editor}=documentWithMatter();assert.equal(replaceEditorText(editor,"a","A"),6);assert.equal(document.querySelector("#p1").textContent,"AlphA betA");assert.equal(document.querySelector("#p1").style.marginRight,"0in");assert.equal(document.querySelectorAll("p").length,3)});
