import assert from"node:assert/strict";import test from"node:test";import{readFile}from"node:fs/promises";import{Window}from"happy-dom";import{validateWordEditorDocument}from"../lib/word-editor-document.ts";import{createEditorBlock,editorBlockAttrs,editorBlockType}from"../lib/word-editor-structure.ts";

test("editable table preserves row, column, and cell content through structured attrs",()=>{const document=new Window().document;document.body.innerHTML='<table data-block-type="table"><tbody><tr><td contenteditable="true">A1</td><td contenteditable="true">B1</td></tr><tr><td contenteditable="true">A2</td><td contenteditable="true">B2</td></tr></tbody></table>';const table=document.querySelector("table"),attrs=editorBlockAttrs(table,editorBlockType(table)),restored=createEditorBlock(document,{id:"table-1",type:"table",alignment:"left",attrs});assert.deepEqual(attrs.rows,[["A1","B1"],["A2","B2"]]);assert.deepEqual([...restored.querySelectorAll("td")].map(cell=>cell.textContent),["A1","B1","A2","B2"]);assert.ok([...restored.querySelectorAll("td")].every(cell=>cell.contentEditable==="true"))});

test("break and header/footer block identity survives reconstruction",()=>{const document=new Window().document;for(const type of["page-break","section-break","header","footer","cover-page","shape"]){const source=document.createElement(type==="header"?"header":type==="footer"?"footer":type.includes("break")?"hr":"section");source.dataset.blockType=type;if(type==="section-break")source.dataset.breakKind="section-continuous";const attrs=editorBlockAttrs(source,type),restored=createEditorBlock(document,{id:`${type}-1`,type,alignment:"left",attrs});assert.equal(editorBlockType(restored),type);if(type==="section-break")assert.equal(restored.dataset.breakKind,"section-continuous")}});

test("safe embedded and local images retain bounded metadata",()=>{const document=new Window().document,source=document.createElement("figure");source.dataset.blockType="image";source.innerHTML='<img src="data:image/png;base64,iVBORw0KGgo=" alt="Diagram" width="320" height="180">';const attrs=editorBlockAttrs(source,"image"),restored=createEditorBlock(document,{id:"image-1",type:"image",alignment:"center",attrs});assert.equal(attrs.alt,"Diagram");assert.equal(attrs.width,320);assert.equal(restored.querySelector("img").getAttribute("src"),attrs.src);const local=document.createElement("figure");local.dataset.localAsset="samradhi-mark";assert.equal(editorBlockAttrs(local,"image").src,"asset:samradhi-mark")});

test("the v2 validator accepts each supported structural block and editor integrates structured save/restore",async()=>{const run={text:"Editable",bold:false,italic:false,underline:false,underlineStyle:null,underlineColor:null,underlineThickness:null,underlineWordsOnly:false,strike:false,doubleStrike:false,superscript:false,subscript:false,fontFamily:"Arial",fontSize:12,color:null,highlight:null,href:null,bookmark:null,field:null},blocks=[{id:"table-1",type:"table",alignment:"left",runs:[{...run,text:""}],attrs:{rows:[["A","B"]]}},{id:"break-1",type:"section-break",alignment:"left",runs:[{...run,text:""}],attrs:{kind:"section-next-page"}},{id:"header-1",type:"header",alignment:"left",runs:[run],attrs:{}},{id:"footer-1",type:"footer",alignment:"left",runs:[run],attrs:{}},{id:"shape-1",type:"shape",alignment:"left",runs:[run],attrs:{}}],snapshot={schemaVersion:"2",blocks,pageLayout:{padding:null,maxWidth:null,aspectRatio:null,columnCount:null,backgroundColor:null,border:null,watermark:null},operations:[],savedAt:new Date().toISOString()};assert.equal(validateWordEditorDocument(snapshot),snapshot);const source=await readFile(new URL("../app/typing/word-efficiency/[language]/[testId]/workspace/rich-document-editor.tsx",import.meta.url),"utf8");assert.match(source,/makeStructuredBlock/);assert.match(source,/renderStructuredSnapshot/);assert.match(source,/editorBlockAttrs/);assert.match(source,/createEditorBlock/)});
