import type { Metadata } from "next";
import Link from "next/link";
import { TypingBrandHeader } from "../_components/typing-brand";

export const metadata: Metadata = { title: "Practice Categories | Samradhi Classes", description: "English and Hindi typing, stenography, Word, and Excel practice categories." };

const CATEGORIES = [
  { title:"English Typing", href:"/typing/practice/english", description:"Build English speed and accuracy with published QWERTY practice tests.", action:"Browse English Tests", tone:"from-blue-700 to-cyan-500", icon:"keyboard" },
  { title:"Hindi Typing", href:"/typing/practice/hindi", description:"Choose your Hindi font and keyboard layout before selecting a compatible test.", action:"Choose Hindi Keyboard", tone:"from-orange-600 to-amber-400", icon:"language" },
  { title:"English Stenography", href:"/typing/practice/english-stenography", description:"Open published English stenography passages with dedicated speed targets.", action:"Browse English Steno", tone:"from-violet-700 to-fuchsia-500", icon:"mic" },
  { title:"Hindi Stenography", href:"/typing/practice/hindi-stenography", description:"Select a Hindi input system and practise compatible stenography tests.", action:"Choose Hindi Steno", tone:"from-rose-700 to-pink-500", icon:"wave" },
  { title:"Word Efficiency", href:"/typing/word-efficiency", description:"Prepare for document formatting and productivity exercises.", action:"Explore Word Training", tone:"from-sky-700 to-blue-500", icon:"document" },
  { title:"Excel Efficiency", href:"/typing/practice/excel-efficiency", description:"Prepare for spreadsheet, formula, and data-entry exercises.", action:"Explore Excel Training", tone:"from-emerald-700 to-teal-500", icon:"grid" },
] as const;

export default function PracticeCataloguePage() {
  return <main className="min-h-screen bg-[#f3f6fb]"><TypingBrandHeader/><section className="bg-slate-950 px-4 py-12 text-white"><div className="mx-auto max-w-7xl"><Link href="/typing" className="text-sm font-black text-cyan-300">← Typing Hub</Link><p className="mt-8 text-xs font-black uppercase tracking-[.22em] text-cyan-300">Practice workspace</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Choose your skill category</h1><p className="mt-4 max-w-2xl text-slate-300">Each catalogue is isolated by test type, language, and keyboard system so you always practise with the correct configuration.</p></div></section><section className="mx-auto max-w-7xl px-4 py-10"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-blue-700">Training categories</p><h2 className="mt-2 text-3xl font-black">Select a practice path</h2></div><span className="rounded-full bg-white px-4 py-2 text-xs font-black text-slate-600 shadow">{CATEGORIES.length} active categories</span></div><div className="mt-7 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{CATEGORIES.map((category)=><Link key={category.href} href={category.href} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-2 hover:shadow-2xl"><div className={`bg-gradient-to-br ${category.tone} p-6 text-white`}><CategoryIcon name={category.icon}/></div><div className="p-6"><h3 className="text-2xl font-black">{category.title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-slate-600">{category.description}</p><span className={`mt-6 flex items-center justify-between rounded-xl bg-gradient-to-r ${category.tone} px-4 py-3 text-sm font-black text-white`}>{category.action}<b className="transition group-hover:translate-x-1">→</b></span></div></Link>)}</div></section></main>;
}

function CategoryIcon({name}:{name:string}) { const paths:Record<string,React.ReactNode>={keyboard:<><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M7 10h.01M11 10h.01M15 10h.01M7 14h10"/></>,language:<><path d="M4 5h7M7.5 3v2c0 4-2 7-5 9M5 9c1 2 3 4 6 5M14 19l4-10 4 10M15.5 16h5"/></>,mic:<><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M8 21h8"/></>,wave:<><path d="M3 12h2l2-7 4 14 3-11 3 8 2-4h2"/></>,document:<><path d="M6 2h9l4 4v16H6zM14 2v5h5M9 12h6M9 16h6"/></>,grid:<><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M3 15h18M9 3v18M15 3v18"/></>};return <span className="grid h-16 w-16 place-items-center rounded-2xl bg-white/15"><svg viewBox="0 0 24 24" className="h-9 w-9 fill-none stroke-current stroke-2" aria-hidden="true">{paths[name]}</svg></span>; }
