import type { Metadata } from "next";
import Link from "next/link";
import { TypingBrandHeader } from "../_components/typing-brand";

export const metadata: Metadata = { title: "Practice Categories | Samradhi Classes", description: "English and Hindi typing practice categories." };

const CATEGORIES = [
  { title:"English Typing", href:"/typing/practice/english", description:"Build English speed and accuracy with published QWERTY practice tests.", action:"Browse English Tests", tone:"from-blue-700 to-cyan-500", icon:"keyboard" },
  { title:"Hindi Typing", href:"/typing/practice/hindi", description:"Choose your Hindi font and keyboard layout before selecting a compatible test.", action:"Choose Hindi Keyboard", tone:"from-orange-600 to-amber-400", icon:"language" },
] as const;

export default function PracticeCataloguePage() {
  return <main className="min-h-screen bg-[#f3f6fb]"><TypingBrandHeader/><section className="bg-slate-950 px-4 py-7 text-white"><div className="mx-auto max-w-7xl"><Link href="/typing" className="text-sm font-black text-cyan-300">← Typing Hub</Link><div className="mt-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.22em] text-cyan-300">Practice workspace</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">Choose your skill category</h1></div><p className="max-w-md text-sm text-slate-300">Each catalogue is isolated by test type, language, and keyboard system so you always practise with the correct configuration.</p></div></div></section><section className="mx-auto max-w-7xl px-4 py-10"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-blue-700">Training categories</p><h2 className="mt-2 text-3xl font-black">Select a practice path</h2></div><span className="rounded-full bg-white px-4 py-2 text-xs font-black text-slate-600 shadow">{CATEGORIES.length} active categories</span></div><div className="mt-7 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{CATEGORIES.map((category)=><Link key={category.href} href={category.href} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-2 hover:shadow-2xl"><div className={`bg-gradient-to-br ${category.tone} p-6 text-white`}><CategoryIcon name={category.icon}/></div><div className="p-6"><h3 className="text-2xl font-black">{category.title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-slate-600">{category.description}</p><span className={`mt-6 flex items-center justify-between rounded-xl bg-gradient-to-r ${category.tone} px-4 py-3 text-sm font-black text-white`}>{category.action}<b className="transition group-hover:translate-x-1">→</b></span></div></Link>)}</div></section></main>;
}

function CategoryIcon({name}:{name:string}) { const paths:Record<string,React.ReactNode>={keyboard:<><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M7 10h.01M11 10h.01M15 10h.01M7 14h10"/></>,language:<><path d="M4 5h7M7.5 3v2c0 4-2 7-5 9M5 9c1 2 3 4 6 5M14 19l4-10 4 10M15.5 16h5"/></>};return <span className="grid h-16 w-16 place-items-center rounded-2xl bg-white/15"><svg viewBox="0 0 24 24" className="h-9 w-9 fill-none stroke-current stroke-2" aria-hidden="true">{paths[name]}</svg></span>; }
