import Link from "next/link";
import { requireStudent } from "@/lib/auth";
import { BackButton } from "@/app/_components/back-button";

export default async function StudentProfilePage() {
  const { user, profile } = await requireStudent();
  const name: string = profile.full_name?.trim() || "Student";
  const initials = name.split(/\s+/u).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "ST";
  return <main className="min-h-screen bg-slate-100 px-4 py-8"><div className="mx-auto max-w-3xl"><BackButton href="/typing" label="Typing Hub" /><section className="mt-5 overflow-hidden rounded-3xl bg-white shadow-xl"><header className="bg-gradient-to-br from-blue-800 via-indigo-700 to-violet-700 p-7 text-white"><div className="flex items-center gap-5"><span className="flex h-24 w-24 items-center justify-center rounded-full bg-white/15 text-2xl font-black ring-4 ring-white/30">{initials}</span><div><p className="text-xs font-black uppercase tracking-[0.18em] text-blue-200">Student profile</p><h1 className="mt-2 text-3xl font-black">{name}</h1><span className="mt-2 inline-flex rounded-full bg-emerald-400/20 px-3 py-1 text-xs font-black text-emerald-100">● Active student</span></div></div></header><div className="grid gap-4 p-6 sm:grid-cols-2"><Info label="Full name" value={name}/><Info label="Email address" value={user.email || "Not available"}/><Info label="Contact number" value={user.phone || "Not added"}/><Info label="Account ID" value={user.id.slice(0, 8).toUpperCase()}/><Info label="Email verification" value={user.email_confirmed_at ? "Verified" : "Pending"}/><Info label="Member since" value={new Date(user.created_at).toLocaleDateString()}/></div><div className="grid gap-3 border-t border-slate-100 p-6 sm:grid-cols-3"><Link href="/student/results" className="rounded-xl bg-blue-700 px-4 py-3 text-center text-sm font-black text-white">My Results</Link><Link href="/live-test" className="rounded-xl bg-indigo-100 px-4 py-3 text-center text-sm font-black text-indigo-800">Live Results</Link><Link href="/account/security" className="rounded-xl bg-slate-100 px-4 py-3 text-center text-sm font-black text-slate-700">Security</Link></div></section></div></main>;
}
function Info({label,value}:{label:string;value:string}) { return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 break-all text-sm font-black text-slate-900">{value}</p></div>; }

