"use client";

import Link from "next/link";
import Image from "next/image";
import { signOut } from "@/app/auth/actions";
import { useTypingStudent } from "./typing-student-provider";

export function TypingBrandHeader() {
  const student = useTypingStudent();
  const name = student.name;
  const initials = name.split(/\s+/u).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "ST";
  return <header className="relative z-50 bg-blue-700 text-white shadow"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3"><Link href="/typing" className="flex min-w-0 items-center gap-3"><Image src="/samradhi-classes-logo.png" alt="Samradhi Classes logo" width={40} height={40} priority className="h-10 w-10 shrink-0 rounded-full bg-white object-contain ring-1 ring-white/80"/><span className="min-w-0"><strong className="block truncate text-lg">SAMRADHI CLASSES</strong><span className="hidden text-xs text-blue-100 sm:block">Student Typing Workspace</span></span></Link><div className="flex items-center gap-2"><nav aria-label="Student results" className="hidden items-center gap-2 md:flex"><HeaderLink href="/student/results" label="Test Results" icon="▥"/><HeaderLink href="/live-test" label="Live Test Results" icon="●" live/></nav><details className="group relative"><summary className="flex cursor-pointer list-none items-center gap-2 rounded-xl border border-white/15 bg-white/10 p-1.5 pr-3 transition hover:bg-white/15"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-cyan-300 to-violet-300 text-xs font-black text-blue-950 ring-2 ring-white/50">{initials}</span><span className="hidden min-w-0 text-left sm:block"><strong className="block max-w-36 truncate text-xs">{name}</strong><span className="block max-w-36 truncate text-[10px] text-blue-100">Student profile</span></span><span aria-hidden="true" className="text-xs transition group-open:rotate-180">▾</span></summary><div className="absolute right-0 mt-2 w-80 overflow-hidden rounded-2xl border border-slate-200 bg-white text-slate-900 shadow-2xl"><div className="bg-gradient-to-br from-blue-700 to-indigo-700 p-5 text-white"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-white/20 text-sm font-black ring-2 ring-white/40">{initials}</span><div className="min-w-0"><p className="truncate font-black">{name}</p><p className="truncate text-xs text-blue-100">{student.email}</p><p className="mt-1 text-[10px] text-blue-200">{student.phone || "Mobile number not added"}</p></div></div></div><nav aria-label="Student account menu" className="grid grid-cols-2 gap-2 p-3"><ProfileLink href="/student/profile" icon="◉" label="My Profile"/><ProfileLink href="/account/security" icon="◆" label="Security"/><ProfileLink href="/student" icon="⌂" label="Dashboard"/><span className="md:hidden"><ProfileLink href="/student/results" icon="▥" label="Test Results"/></span><span className="md:hidden"><ProfileLink href="/live-test" icon="●" label="Live Results"/></span></nav><form action={signOut} className="border-t border-slate-100 p-3"><button className="w-full rounded-xl bg-red-50 px-4 py-3 text-sm font-black text-red-700 hover:bg-red-100">Sign out</button></form></div></details></div></div></header>;
}

function HeaderLink({href,label,icon,live = false}:{href:string;label:string;icon:string;live?:boolean}) { return <Link href={href} className="flex items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-3 py-2 text-xs font-black transition hover:bg-white/20"><span aria-hidden="true" className={live ? "text-emerald-300" : "text-cyan-200"}>{icon}</span>{label}</Link>; }

function ProfileLink({href,icon,label}:{href:string;icon:string;label:string}) { return <Link href={href} className="rounded-xl bg-slate-50 p-3 text-xs font-black text-slate-700 transition hover:bg-blue-50 hover:text-blue-700"><span aria-hidden="true" className="mr-2 text-blue-600">{icon}</span>{label}</Link>; }
