type Run={text?:unknown;bold?:unknown;italic?:unknown;underline?:unknown;strike?:unknown;fontFamily?:unknown;fontSize?:unknown;color?:unknown;highlight?:unknown};
type Block={id?:unknown;type?:unknown;alignment?:unknown;runs?:unknown;attrs?:unknown};

export function StructuredDocumentViewer({document,label}:{document:unknown;label:string}){
 const blocks=readBlocks(document);
 return <section aria-label={label} className="rounded-2xl border bg-white p-5"><h3 className="font-black">{label}</h3><div className="mt-4 max-h-[32rem] overflow-auto rounded-xl bg-slate-50 p-5 leading-7">{blocks.length?blocks.map((block,index)=><BlockView key={String(block.id??index)} block={block}/>):<p className="text-slate-500">Document preview unavailable.</p>}</div></section>;
}
export function documentText(document:unknown){return readBlocks(document).map(block=>runs(block).map(run=>String(run.text??"")).join("")).join("\n")}
function readBlocks(document:unknown):Block[]{if(!document||typeof document!=="object")return[];const value=document as Record<string,unknown>;if(Array.isArray(value.blocks))return value.blocks.filter(item=>item&&typeof item==="object") as Block[];if(Array.isArray(value.paragraphs))return value.paragraphs.filter(item=>item&&typeof item==="object") as Block[];return[]}
function runs(block:Block):Run[]{return Array.isArray(block.runs)?block.runs.filter(item=>item&&typeof item==="object") as Run[]:[]}
function BlockView({block}:{block:Block}){const content=runs(block).map((run,index)=><span key={index} style={{fontWeight:run.bold?700:undefined,fontStyle:run.italic?"italic":undefined,textDecoration:[run.underline?"underline":"",run.strike?"line-through":""].filter(Boolean).join(" ")||undefined,fontFamily:typeof run.fontFamily==="string"?run.fontFamily:undefined,fontSize:typeof run.fontSize==="number"?`${run.fontSize}pt`:undefined,color:safeColor(run.color),backgroundColor:safeColor(run.highlight)}}>{String(run.text??"")}</span>);const style={textAlign:allowedAlignment(block.alignment)};if(block.type==="list-item")return <li style={style}>{content}</li>;if(block.type==="horizontal-rule"||block.type==="page-break"||block.type==="section-break")return <hr className="my-4 border-slate-300"/>;if(block.type==="table"){const rows=(block.attrs as {rows?:unknown})?.rows;return Array.isArray(rows)?<table className="my-3 w-full border-collapse"><tbody>{rows.map((row,index)=><tr key={index}>{Array.isArray(row)&&row.map((cell,cellIndex)=><td className="border p-2" key={cellIndex}>{String(cell??"")}</td>)}</tr>)}</tbody></table>:null}return <p className="mb-3 whitespace-pre-wrap" style={style}>{content}</p>}
function allowedAlignment(value:unknown):"left"|"center"|"right"|"justify"|undefined{return ["left","center","right","justify"].includes(String(value))?value as "left"|"center"|"right"|"justify":undefined}
function safeColor(value:unknown){const text=String(value??"");return /^#?[0-9a-f]{6}$/i.test(text)?`#${text.replace("#","")}`:undefined}
