import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { liveTestState } from "@/lib/live-tests";
import { formatIST } from "@/lib/format-datetime";
import { LiveResultsTicker, type PublicLiveResult } from "@/app/_components/live-results-ticker";
import { BackButton } from "@/app/_components/back-button";

export default async function LiveTestCentre(){
  const supabase=await createClient();
  const[{data:tests},{data:results}]=await Promise.all([
    supabase.from("tests").select("id,title,slug,description,language,duration_seconds,live_starts_at,live_ends_at,results_publish_at,is_live").eq("status","published").eq("visibility","public").eq("is_live",true).order("live_starts_at",{ascending:false}),
    supabase.rpc("published_live_results",{p_limit:30}),
  ]);
  return <main className="min-h-screen bg-slate-100"><section className="bg-gradient-to-br from-blue-800 to-indigo-950 px-4 py-12 text-white"><div className="mx-auto max-w-6xl"><BackButton href="/typing" label="Typing Hub" dark/><p className="mt-6 text-sm font-black uppercase tracking-[.2em] text-blue-200">Free for registered students</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Samradhi Live Test Centre</h1><p className="mt-4 max-w-3xl text-blue-100">Join during the scheduled window, submit one secure attempt, and see anonymized results only after the announced next-day release.</p></div></section><section className="mx-auto max-w-6xl px-4 py-10"><h2 className="text-2xl font-black">Scheduled live tests</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{(tests??[]).map(test=><LiveTestCard key={test.id} test={test}/>) }{!tests?.length&&<p className="rounded-2xl bg-white p-7 text-slate-600 shadow">No free live test is scheduled yet. Please check again soon.</p>}</div><div className="mt-12 flex items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-blue-700">Released leaderboard</p><h2 className="mt-1 text-2xl font-black">Latest student results</h2></div></div><div className="mt-5"><LiveResultsTicker results={(results??[]) as PublicLiveResult[]}/></div><p className="mt-4 text-xs text-slate-500">Names are anonymized. Results appear automatically only after the administrator-scheduled publication time.</p></section></main>;
}

function LiveTestCard({test}:{test:{id:string;title:string;slug:string;description:string|null;language:string;duration_seconds:number;live_starts_at:string|null;live_ends_at:string|null;results_publish_at:string|null;is_live:boolean}}){const state=liveTestState({isLive:test.is_live,startsAt:test.live_starts_at,endsAt:test.live_ends_at,resultsPublishAt:test.results_publish_at});const action=state==="open"?"Start free live test":state==="upcoming"?"View schedule":state==="results-published"?"View published results":"Test closed — awaiting results";return <article className="rounded-2xl bg-white p-6 shadow"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-red-100 px-3 py-1 text-xs font-black text-red-700">FREE LIVE</span><span className="text-xs font-bold uppercase text-slate-500">{state.replace("-"," ")}</span></div><h3 className="mt-4 text-xl font-black">{test.title}</h3><p className="mt-2 text-sm text-slate-600">{test.description||"Samradhi Classes live typing test"}</p><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">Starts</dt><dd className="font-bold">{formatIST(test.live_starts_at)||"—"}</dd></div><div><dt className="text-slate-500">Ends</dt><dd className="font-bold">{formatIST(test.live_ends_at)||"—"}</dd></div><div><dt className="text-slate-500">Duration</dt><dd className="font-bold">{Math.round(test.duration_seconds/60)} minutes</dd></div><div><dt className="text-slate-500">Results</dt><dd className="font-bold">{formatIST(test.results_publish_at)||"—"}</dd></div></dl><Link href={state==="results-published"?"/live-test":`/tests/${test.slug}`} aria-disabled={state==="closed"} className={`mt-6 block rounded-xl px-4 py-3 text-center font-black ${state==="open"?"bg-green-600 text-white":"bg-blue-50 text-blue-700"}`}>{action}</Link></article>}
