import type { BackspaceMode, HighlightMode, WordMethod } from "./typing-test.ts";

export type ExamCategoryIconKind = "commission" | "medical" | "train" | "police" | "scales" | "book" | "flask" | "monitor";

export type ExamCategoryDefinition = {
  slug: string;
  name: string;
  fullName: string;
  badge: string;
  tone: string;
  toneDark: string;
  iconKind: ExamCategoryIconKind;
  /** Researched (or reasonably estimated) real exam pattern. Not exact official copies — a
   * close approximation to make the simulation realistic. See `patternSourced`. */
  speedEnglish: number;
  speedHindi: number;
  durationMinutes: number;
  accuracy: number;
  // Widened from "full" | "disabled" to the app's real BackspaceMode when
  // the Rajasthan LDC / RSMSSB category's genuine word-level-lock rule
  // (correct freely within the current word, locked forever once you press
  // Space or Enter -- see its patternNotes) needed the "word" value this
  // type had never allowed for any category before.
  backspaceMode: BackspaceMode;
  /** Board-specific overrides for the two typing-behaviour dimensions no category has
   * ever varied before -- undefined for every category except where explicitly
   * researched (e.g. Rajasthan LDC's real word-separated counting and no on-screen
   * highlight). Undefined means categoryPreset() falls back to its long-standing
   * defaults ("characters" word method, no highlight override) exactly as before. */
  wordMethod?: WordMethod;
  highlightMode?: HighlightMode;
  /** Board-specific override for the scoring engine's per-mistake penalty weights (default
   * for every other category: 1 for a full mistake, 0.5 for a half mistake -- a generic
   * approximation). Set only where a board's real, confirmed formula penalizes every
   * incorrect word identically regardless of severity (e.g. NCERT/DDA/SSC's shared
   * "(gross keystrokes / 5 - incorrect words x 10) / minutes" net-speed formula, which
   * draws no full/half distinction at all -- both fields are set to that same 10). */
  fullErrorPenalty?: number;
  halfErrorPenalty?: number;
  /** Hindi translation of patternNotes, shown on the Hindi half of the category rules page and
   * as this category's Hindi preset's own instructionNotes. Every category has one; kept optional
   * (defaultExamCategoryRules() falls back to the English patternNotes when absent) so a newly
   * added category still works correctly before its own translation is written. */
  patternNotesHindi?: string[];
  /** true = based on a specific recruiting authority's published pattern found during research;
   * false = no confirmed pattern found for this exact post, using a reasoned baseline from the
   * closest comparable exam family. Either way, always verify against the current notification. */
  patternSourced: boolean;
  patternNotes: string[];
};

const TONE_PALETTE: Array<[string, string]> = [
  ["#e11d48", "#9f1239"], ["#ea580c", "#9a3412"], ["#d97706", "#92400e"], ["#65a30d", "#3f6212"],
  ["#059669", "#065f46"], ["#0d9488", "#115e59"], ["#0891b2", "#155e75"], ["#2563eb", "#1e40af"],
  ["#4f46e5", "#3730a3"], ["#7c3aed", "#5b21b6"], ["#c026d3", "#86198f"], ["#db2777", "#9d174d"],
];

// patternNotes below were researched against typing-test-preparation guides that
// cite each board's own notifications (SSC, RRB, DSSSB, RSMSSB, court
// registries, etc.) as of September 2026, specifically for: the marking/error
// scheme (what counts as a full vs half mistake, marks-per-word where
// applicable), the backspace policy, and whether the real exam screen shows
// any live highlighting. Where sources conflicted or nothing could be
// confirmed, that conflict/gap is stated plainly rather than guessed at --
// see each category's patternSourced flag and the corresponding note.
const RAW_CATEGORIES: Array<Omit<ExamCategoryDefinition, "tone" | "toneDark">> = [
  { slug: "ssc-chsl", name: "SSC CHSL", badge: "CHSL", fullName: "Staff Selection Commission — Combined Higher Secondary Level", iconKind: "commission",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 15, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["Test duration is 15 minutes (20 minutes for candidates eligible for a scribe).", "The typing/DEST test itself carries no marks toward the final score, but failing it disqualifies the candidate regardless of other marks.", "Backspace is allowed under SSC's current clarification, but every backspace still counts toward your gross keystrokes, so overusing it lowers your net speed.", "Mistakes are split into full mistakes (wrong, omitted, or repeated words; spelling errors) and half mistakes (spacing, capitalization, punctuation, transposition); the combined error percentage must stay within the category-wise limit set in that year's notification — commonly around 7% for general-category candidates."],
    patternNotesHindi: ["परीक्षा की अवधि 15 मिनट है (लेखक/स्क्राइब की पात्रता रखने वाले उम्मीदवारों के लिए 20 मिनट)।", "टाइपिंग/डेस्ट परीक्षा स्वयं अंतिम स्कोर में कोई अंक नहीं जोड़ती, लेकिन इसमें असफल होने पर उम्मीदवार अन्य अंकों के बावजूद अयोग्य हो जाता है।", "एसएससी के वर्तमान स्पष्टीकरण के अनुसार बैकस्पेस की अनुमति है, लेकिन हर बैकस्पेस आपकी सकल की-स्ट्रोक्स में गिना जाता है, इसलिए अधिक उपयोग करने पर आपकी नेट स्पीड कम हो जाती है।", "गलतियों को पूर्ण गलती (गलत, छूटे हुए या दोहराए गए शब्द; वर्तनी की त्रुटियाँ) और आधी गलती (स्पेसिंग, कैपिटलाइज़ेशन, विराम चिह्न, अक्षर-क्रम बदलना) में बांटा जाता है; कुल त्रुटि प्रतिशत उस वर्ष की अधिसूचना में तय श्रेणी-वार सीमा के भीतर रहना चाहिए — सामान्य श्रेणी के उम्मीदवारों के लिए आमतौर पर लगभग 7%।"] },
  { slug: "ssc-cgl", name: "SSC CGL", badge: "CGL", fullName: "Staff Selection Commission — Combined Graduate Level", iconKind: "commission",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 15, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["The DEST is historically measured as about 2000 key depressions in 15 minutes (roughly 27–33 WPM); this simulation uses the standard SSC 35/30 WPM baseline.", "Qualifying only — it does not add to the final score, but you must clear it to remain in contention.", "Backspace is allowed at any point during the 15 minutes with no usage limit, but you cannot restart the passage from the beginning once you start typing — correct only as you go.", "Mistakes are graded as full mistakes (omitted, substituted, added, or repeated words; spelling errors) and half mistakes (spacing, capitalization, punctuation, transposition), converted to an error percentage of the whole passage. The pass threshold is category- and post-dependent — roughly 20% for general Group C/D posts down to 5% for higher-standard posts such as Tax Assistant or ASO — so always confirm against your specific post's notification."],
    patternNotesHindi: ["डेस्ट (DEST) परीक्षा पारंपरिक रूप से 15 मिनट में लगभग 2000 की-डिप्रेशन (लगभग 27–33 डब्ल्यूपीएम) के रूप में मापी जाती रही है; यह सिमुलेशन मानक एसएससी 35/30 डब्ल्यूपीएम आधार रेखा का उपयोग करता है।", "केवल अर्हकारी (क्वालिफाइंग) — यह अंतिम स्कोर में नहीं जुड़ता, लेकिन प्रतियोगिता में बने रहने के लिए इसे पास करना अनिवार्य है।", "15 मिनट के दौरान किसी भी समय बिना किसी सीमा के बैकस्पेस की अनुमति है, लेकिन टाइप करना शुरू करने के बाद आप गद्यांश को शुरू से दोबारा शुरू नहीं कर सकते — केवल आगे बढ़ते हुए ही सुधार करें।", "गलतियों को पूर्ण गलती (छूटे हुए, बदले हुए, जोड़े गए या दोहराए गए शब्द; वर्तनी की त्रुटियाँ) और आधी गलती (स्पेसिंग, कैपिटलाइज़ेशन, विराम चिह्न, अक्षर-क्रम बदलना) में आंका जाता है, जिन्हें पूरे गद्यांश के त्रुटि प्रतिशत में बदला जाता है। उत्तीर्ण सीमा श्रेणी और पद पर निर्भर करती है — सामान्य ग्रुप सी/डी पदों के लिए लगभग 20% से लेकर टैक्स असिस्टेंट या एएसओ जैसे उच्च-मानक पदों के लिए 5% तक — इसलिए हमेशा अपने विशिष्ट पद की अधिसूचना से पुष्टि करें।"] },
  { slug: "aiims-cre-ldc", name: "AIIMS CRE LDC", badge: "AIIMS", fullName: "All India Institute of Medical Sciences — Common Recruitment Exam, Lower Division Clerk", iconKind: "medical",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 15, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["Test duration is 15 minutes.", "Backspace is fully enabled — you can correct any earlier mistake at any point in the 15 minutes. Qualifying only.", "Minimum keystrokes to qualify: about 2625 in English or 2250 in Hindi within the 15 minutes, on top of the 35/30 WPM speed requirement."],
    patternNotesHindi: ["परीक्षा की अवधि 15 मिनट है।", "बैकस्पेस पूरी तरह सक्षम है — आप 15 मिनट के दौरान किसी भी समय पहले की कोई भी गलती ठीक कर सकते हैं। केवल अर्हकारी (क्वालिफाइंग)।", "उत्तीर्ण होने के लिए न्यूनतम की-स्ट्रोक्स: 15 मिनट में अंग्रेज़ी में लगभग 2625 या हिंदी में लगभग 2250, 35/30 डब्ल्यूपीएम गति की आवश्यकता के अतिरिक्त।"] },
  { slug: "rrb-ntpc", name: "RRB NTPC", badge: "NTPC", fullName: "Railway Recruitment Board — Non-Technical Popular Categories", iconKind: "train",
    speedEnglish: 30, speedHindi: 25, durationMinutes: 10, accuracy: 95, backspaceMode: "disabled", patternSourced: true,
    patternNotes: ["A 5% error margin is allowed; beyond that, each mistake is penalised as 10 words.", "Backspace is not permitted in the real exam. Hindi uses the InScript or Remington Gail layout.", "Errors are graded word-by-word as full and half mistakes; the first 5% of mistyped words are ignored, and every mistake past that deducts the equivalent of 10 words (50 keystrokes) from your final score."],
    patternNotesHindi: ["5% त्रुटि की छूट दी जाती है; इससे अधिक होने पर हर गलती को 10 शब्दों के बराबर दंडित किया जाता है।", "वास्तविक परीक्षा में बैकस्पेस की अनुमति नहीं है। हिंदी के लिए इनस्क्रिप्ट (InScript) या रेमिंग्टन गेल लेआउट उपयोग होता है।", "त्रुटियों को शब्द-दर-शब्द पूर्ण और आधी गलती के रूप में आंका जाता है; गलत टाइप किए गए पहले 5% शब्दों को नज़रअंदाज़ किया जाता है, और उसके बाद हर गलती आपके अंतिम स्कोर से 10 शब्दों (50 की-स्ट्रोक्स) के बराबर काट लेती है।"] },
  { slug: "crpf-hcm", name: "CRPF HCM", badge: "CRPF", fullName: "Central Reserve Police Force — Head Constable (Ministerial)", iconKind: "police",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 10, accuracy: 95, backspaceMode: "disabled", patternSourced: true,
    patternNotes: ["The same standard applies across CRPF, BSF, CISF, ITBP, and SSB Head Constable (Ministerial) posts.", "A 5% error margin is allowed; beyond that, each mistake is penalised as 10 words. Paper-to-screen format on centre-provided computers only.", "Backspace is commonly disabled for CRPF and CISF specifically, though the CAPF-wide policy has varied by force and notification cycle (BSF has sometimes allowed it) — this simulation uses backspace disabled as the standard baseline for CRPF. Confirm against your specific force's current notification."],
    patternNotesHindi: ["यही मानक सीआरपीएफ, बीएसएफ, सीआईएसएफ, आईटीबीपी और एसएसबी हेड कांस्टेबल (मंत्रालयिक) पदों पर समान रूप से लागू होता है।", "5% त्रुटि की छूट दी जाती है; इससे अधिक होने पर हर गलती को 10 शब्दों के बराबर दंडित किया जाता है। यह पेपर-से-स्क्रीन प्रारूप है, केवल परीक्षा केंद्र द्वारा उपलब्ध कराए गए कंप्यूटरों पर।", "सीआरपीएफ और सीआईएसएफ के लिए विशेष रूप से बैकस्पेस आमतौर पर अक्षम रहता है, हालांकि सीएपीएफ-व्यापी नीति बल और अधिसूचना चक्र के अनुसार बदलती रही है (बीएसएफ ने कभी-कभी इसकी अनुमति दी है) — यह सिमुलेशन सीआरपीएफ के लिए मानक आधार रेखा के रूप में बैकस्पेस अक्षम रखता है। अपने विशिष्ट बल की वर्तमान अधिसूचना से पुष्टि करें।"] },
  { slug: "dsssb-ldc", name: "DSSSB LDC", badge: "DSSSB", fullName: "Delhi Subordinate Services Selection Board — Lower Division Clerk", iconKind: "commission",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 10, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["Screen-to-screen mode — the passage is shown on screen, not printed on paper.", "Backspace is permitted, but typed text is not highlighted as you go — the real DSSSB interface shows no live word or error highlighting, and the passage does not auto-scroll for you. Mistakes only become visible after you submit.", "This simulator highlights your current position and auto-scrolls as a training aid, which the real DSSSB screen does not do — practice occasionally with a highlight setting of \"None\" from Settings to get used to typing without that cue."],
    patternNotesHindi: ["स्क्रीन-टू-स्क्रीन मोड — गद्यांश स्क्रीन पर दिखाया जाता है, कागज़ पर छपा हुआ नहीं।", "बैकस्पेस की अनुमति है, लेकिन टाइप करते समय टेक्स्ट हाइलाइट नहीं होता — वास्तविक डीएसएसएसबी इंटरफ़ेस में कोई लाइव शब्द या त्रुटि हाइलाइटिंग नहीं दिखती, और गद्यांश आपके लिए ऑटो-स्क्रॉल भी नहीं होता। गलतियाँ सबमिट करने के बाद ही दिखाई देती हैं।", "यह सिमुलेटर अभ्यास सहायता के रूप में आपकी वर्तमान स्थिति को हाइलाइट करता है और ऑटो-स्क्रॉल करता है, जो वास्तविक डीएसएसएसबी स्क्रीन नहीं करती — बिना उस संकेत के टाइप करने का अभ्यास करने के लिए कभी-कभी सेटिंग्स में हाइलाइट को \"कोई नहीं (None)\" पर सेट करके अभ्यास करें।"] },
  { slug: "up-police-computer-operator", name: "UP Police Computer Operator", badge: "UPP", fullName: "Uttar Pradesh Police — Computer Operator", iconKind: "police",
    speedEnglish: 30, speedHindi: 25, durationMinutes: 15, accuracy: 85, backspaceMode: "full", patternSourced: true,
    patternNotes: ["Modelled on the UPPRPB Computer Operator pattern: a 500-word English passage in 15 minutes at 30 WPM with 85% accuracy, and a 400-word Hindi passage at 25 WPM with 85% accuracy on the Unicode InScript keyboard.", "Backspace can be used to correct typed words, but frequent use noticeably reduces your gross-to-net speed conversion.", "Wrong, missing, or extra words count as full mistakes; spacing and capitalization count as half mistakes. Net WPM is (total words − full mistakes − half mistakes ÷ 2) ÷ minutes.", "The test is qualifying only, with no live error highlighting in the real interface."],
    patternNotesHindi: ["यूपीपीआरपीबी कंप्यूटर ऑपरेटर पैटर्न पर आधारित: 15 मिनट में 30 डब्ल्यूपीएम पर 500-शब्दों का अंग्रेज़ी गद्यांश, 85% सटीकता के साथ, और यूनिकोड इनस्क्रिप्ट कीबोर्ड पर 25 डब्ल्यूपीएम पर 400-शब्दों का हिंदी गद्यांश, 85% सटीकता के साथ।", "टाइप किए गए शब्दों को ठीक करने के लिए बैकस्पेस का उपयोग किया जा सकता है, लेकिन इसका बार-बार उपयोग आपकी सकल-से-नेट स्पीड रूपांतरण को काफी कम कर देता है।", "गलत, छूटे हुए या अतिरिक्त शब्द पूर्ण गलती में गिने जाते हैं; स्पेसिंग और कैपिटलाइज़ेशन आधी गलती में गिने जाते हैं। नेट डब्ल्यूपीएम = (कुल शब्द − पूर्ण गलतियाँ − आधी गलतियाँ ÷ 2) ÷ मिनट।", "यह परीक्षा केवल अर्हकारी (क्वालिफाइंग) है, और वास्तविक इंटरफ़ेस में कोई लाइव त्रुटि हाइलाइटिंग नहीं होती।"] },
  { slug: "rajasthan-high-court-ldc", name: "Rajasthan High Court LDC", badge: "RHC", fullName: "Rajasthan High Court — Lower Division Clerk", iconKind: "scales",
    speedEnglish: 40, speedHindi: 35, durationMinutes: 10, accuracy: 95, backspaceMode: "full", patternSourced: false,
    patternNotes: ["Modelled on the Rajasthan LDC/Stenographer typing benchmark of 40 WPM English / 35 WPM Hindi at 95% accuracy.", "Published sources disagree on the exact scheme — some describe a marks-based test (up to 50 marks, a roughly 25 net-WPM benchmark), others a straightforward speed-and-accuracy qualifying test, and backspace availability is reported both ways.", "Verify against the specific Rajasthan High Court LDC notification before your real exam."],
    patternNotesHindi: ["राजस्थान एलडीसी/स्टेनोग्राफर टाइपिंग मानक — अंग्रेज़ी में 40 डब्ल्यूपीएम / हिंदी में 35 डब्ल्यूपीएम, 95% सटीकता के साथ — पर आधारित।", "प्रकाशित स्रोत सटीक योजना पर असहमत हैं — कुछ इसे अंकों पर आधारित परीक्षा (अधिकतम 50 अंक, लगभग 25 नेट-डब्ल्यूपीएम मानक) बताते हैं, तो अन्य इसे केवल गति-और-सटीकता वाली अर्हकारी परीक्षा बताते हैं, और बैकस्पेस की उपलब्धता भी दोनों तरह से बताई गई है।", "अपनी वास्तविक परीक्षा से पहले विशिष्ट राजस्थान हाई कोर्ट एलडीसी अधिसूचना से पुष्टि करें।"] },
  { slug: "delhi-police-hcm", name: "Delhi Police HCM", badge: "DP", fullName: "Delhi Police — Head Constable (Ministerial)", iconKind: "police",
    speedEnglish: 30, speedHindi: 25, durationMinutes: 10, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["The real passage is at least 400 words (2000 strokes) in English or 350 words (1750 strokes) in Hindi.", "Every remaining error reduces the final speed by exactly 1 WPM — there is no partial-mistake concession. Paper-to-screen format, maximum 25 marks.", "Backspace is permitted for corrections before you move on, unlike the stricter CAPF Head Constable Ministerial standard above — but since every uncorrected error still costs a full WPM, correct deliberately rather than typing fast and hoping to fix it later."],
    patternNotesHindi: ["वास्तविक गद्यांश अंग्रेज़ी में कम से कम 400 शब्द (2000 स्ट्रोक्स) या हिंदी में 350 शब्द (1750 स्ट्रोक्स) का होता है।", "बची हुई हर गलती अंतिम गति को ठीक 1 डब्ल्यूपीएम कम कर देती है — किसी आंशिक-गलती में कोई राहत नहीं है। यह पेपर-से-स्क्रीन प्रारूप है, अधिकतम 25 अंक।", "ऊपर बताए गए सख़्त सीएपीएफ हेड कांस्टेबल (मंत्रालयिक) मानक के विपरीत, आगे बढ़ने से पहले सुधार के लिए बैकस्पेस की अनुमति है — लेकिन चूंकि हर बिना सुधारी गलती फिर भी पूरा 1 डब्ल्यूपीएम खर्च करती है, इसलिए तेज़ टाइप करके बाद में ठीक करने की उम्मीद रखने के बजाय सोच-समझकर सुधार करें।"] },
  { slug: "bihar-civil-court-clerk", name: "Bihar Civil Court Clerk", badge: "BCC", fullName: "Bihar Civil Court — Clerk", iconKind: "scales",
    speedEnglish: 30, speedHindi: 25, durationMinutes: 10, accuracy: 90, backspaceMode: "full", patternSourced: false,
    patternNotes: ["No confirmed pattern found for this exact post; using a typical subordinate-court clerk baseline (35 WPM English / 30 WPM Hindi-family benchmark and ~95% accuracy are common across comparable subordinate courts, so treat this simulation's numbers as a gentler starting point, not the ceiling).", "Backspace policy for subordinate-court clerk exams varies significantly by court and notification — some allow free correction, others lock text in permanently. We could not locate a published typing-specific rulebook from Bihar's own recruiting body; verify against the latest Bihar Civil Court recruitment notification."],
    patternNotesHindi: ["इस विशिष्ट पद के लिए कोई पुष्ट पैटर्न नहीं मिला; एक सामान्य अधीनस्थ-न्यायालय क्लर्क आधार रेखा का उपयोग किया गया है (तुलनीय अधीनस्थ न्यायालयों में आमतौर पर अंग्रेज़ी में 35 डब्ल्यूपीएम / हिंदी-परिवार में 30 डब्ल्यूपीएम और लगभग 95% सटीकता प्रचलित है, इसलिए इस सिमुलेशन के आंकड़ों को एक सहज शुरुआती बिंदु मानें, ऊपरी सीमा नहीं)।", "अधीनस्थ-न्यायालय क्लर्क परीक्षाओं में बैकस्पेस नीति न्यायालय और अधिसूचना के अनुसार काफी भिन्न होती है — कुछ में मुक्त सुधार की अनुमति है, तो कुछ में टेक्स्ट स्थायी रूप से लॉक हो जाता है। हमें बिहार के अपने भर्ती निकाय से कोई प्रकाशित टाइपिंग-विशिष्ट नियम-पुस्तिका नहीं मिली; नवीनतम बिहार सिविल कोर्ट भर्ती अधिसूचना से पुष्टि करें।"] },
  { slug: "rajasthan-ldc", name: "RAJASTHAN LDC", badge: "RSMSSB", fullName: "Rajasthan Subordinate & Ministerial Services Selection Board — Lower Division Clerk", iconKind: "commission",
    // speedEnglish/speedHindi represent the pace needed for full marks
    // (25/25), not a separate qualifying threshold: 500 words / 10 min =
    // exactly 50 WPM English, 400 words / 10 min = exactly 40 WPM Hindi --
    // the same numbers the marks scheme already implies, confirmed directly
    // by the user against RSSB's own published rules.
    speedEnglish: 50, speedHindi: 40, durationMinutes: 10, accuracy: 95, backspaceMode: "word", wordMethod: "spaces", highlightMode: "none", patternSourced: true,
    patternNotes: ["Modelled on the RSSB/RSMSSB LDC & Junior Assistant pattern: a 500-word English and 400-word Hindi passage in 10 minutes, marks-based (25 maximum, 9 to qualify). Hindi font: DevLys 010 with the Remington Gail layout.", "Marks are earned per correct word only — 0.05 marks/word in English (need 180 of 500 words correct, 36%, for the 9-mark minimum) and 0.0625 marks/word in Hindi (need 144 of 400 words correct, also 36%). There is no negative marking for wrong words — an incorrect word simply earns nothing.", "Full marks (25/25) require typing the whole passage correctly within the 10 minutes — 50 WPM in English, 40 WPM in Hindi, both at the 95% accuracy shown above.", "The moment you press Space or Enter, the word you just typed is locked forever — backspace only works within the word currently being typed, never on a completed one.", "There is no on-screen highlighting of your current position, and words are counted by spaces (not the SSC-style 5-characters-per-word convention) — matching the real RSSB screen and its per-word marking scheme."],
    patternNotesHindi: ["आरएसएसबी/आरएसएमएसएसबी एलडीसी और जूनियर असिस्टेंट पैटर्न पर आधारित: 10 मिनट में 500-शब्दों का अंग्रेज़ी और 400-शब्दों का हिंदी गद्यांश, अंकों पर आधारित (अधिकतम 25, अर्हकारी न्यूनतम 9)। हिंदी फ़ॉन्ट: रेमिंग्टन गेल लेआउट के साथ डेवलिस 010।", "अंक केवल सही शब्दों के आधार पर मिलते हैं — अंग्रेज़ी में 0.05 अंक प्रति शब्द (9-अंक की न्यूनतम सीमा के लिए 500 में से 180 शब्द सही होने चाहिए, यानी 36%) और हिंदी में 0.0625 अंक प्रति शब्द (400 में से 144 शब्द सही होने चाहिए, वही 36%)। गलत शब्दों के लिए कोई ऋणात्मक अंकन नहीं है — गलत शब्द बस कोई अंक नहीं दिलाता।", "पूर्ण अंक (25/25) पाने के लिए 10 मिनट के भीतर पूरा गद्यांश सही टाइप करना ज़रूरी है — अंग्रेज़ी में 50 डब्ल्यूपीएम, हिंदी में 40 डब्ल्यूपीएम, दोनों ऊपर बताई गई 95% सटीकता पर।", "जिस क्षण आप स्पेस या एंटर दबाते हैं, अभी टाइप किया गया शब्द हमेशा के लिए लॉक हो जाता है — बैकस्पेस केवल उस शब्द के भीतर काम करता है जो अभी टाइप हो रहा है, कभी पूरे हो चुके शब्द पर नहीं।", "आपकी वर्तमान स्थिति की कोई ऑन-स्क्रीन हाइलाइटिंग नहीं होती, और शब्द स्पेस के आधार पर गिने जाते हैं (एसएससी-शैली के 5-अक्षर-प्रति-शब्द नियम के अनुसार नहीं) — यह वास्तविक आरएसएसबी स्क्रीन और उसकी प्रति-शब्द अंकन योजना से मेल खाता है।"] },
  { slug: "upsssc-assistants", name: "UPSSSC Assistants", badge: "UPSSSC", fullName: "UP Subordinate Services Selection Commission — Junior Assistant", iconKind: "commission",
    speedEnglish: 30, speedHindi: 25, durationMinutes: 5, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["English and Hindi are tested separately, 5 minutes each, in the real exam (this simulation runs one language for the full duration).", "Backspace may correct only the current word and the one word immediately before it — a maximum of two words in total; you cannot go back further to fix an earlier mistake. Hindi is typed in Kruti Dev 010 or Mangal, per the notification.", "Each word in the passage is highlighted one at a time as you type it, moving to the next word once you press Space. A grace of up to 5 mistakes is given — if you make 5 or fewer, your speed is calculated on the full word count typed."],
    patternNotesHindi: ["वास्तविक परीक्षा में अंग्रेज़ी और हिंदी की जांच अलग-अलग होती है, प्रत्येक 5 मिनट के लिए (यह सिमुलेशन पूरी अवधि के लिए एक ही भाषा चलाता है)।", "बैकस्पेस केवल वर्तमान शब्द और उससे ठीक पहले वाले शब्द को ही सुधार सकता है — कुल मिलाकर अधिकतम दो शब्द; इससे पहले की किसी गलती को ठीक करने के लिए आप वापस नहीं जा सकते। अधिसूचना के अनुसार हिंदी कृति देव 010 या मंगल में टाइप की जाती है।", "गद्यांश का हर शब्द टाइप करते समय एक-एक करके हाइलाइट होता है, स्पेस दबाते ही अगले शब्द पर चला जाता है। अधिकतम 5 गलतियों तक की छूट दी जाती है — यदि आप 5 या उससे कम गलतियाँ करते हैं, तो आपकी गति पूरे टाइप किए गए शब्दों की गिनती पर आंकी जाती है।"] },
  { slug: "kvs-jsa", name: "KVS JSA", badge: "KVS", fullName: "Kendriya Vidyalaya Sangathan — Junior Secretariat Assistant", iconKind: "book",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 10, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["A 5% error tolerance applies in most notifications — about 5 mistakes per 100 words typed — though some cycles have reported figures as high as 20%, so treat the app's accuracy requirement as a solid practice target rather than a guaranteed official cutoff.", "Backspace is fully enabled with no restriction.", "The real KVS JSA screen shows no live word highlight, no error highlight, and no auto-scroll — unlike this simulator's on-screen aids, you're on your own to track your position."],
    patternNotesHindi: ["अधिकांश अधिसूचनाओं में 5% त्रुटि की छूट लागू होती है — प्रति 100 टाइप किए गए शब्दों में लगभग 5 गलतियाँ — हालांकि कुछ चक्रों में यह आंकड़ा 20% तक बताया गया है, इसलिए ऐप की सटीकता आवश्यकता को एक ठोस अभ्यास लक्ष्य मानें, न कि एक निश्चित आधिकारिक सीमा।", "बैकस्पेस बिना किसी प्रतिबंध के पूरी तरह सक्षम है।", "वास्तविक केवीएस जेएसए स्क्रीन में कोई लाइव शब्द हाइलाइट, कोई त्रुटि हाइलाइट, और कोई ऑटो-स्क्रॉल नहीं दिखता — इस सिमुलेटर की ऑन-स्क्रीन सहायता के विपरीत, वहां आपको अपनी स्थिति खुद ट्रैक करनी होती है।"] },
  { slug: "emrs-jsa", name: "EMRS JSA", badge: "EMRS", fullName: "Eklavya Model Residential Schools — Junior Secretariat Assistant", iconKind: "book",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 10, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["Backspace use is effectively unlimited in the real exam — correcting a mistake costs a few seconds, but an uncorrected one can cost you the qualifying cutoff, so use it freely.", "Typing is Tier-III of the selection process (after a qualifying Tier-I and a merit-determining Tier-II) — it does not add marks to your final merit, it is a pass/fail hurdle you must clear after the written stages.", "Expect roughly 1750+ keystrokes within the 10-minute window at the 35/30 WPM requirement; the exact marks-deduction schedule for wrong words has not been published in the notifications we could find."],
    patternNotesHindi: ["वास्तविक परीक्षा में बैकस्पेस का उपयोग व्यावहारिक रूप से असीमित है — गलती सुधारने में कुछ सेकंड लगते हैं, लेकिन बिना सुधारी गलती आपको अर्हकारी सीमा से बाहर कर सकती है, इसलिए इसका खुलकर उपयोग करें।", "टाइपिंग चयन प्रक्रिया का टियर-III है (एक अर्हकारी टियर-I और मेरिट तय करने वाले टियर-II के बाद) — यह आपकी अंतिम मेरिट में अंक नहीं जोड़ती, यह लिखित चरणों के बाद पास/फेल की एक बाधा है जिसे पार करना ज़रूरी है।", "35/30 डब्ल्यूपीएम की आवश्यकता पर 10 मिनट के भीतर लगभग 1750+ की-स्ट्रोक्स की अपेक्षा करें; गलत शब्दों के लिए सटीक अंक-कटौती अनुसूची हमें मिली अधिसूचनाओं में प्रकाशित नहीं की गई है।"] },
  { slug: "supreme-court-jca", name: "Supreme Court JCA", badge: "SC", fullName: "Supreme Court of India — Junior Court Assistant", iconKind: "scales",
    speedEnglish: 35, speedHindi: 35, durationMinutes: 10, accuracy: 97, backspaceMode: "full", patternSourced: true,
    patternNotes: ["English only in the real exam — there is no Hindi typing option for this post.", "Only 3% errors are allowed (97%+ accuracy). The real passage is exactly 1750 keystrokes (350 words).", "The typing test carries 50 maximum marks with 25 required to qualify — awarded independently of, and in addition to, the minimum 35 net WPM speed requirement."],
    patternNotesHindi: ["वास्तविक परीक्षा में केवल अंग्रेज़ी होती है — इस पद के लिए हिंदी टाइपिंग का कोई विकल्प नहीं है।", "केवल 3% त्रुटि की अनुमति है (97%+ सटीकता)। वास्तविक गद्यांश ठीक 1750 की-स्ट्रोक्स (350 शब्द) का होता है।", "टाइपिंग परीक्षा में अधिकतम 50 अंक होते हैं जिनमें से अर्हकारी होने के लिए 25 चाहिए — ये अंक न्यूनतम 35 नेट डब्ल्यूपीएम गति की आवश्यकता से स्वतंत्र रूप से, और उसके अतिरिक्त दिए जाते हैं।"] },
  { slug: "allahabad-hc-ro-aro", name: "Allahabad High Court RO/ARO", badge: "AHC", fullName: "Allahabad High Court — Review Officer / Assistant Review Officer", iconKind: "scales",
    speedEnglish: 25, speedHindi: 25, durationMinutes: 20, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["English only, reflecting court/legal drafting work.", "The real scheme deducts 0.1 marks per confirmed error (not a percentage): 25 of 50 marks are needed to qualify, alongside 25+ net WPM independently.", "No error highlighting while typing — you must proofread visually as you go, since mistakes are never flagged on screen. Backspace is enabled with no usage penalty."],
    patternNotesHindi: ["केवल अंग्रेज़ी, जो न्यायालय/कानूनी प्रारूपण कार्य को दर्शाती है।", "वास्तविक योजना में हर पुष्ट गलती पर 0.1 अंक काटे जाते हैं (प्रतिशत के रूप में नहीं): अर्हकारी होने के लिए 50 में से 25 अंक चाहिए, साथ ही स्वतंत्र रूप से 25+ नेट डब्ल्यूपीएम भी चाहिए।", "टाइप करते समय कोई त्रुटि हाइलाइटिंग नहीं होती — चूंकि गलतियाँ स्क्रीन पर कभी नहीं दिखाई जातीं, इसलिए आपको खुद दृष्टि से जांचते हुए आगे बढ़ना होता है। बैकस्पेस बिना किसी उपयोग-दंड के सक्षम है।"] },
  { slug: "allahabad-hc-ps", name: "Allahabad High Court P.S.", badge: "AHC", fullName: "Allahabad High Court — Personal Secretary", iconKind: "scales",
    speedEnglish: 25, speedHindi: 25, durationMinutes: 20, accuracy: 90, backspaceMode: "full", patternSourced: false,
    patternNotes: ["Personal Secretary posts usually also require shorthand/stenography skill in addition to typing — check the specific notification.", "Typing baseline modelled on the Allahabad High Court RO/ARO pattern: 0.1 marks deducted per confirmed error, 25 of 50 marks to qualify, no on-screen error highlighting, backspace enabled."],
    patternNotesHindi: ["पर्सनल सेक्रेटरी पदों के लिए आमतौर पर टाइपिंग के अलावा शॉर्टहैंड/स्टेनोग्राफी कौशल भी आवश्यक होता है — विशिष्ट अधिसूचना अवश्य जांचें।", "टाइपिंग आधार रेखा इलाहाबाद हाई कोर्ट आरओ/एआरओ पैटर्न पर आधारित है: हर पुष्ट गलती पर 0.1 अंक की कटौती, अर्हकारी होने के लिए 50 में से 25 अंक, कोई ऑन-स्क्रीन त्रुटि हाइलाइटिंग नहीं, बैकस्पेस सक्षम।"] },
  { slug: "csir-jsa", name: "CSIR JSA", badge: "CSIR", fullName: "Council of Scientific & Industrial Research — Junior Secretariat Assistant", iconKind: "flask",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 10, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["Paper-to-screen format — the passage is printed, not shown on screen.", "Up to 5% mistakes are ignored for UR/EWS/OBC/SC/OH/VH candidates, and up to 7% for ST/HH/Ex-servicemen candidates, before any further penalty applies.", "You must type the passage from beginning to end within the 10-minute window — there's no separate correction phase once time runs out."],
    patternNotesHindi: ["पेपर-से-स्क्रीन प्रारूप — गद्यांश छपा हुआ होता है, स्क्रीन पर नहीं दिखाया जाता।", "यूआर/ईडब्ल्यूएस/ओबीसी/एससी/ओएच/वीएच उम्मीदवारों के लिए 5% तक की गलतियाँ नज़रअंदाज़ की जाती हैं, और एसटी/एचएच/भूतपूर्व सैनिक उम्मीदवारों के लिए 7% तक — इसके बाद ही कोई और दंड लागू होता है।", "आपको 10 मिनट के भीतर गद्यांश शुरू से अंत तक टाइप करना होता है — समय समाप्त होने के बाद कोई अलग सुधार चरण नहीं होता।"] },
  { slug: "jharkhand-hc-assistant", name: "Jharkhand High Court Assistant", badge: "JHC", fullName: "Jharkhand High Court — Assistant", iconKind: "scales",
    speedEnglish: 30, speedHindi: 25, durationMinutes: 10, accuracy: 90, backspaceMode: "full", patternSourced: false,
    patternNotes: ["No confirmed pattern found for this exact post; using a typical High Court assistant baseline.", "We could not locate a published typing-specific rulebook (marking scheme, backspace policy, or highlighting behaviour) for this post — verify against the latest Jharkhand High Court notification."],
    patternNotesHindi: ["इस विशिष्ट पद के लिए कोई पुष्ट पैटर्न नहीं मिला; एक सामान्य हाई कोर्ट असिस्टेंट आधार रेखा का उपयोग किया गया है।", "इस पद के लिए हमें कोई प्रकाशित टाइपिंग-विशिष्ट नियम-पुस्तिका (अंकन योजना, बैकस्पेस नीति, या हाइलाइटिंग व्यवहार) नहीं मिली — नवीनतम झारखंड हाई कोर्ट अधिसूचना से पुष्टि करें।"] },
  { slug: "bsf-hcm", name: "BSF HCM", badge: "BSF", fullName: "Border Security Force — Head Constable (Ministerial)", iconKind: "police",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 10, accuracy: 95, backspaceMode: "disabled", patternSourced: true,
    patternNotes: ["Same CAPF-wide standard as CRPF, CISF, ITBP, and SSB Head Constable (Ministerial). A 5% error margin is allowed; beyond that, each mistake is penalised as 10 words.", "BSF's own skill test has, in some notification cycles, allowed backspace even where CRPF/CISF disabled it — this simulation keeps backspace disabled to match the conservative CAPF-wide baseline above; confirm against BSF's current notification if you specifically need it enabled."],
    patternNotesHindi: ["सीआरपीएफ, सीआईएसएफ, आईटीबीपी और एसएसबी हेड कांस्टेबल (मंत्रालयिक) जैसा ही सीएपीएफ-व्यापी मानक। 5% त्रुटि की छूट दी जाती है; इससे अधिक होने पर हर गलती को 10 शब्दों के बराबर दंडित किया जाता है।", "बीएसएफ की अपनी कौशल परीक्षा ने कुछ अधिसूचना चक्रों में बैकस्पेस की अनुमति दी है, वहां भी जहां सीआरपीएफ/सीआईएसएफ ने इसे अक्षम रखा — यह सिमुलेशन ऊपर बताई गई सतर्क सीएपीएफ-व्यापी आधार रेखा से मेल खाने के लिए बैकस्पेस अक्षम रखता है; यदि आपको विशेष रूप से इसकी सक्षम स्थिति चाहिए तो बीएसएफ की वर्तमान अधिसूचना से पुष्टि करें।"] },
  { slug: "delhi-hc-jja", name: "Delhi High Court JJA", badge: "DHC", fullName: "Delhi High Court — Junior Judicial Assistant", iconKind: "scales",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 10, accuracy: 90, backspaceMode: "full", patternSourced: false,
    patternNotes: ["No separately confirmed pattern found for Junior Judicial Assistant; using the common Delhi-administrative typing baseline.", "Some sources report a stricter 3% error tolerance (97%+ accuracy) for this post and disagree with each other on whether backspace is enabled — until an official notification is confirmed, this simulation keeps the general baseline above. Verify against the latest Delhi High Court notification."],
    patternNotesHindi: ["जूनियर ज्यूडिशियल असिस्टेंट के लिए अलग से कोई पुष्ट पैटर्न नहीं मिला; सामान्य दिल्ली-प्रशासनिक टाइपिंग आधार रेखा का उपयोग किया गया है।", "कुछ स्रोत इस पद के लिए अधिक सख़्त 3% त्रुटि सहनशीलता (97%+ सटीकता) बताते हैं और बैकस्पेस सक्षम है या नहीं, इस पर आपस में असहमत हैं — जब तक कोई आधिकारिक अधिसूचना पुष्ट नहीं होती, यह सिमुलेशन ऊपर बताई गई सामान्य आधार रेखा बनाए रखता है। नवीनतम दिल्ली हाई कोर्ट अधिसूचना से पुष्टि करें।"] },
  { slug: "bombay-hc-clerk", name: "Bombay High Court Clerk", badge: "BHC", fullName: "Bombay High Court — Clerk", iconKind: "scales",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 10, accuracy: 90, backspaceMode: "disabled", patternSourced: true,
    patternNotes: ["The real exam tests English and Marathi, not Hindi — Hindi is used here only as the closest supported regional-language option.", "Personal Assistant/Senior Clerk posts require a higher 40 WPM English; Junior Clerk/Typist posts (this simulation's baseline) require 35 WPM English / 30 WPM Marathi.", "1 mark is deducted per 4 word mistakes, with a maximum 2% error rate permitted; backspace is disabled."],
    patternNotesHindi: ["वास्तविक परीक्षा में अंग्रेज़ी और मराठी की जांच होती है, हिंदी की नहीं — यहां हिंदी का उपयोग केवल निकटतम समर्थित क्षेत्रीय-भाषा विकल्प के रूप में किया गया है।", "पर्सनल असिस्टेंट/सीनियर क्लर्क पदों के लिए उच्च 40 डब्ल्यूपीएम अंग्रेज़ी चाहिए; जूनियर क्लर्क/टाइपिस्ट पदों (इस सिमुलेशन की आधार रेखा) के लिए 35 डब्ल्यूपीएम अंग्रेज़ी / 30 डब्ल्यूपीएम मराठी चाहिए।", "हर 4 शब्दों की गलती पर 1 अंक काटा जाता है, अधिकतम 2% त्रुटि दर की अनुमति है; बैकस्पेस अक्षम है।"] },
  { slug: "mp-cpct", name: "MP CPCT", badge: "CPCT", fullName: "Madhya Pradesh — Computer Proficiency Certification Test", iconKind: "monitor",
    speedEnglish: 30, speedHindi: 20, durationMinutes: 5, accuracy: 95, backspaceMode: "full", patternSourced: true,
    patternNotes: ["The real CPCT typing component runs only 5 minutes per language (English or Hindi, candidate's choice) — shorter than most other exams on this list.", "A net speed of 30 WPM (English) or 20 WPM (Hindi) at roughly 95% accuracy is the qualifying benchmark; CPCT then converts your actual net speed into a scaled score between 50% and 100%, so a faster, cleaner attempt scores higher rather than just \"pass/fail\".", "CPCT runs an \"Unrestricted Typing\" mode where backspace is fully usable; word highlighting, error highlighting, and auto-scrolling are all enabled on the real screen — one of the few exams on this list where the live interface works much like this simulator's."],
    patternNotesHindi: ["वास्तविक सीपीसीटी टाइपिंग घटक प्रति भाषा (अंग्रेज़ी या हिंदी, उम्मीदवार की पसंद) केवल 5 मिनट चलता है — इस सूची की अधिकांश अन्य परीक्षाओं से छोटा।", "लगभग 95% सटीकता पर 30 डब्ल्यूपीएम (अंग्रेज़ी) या 20 डब्ल्यूपीएम (हिंदी) की नेट स्पीड अर्हकारी मानक है; इसके बाद सीपीसीटी आपकी वास्तविक नेट स्पीड को 50% से 100% के बीच एक स्केल किए गए स्कोर में बदल देता है, इसलिए तेज़ और साफ़ प्रयास केवल \"पास/फेल\" के बजाय अधिक स्कोर दिलाता है।", "सीपीसीटी एक \"अप्रतिबंधित टाइपिंग (Unrestricted Typing)\" मोड में चलता है जहां बैकस्पेस पूरी तरह उपयोग किया जा सकता है; वास्तविक स्क्रीन पर शब्द हाइलाइटिंग, त्रुटि हाइलाइटिंग और ऑटो-स्क्रॉलिंग तीनों सक्षम रहते हैं — इस सूची की उन कुछ परीक्षाओं में से एक जहां लाइव इंटरफ़ेस इस सिमुलेटर जैसा ही काम करता है।"] },
  { slug: "patna-hc-computer-operator", name: "Patna High Court Computer Operator", badge: "PHC", fullName: "Patna High Court — Computer Operator", iconKind: "scales",
    speedEnglish: 40, speedHindi: 30, durationMinutes: 10, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["Passage length is about 400 words in English or 300 words in Hindi (plus or minus 5%), typed within the 10-minute window. English requires roughly 90% accuracy, Hindi roughly 85%.", "Scoring is percentage-based: for example, 40 WPM at 96% accuracy scores about 96 out of 100 for the typing component, rather than a flat pass/fail.", "Candidate reports on backspace availability conflict between recruitment cycles — this simulation keeps backspace enabled as the more commonly reported setting, but confirm against your admit card and exam-day instructions."],
    patternNotesHindi: ["गद्यांश की लंबाई अंग्रेज़ी में लगभग 400 शब्द या हिंदी में लगभग 300 शब्द (5% कम-ज़्यादा) होती है, जिसे 10 मिनट के भीतर टाइप करना होता है। अंग्रेज़ी में लगभग 90% सटीकता चाहिए, हिंदी में लगभग 85%।", "स्कोरिंग प्रतिशत-आधारित है: उदाहरण के लिए, 96% सटीकता पर 40 डब्ल्यूपीएम टाइपिंग घटक में 100 में से लगभग 96 अंक दिलाता है, न कि केवल पास/फेल।", "बैकस्पेस की उपलब्धता को लेकर उम्मीदवारों की रिपोर्टें भर्ती चक्रों के बीच परस्पर विरोधाभासी हैं — यह सिमुलेशन अधिक सामान्य रूप से बताई गई सेटिंग के रूप में बैकस्पेस सक्षम रखता है, लेकिन अपने प्रवेश पत्र और परीक्षा-दिवस निर्देशों से पुष्टि करें।"] },
  { slug: "ssb-hcm", name: "SSB HCM", badge: "SSB", fullName: "Sashastra Seema Bal — Head Constable (Ministerial)", iconKind: "police",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 10, accuracy: 95, backspaceMode: "disabled", patternSourced: true,
    patternNotes: ["Same CAPF-wide standard as CRPF, BSF, and ITBP Head Constable (Ministerial).", "A 5% error margin is allowed before the 10-words-per-mistake penalty applies; backspace is disabled to match the conservative CAPF-wide baseline (some individual forces have allowed it in specific cycles — confirm against SSB's current notification)."],
    patternNotesHindi: ["सीआरपीएफ, बीएसएफ और आईटीबीपी हेड कांस्टेबल (मंत्रालयिक) जैसा ही सीएपीएफ-व्यापी मानक।", "10-शब्द-प्रति-गलती का दंड लागू होने से पहले 5% त्रुटि की छूट दी जाती है; सतर्क सीएपीएफ-व्यापी आधार रेखा से मेल खाने के लिए बैकस्पेस अक्षम रखा गया है (कुछ बलों ने विशिष्ट चक्रों में इसकी अनुमति दी है — एसएसबी की वर्तमान अधिसूचना से पुष्टि करें)।"] },
  { slug: "ncert-ldc", name: "NCERT LDC", badge: "NCERT", fullName: "National Council of Educational Research and Training — Lower Division Clerk", iconKind: "book",
    speedEnglish: 35, speedHindi: 30, durationMinutes: 10, accuracy: 95, backspaceMode: "full", highlightMode: "none", fullErrorPenalty: 10, halfErrorPenalty: 10, patternSourced: true,
    // Corrected from an earlier assumption: NCERT's typing test actually
    // runs on the TCS-iON platform (the software behind SSC/RRB-style
    // exams), not DDA's own portal, and TCS-iON runs with NO live
    // highlighting and NO auto-scroll at all -- confirmed independently
    // via research, not just the DDA-borrowed "Unrestricted Mode" (green/
    // red word highlighting) previously assumed here since NCERT's own
    // notification wasn't directly machine-readable.
    patternNotes: ["Selection is a Computer-Based Test (CBT) for the merit list, followed by a qualifying-only typing/computer skill test: it adds no marks of its own to the merit list, but failing it disqualifies you regardless of CBT rank. Confirmed directly against NCERT's own 2026 LDC recruitment cycle (result declared, typing test scheduled at NCERT New Delhi), not just the closest comparable exam family.", "35 WPM English or 30 WPM Hindi, corresponding to 10,500 / 9,000 key depressions per hour at 5 depressions per word (including spaces and punctuation), over a 10-minute test — the same widely standardised government pattern SSC and DDA's Junior Secretariat Assistant post use; NCERT's own notification confirms these exact numbers and duration, and only opts you into one language (English in Times New Roman, or Hindi in Unicode/Kruti Dev/Mangal) for the whole attempt.", "The real scoring formula -- confirmed against DDA's official JSA typing instructions, which NCERT's typing test follows the same standard as -- is Net Speed = (gross keystrokes ÷ 5 − incorrect words × 10) ÷ minutes: every incorrect word costs a flat 10-word penalty with no partial credit for a minor slip, unlike this platform's default full/half mistake split. fullErrorPenalty and halfErrorPenalty are both set to 10 here so every mistake category scores identically -- this is now the real formula, not an approximation.", "NCERT's typing test actually runs on the TCS-iON platform (the same software used for SSC/RRB-style exams), not DDA's own portal -- confirmed live word/error highlighting and auto-scrolling are both OFF: the passage shows as static plain text and you track your own position line by line while typing into the blank area below it, matching this platform's own layout. Backspace is fully enabled to fix a mistake at any point.", "English uses Times New Roman on a US QWERTY layout (12 pt, 1.5 line spacing on the real exam screen); Hindi uses Mangal on a Remington Gail layout — both already supported by this platform's existing Hindi input systems."],
    patternNotesHindi: ["चयन मेरिट सूची के लिए एक कंप्यूटर आधारित परीक्षा (सीबीटी) है, जिसके बाद केवल अर्हकारी (क्वालिफाइंग) टाइपिंग/कंप्यूटर कौशल परीक्षा होती है: यह मेरिट सूची में अपने कोई अंक नहीं जोड़ती, लेकिन इसमें असफल होने पर आपकी सीबीटी रैंक चाहे जो भी हो, आप अयोग्य हो जाते हैं। यह सीधे एनसीईआरटी की अपनी 2026 एलडीसी भर्ती प्रक्रिया (परिणाम घोषित, टाइपिंग टेस्ट एनसीईआरटी नई दिल्ली में निर्धारित) के विरुद्ध पुष्ट किया गया है, न कि केवल निकटतम तुलनीय परीक्षा परिवार से।", "अंग्रेज़ी में 35 डब्ल्यूपीएम या हिंदी में 30 डब्ल्यूपीएम, जो प्रति शब्द 5 की-डिप्रेशन (रिक्त स्थान और विराम चिह्नों सहित) की दर से 10,500 / 9,000 की-डिप्रेशन प्रति घंटा के बराबर है, 10 मिनट की परीक्षा में — यही व्यापक रूप से मानकीकृत सरकारी पैटर्न एसएससी और डीडीए के जूनियर सचिवालय सहायक पद में भी उपयोग होता है; एनसीईआरटी की अपनी अधिसूचना इन्हीं सटीक आंकड़ों और अवधि की पुष्टि करती है, और पूरी परीक्षा के लिए आपको केवल एक भाषा चुननी होती है (टाइम्स न्यू रोमन में अंग्रेज़ी, या यूनिकोड/कृति देव/मंगल में हिंदी)।", "वास्तविक स्कोरिंग सूत्र — डीडीए के आधिकारिक जेएसए टाइपिंग निर्देशों के विरुद्ध पुष्ट, जिनके समान मानक का पालन एनसीईआरटी की टाइपिंग परीक्षा भी करती है — है: नेट स्पीड = (सकल की-डिप्रेशन ÷ 5 − गलत शब्द × 10) ÷ मिनट: प्रत्येक गलत शब्द पर पूरे 10 शब्दों की कटौती होती है, चाहे गलती कितनी भी मामूली क्यों न हो — इस प्लेटफ़ॉर्म के डिफ़ॉल्ट पूर्ण/आधी गलती विभाजन के विपरीत। fullErrorPenalty और halfErrorPenalty दोनों को यहां 10 पर सेट किया गया है ताकि हर गलती श्रेणी समान रूप से स्कोर हो — यह अब वास्तविक सूत्र है, अनुमान नहीं।", "एनसीईआरटी की टाइपिंग परीक्षा वास्तव में टीसीएस-आयन (TCS-iON) प्लेटफ़ॉर्म पर आयोजित होती है (वही सॉफ़्टवेयर जो एसएससी/आरआरबी शैली की परीक्षाओं में उपयोग होता है), डीडीए के अपने पोर्टल पर नहीं — पुष्टि की गई है कि लाइव शब्द/त्रुटि हाइलाइटिंग और ऑटो-स्क्रॉलिंग दोनों बंद रहते हैं: गद्यांश स्थिर सादे पाठ के रूप में दिखता है और आपको टाइप करते समय नीचे की खाली जगह में अपनी स्थिति स्वयं पंक्ति-दर-पंक्ति ट्रैक करनी होती है, ठीक इस प्लेटफ़ॉर्म के अपने ले-आउट की तरह। किसी भी समय गलती ठीक करने के लिए बैकस्पेस पूरी तरह से सक्षम है।", "अंग्रेज़ी के लिए यूएस क्वर्टी (QWERTY) लेआउट पर टाइम्स न्यू रोमन फ़ॉन्ट (वास्तविक परीक्षा स्क्रीन पर 12 पॉइंट, 1.5 लाइन स्पेसिंग) उपयोग होता है; हिंदी के लिए रेमिंग्टन गेल लेआउट पर मंगल फ़ॉन्ट उपयोग होता है — दोनों इस प्लेटफ़ॉर्म की मौजूदा हिंदी इनपुट प्रणालियों में पहले से समर्थित हैं।"] },
  // The admin asked us to research which real Rajasthan/RSSB posts (beyond
  // the existing Rajasthan LDC category) involve typing, and add any
  // genuine gaps with real rules, not guesses. Clerk/Clerk Grade-II and
  // Personal Assistant Grade-II turned out to already be the SAME
  // recruitment as, respectively, "Rajasthan LDC" (RSSB's own posting is
  // titled "Clerk Grade-II / Junior Assistant") and the existing
  // stenography-module "RSMSSB Stenographer" category (RSMSSB's own
  // posting is titled "Stenographer & PA Grade-II") -- so no new category
  // was needed for either. Data Entry Operator and Tax Assistant are
  // genuinely separate posts with their own patterns; see each one's own
  // patternSourced flag and notes for exactly how confident that pattern is.
  { slug: "rajasthan-deo", name: "Rajasthan DEO", badge: "RSSB", fullName: "Rajasthan Staff Selection Board — Data Entry Operator", iconKind: "commission",
    // speedEnglish/speedHindi represent the pace needed for full marks
    // (25/25), matching the same convention as Rajasthan LDC: 1250 words /
    // 15 min = ~83 WPM in both languages (DEO's real passage is the same
    // length in both languages, unlike LDC's differing 500/400).
    speedEnglish: 83, speedHindi: 83, durationMinutes: 15, accuracy: 90, backspaceMode: "full", wordMethod: "spaces", highlightMode: "none", patternSourced: true,
    patternNotes: ["Corroborated across multiple independent sources (typing-practice platforms and 2025 admit-card notices citing RSSB's own recruitment cycle): a 1,250-word passage in each of English and Hindi, 15 minutes per language, marks-based (25 maximum per language, 10.5 to qualify) — genuinely different from Rajasthan LDC's shorter 500/400-word, 10-minute pattern, not the same exam.", "Marks are earned per correct word: 25 ÷ 1250 = 0.02 marks/word in both languages — you need 525 correct words (35 WPM) for the 10.5-mark minimum, matching the sourced \"minimum 35 WPM\" qualifying figure exactly.", "Backspace rules were not specified in any source found during this research pass — \"full\" backspace is used here as a reasonable default, not a confirmed figure; verify against the current notification.", "Word-separated counting and no on-screen highlight are assumed to match the same RSSB screen/software family as Rajasthan LDC, since both are administered by the same board — this is an extrapolation, not independently confirmed for DEO specifically."],
    patternNotesHindi: ["कई स्वतंत्र स्रोतों से पुष्ट (टाइपिंग-अभ्यास प्लेटफ़ॉर्म और आरएसएसबी की अपनी भर्ती प्रक्रिया का हवाला देने वाली 2025 की प्रवेश पत्र सूचनाएं): अंग्रेज़ी और हिंदी दोनों में 1,250-शब्दों का गद्यांश, प्रति भाषा 15 मिनट, अंकों पर आधारित (प्रति भाषा अधिकतम 25 अंक, अर्हकारी न्यूनतम 10.5) — यह राजस्थान एलडीसी के छोटे 500/400-शब्द, 10-मिनट के पैटर्न से वास्तव में अलग है, वही परीक्षा नहीं।", "अंक केवल सही शब्दों पर मिलते हैं: दोनों भाषाओं में 25 ÷ 1250 = 0.02 अंक/शब्द — 10.5-अंक की न्यूनतम सीमा के लिए आपको 525 सही शब्द (35 डब्ल्यूपीएम) चाहिए, जो स्रोत में बताए गए \"न्यूनतम 35 डब्ल्यूपीएम\" अर्हकारी आंकड़े से बिल्कुल मेल खाता है।", "इस शोध चरण के दौरान मिले किसी भी स्रोत में बैकस्पेस नियम निर्दिष्ट नहीं थे — यहां \"पूर्ण (full)\" बैकस्पेस एक उचित डिफ़ॉल्ट के रूप में उपयोग किया गया है, कोई पुष्ट आंकड़ा नहीं; वर्तमान अधिसूचना से पुष्टि करें।", "शब्द-पृथक गणना और कोई ऑन-स्क्रीन हाइलाइट न होना, राजस्थान एलडीसी जैसे ही आरएसएसबी स्क्रीन/सॉफ़्टवेयर परिवार से मेल खाने के अनुमान पर आधारित है, चूंकि दोनों का प्रशासन एक ही बोर्ड करता है — यह एक अनुमान है, डीईओ के लिए स्वतंत्र रूप से पुष्ट नहीं है।"] },
  { slug: "rajasthan-tax-assistant", name: "Rajasthan Tax Assistant", badge: "RSMSSB", fullName: "Rajasthan Subordinate & Ministerial Services Selection Board — Tax Assistant", iconKind: "commission",
    speedEnglish: 20, speedHindi: 20, durationMinutes: 15, accuracy: 90, backspaceMode: "full", patternSourced: false,
    patternNotes: ["Only one source was found for this post's typing requirements during this research pass, and it wasn't independently cross-verified — treat every number here as provisional and confirm against the current official notification before relying on it.", "That source states 20 WPM required in both English and Hindi, 15 minutes per language, as part of a larger \"Computer Proficiency Test\" (Paper 4) worth 100 marks total with 40 to qualify — but the marks figure appears to cover typing AND a separate MS-Excel component together, not typing alone, so it isn't modelled as a per-word marks scheme here the way Rajasthan LDC and Rajasthan DEO are.", "The Excel component is a distinct skill from typing and isn't simulated by this typing category — see the Excel Efficiency Test patterns (shown to admins while authoring a test) for the separate, also-unconfirmed RSMSSB Excel task list.", "Backspace rules were not stated in the source found; \"full\" is used as the platform default, not a confirmed figure."],
    patternNotesHindi: ["इस शोध चरण के दौरान इस पद की टाइपिंग आवश्यकताओं के लिए केवल एक ही स्रोत मिला, और उसकी स्वतंत्र रूप से क्रॉस-पुष्टि नहीं हुई — यहां दिए गए हर आंकड़े को अस्थायी मानें और इस पर भरोसा करने से पहले वर्तमान आधिकारिक अधिसूचना से पुष्टि करें।", "वह स्रोत बताता है कि अंग्रेज़ी और हिंदी दोनों में 20 डब्ल्यूपीएम चाहिए, प्रति भाषा 15 मिनट, एक बड़ी \"कंप्यूटर प्रवीणता परीक्षा\" (पेपर 4) के हिस्से के रूप में जो कुल 100 अंकों की है जिसमें से 40 अर्हकारी हैं — लेकिन यह अंक आंकड़ा टाइपिंग और एक अलग एमएस-एक्सेल घटक दोनों को मिलाकर लगता है, केवल टाइपिंग को नहीं, इसलिए इसे यहां राजस्थान एलडीसी और राजस्थान डीईओ की तरह प्रति-शब्द अंक योजना के रूप में नहीं दर्शाया गया है।", "एक्सेल घटक टाइपिंग से अलग कौशल है और इसे इस टाइपिंग श्रेणी द्वारा सिमुलेट नहीं किया जाता — इस अलग, समान रूप से अपुष्ट आरएसएमएसएसबी एक्सेल कार्य-सूची के लिए एक्सेल एफ़िशिएंसी टेस्ट पैटर्न (टेस्ट बनाते समय एडमिन को दिखाए जाने वाले) देखें।", "मिले हुए स्रोत में बैकस्पेस नियम नहीं बताए गए थे; \"पूर्ण (full)\" प्लेटफ़ॉर्म डिफ़ॉल्ट के रूप में उपयोग किया गया है, कोई पुष्ट आंकड़ा नहीं।"] },
  { slug: "rajasthan-hc-system-assistant", name: "RHC System Assistant", badge: "RHC", fullName: "Rajasthan High Court — System Assistant", iconKind: "scales",
    // 8000 KDPH is the real published qualifying threshold, corroborated
    // across two independent sources with matching numbers -- converted at
    // the standard 5 keystrokes/word: 8000 / 60 / 5 = 26.67 WPM, rounded up.
    speedEnglish: 27, speedHindi: 27, durationMinutes: 5, accuracy: 90, backspaceMode: "word", patternSourced: true,
    patternNotes: ["The real speed test runs Hindi (5 min, Kruti Dev 010) then English (5 min, Calibri) separately with a 2-minute gap between them — this simulator runs one continuous language selection for the same 5-minute duration, like every other category here.", "8,000 KDPH (key depressions per hour) is the qualifying threshold for both languages — about 26.67 WPM at the standard 5-keystrokes-per-word conversion; real candidates are advised to target well above this (10,000–12,000 KDPH) since it's a disqualification floor, not a competitive target.", "Backspace only corrects the word currently being typed — once you press Space or Enter, that word is locked, matching the same rule already modelled for Rajasthan LDC/DEO.", "The real exam also disables arrow-key navigation, Delete, cut/copy/paste, right-click, and spellcheck during the speed test — this simulator doesn't specifically restrict those, so treat this as speed/backspace practice rather than an exact interface reproduction.", "Beyond the speed test, the real exam also has separate 10-minute MS Word and 10-minute MS Excel efficiency papers (50 marks total) — see the Excel Efficiency Test patterns (shown to admins while authoring a test) for that separate, also-sourced task list; this typing category only covers the speed-test half."],
    patternNotesHindi: ["वास्तविक स्पीड टेस्ट में पहले हिंदी (5 मिनट, कृति देव 010) फिर अंग्रेज़ी (5 मिनट, कैलिब्री) अलग-अलग चलती है, दोनों के बीच 2 मिनट का अंतराल होता है — यह सिमुलेटर इस सूची की हर अन्य श्रेणी की तरह उसी 5-मिनट की अवधि के लिए एक निरंतर भाषा चयन चलाता है।", "8,000 केडीपीएच (की-डिप्रेशन प्रति घंटा) दोनों भाषाओं के लिए अर्हकारी सीमा है — मानक 5-की-स्ट्रोक्स-प्रति-शब्द रूपांतरण पर लगभग 26.67 डब्ल्यूपीएम; वास्तविक उम्मीदवारों को इससे काफी ऊपर (10,000–12,000 केडीपीएच) लक्ष्य रखने की सलाह दी जाती है, क्योंकि यह एक अयोग्यता की न्यूनतम सीमा है, कोई प्रतिस्पर्धी लक्ष्य नहीं।", "बैकस्पेस केवल वर्तमान में टाइप हो रहे शब्द को ही सुधारता है — स्पेस या एंटर दबाते ही वह शब्द लॉक हो जाता है, जो राजस्थान एलडीसी/डीईओ के लिए पहले से मॉडल किए गए इसी नियम से मेल खाता है।", "वास्तविक परीक्षा स्पीड टेस्ट के दौरान एरो-की नेविगेशन, डिलीट, कट/कॉपी/पेस्ट, राइट-क्लिक और स्पेलचेक को भी अक्षम कर देती है — यह सिमुलेटर विशेष रूप से इन्हें प्रतिबंधित नहीं करता, इसलिए इसे एक सटीक इंटरफ़ेस प्रतिकृति के बजाय गति/बैकस्पेस अभ्यास मानें।", "स्पीड टेस्ट के अलावा, वास्तविक परीक्षा में अलग से 10-मिनट का एमएस वर्ड और 10-मिनट का एमएस एक्सेल एफ़िशिएंसी पेपर भी होता है (कुल 50 अंक) — उस अलग, समान रूप से स्रोतित कार्य-सूची के लिए एक्सेल एफ़िशिएंसी टेस्ट पैटर्न (टेस्ट बनाते समय एडमिन को दिखाए जाने वाले) देखें; यह टाइपिंग श्रेणी केवल स्पीड-टेस्ट वाले आधे हिस्से को कवर करती है।"] },
  { slug: "rssb-informatics-assistant", name: "RSSB Informatics Assistant", badge: "RSSB", fullName: "Rajasthan Staff Selection Board — Informatics Assistant", iconKind: "commission",
    speedEnglish: 20, speedHindi: 20, durationMinutes: 15, accuracy: 90, backspaceMode: "full", patternSourced: true,
    patternNotes: ["Corroborated across two independent sources with matching numbers: 15 minutes per language, 20 WPM required in both English and Hindi, and the test is qualifying only — no marks are awarded for typing speed itself, but failing disqualifies you regardless of your written-exam rank.", "English uses Courier New on a standard QWERTY layout; Hindi uses DevLys 010 on a Remington (typewriter) layout.", "Neither source found during this research pass stated an accuracy percentage or a backspace rule — the 90% accuracy and full backspace used here are the platform's own defaults, not confirmed figures. Verify against the current official notification."],
    patternNotesHindi: ["मेल खाते आंकड़ों वाले दो स्वतंत्र स्रोतों से पुष्ट: प्रति भाषा 15 मिनट, अंग्रेज़ी और हिंदी दोनों में 20 डब्ल्यूपीएम चाहिए, और यह परीक्षा केवल अर्हकारी है — टाइपिंग गति के लिए स्वयं कोई अंक नहीं दिए जाते, लेकिन असफल होने पर आपकी लिखित-परीक्षा रैंक चाहे जो भी हो, आप अयोग्य हो जाते हैं।", "अंग्रेज़ी के लिए मानक क्वर्टी (QWERTY) लेआउट पर कूरियर न्यू फ़ॉन्ट उपयोग होता है; हिंदी के लिए रेमिंग्टन (टाइपराइटर) लेआउट पर डेवलिस 010 उपयोग होता है।", "इस शोध चरण के दौरान मिले किसी भी स्रोत में सटीकता प्रतिशत या बैकस्पेस नियम नहीं बताया गया — यहां उपयोग की गई 90% सटीकता और पूर्ण बैकस्पेस प्लेटफ़ॉर्म के अपने डिफ़ॉल्ट हैं, कोई पुष्ट आंकड़े नहीं। वर्तमान आधिकारिक अधिसूचना से पुष्टि करें।"] },
];

export const EXAM_CATEGORIES: ExamCategoryDefinition[] = RAW_CATEGORIES.map((category, index) => ({
  ...category,
  tone: TONE_PALETTE[index % TONE_PALETTE.length][0],
  toneDark: TONE_PALETTE[index % TONE_PALETTE.length][1],
}));

export function getExamCategory(slug: string) {
  return EXAM_CATEGORIES.find((category) => category.slug === slug);
}

export function examCategoryPresetId(slug: string, language: "English" | "Hindi") {
  return `exam-cat-${slug}-${language.toLowerCase()}`;
}

export function defaultExamCategoryRules(category: ExamCategoryDefinition, language: "English" | "Hindi"): string[] {
  const speed = language === "English" ? category.speedEnglish : category.speedHindi;
  // Real reported bug: the Hindi half of the category rules page (and this
  // category's Hindi preset's own instructionNotes) rendered these same
  // fixed sentences in English -- only the heading above them ("हिंदी नियम
  // एवं शर्तें") was actually Hindi. These five sentences are now genuinely
  // translated; category.patternNotesHindi (falling back to the English
  // patternNotes when a category hasn't been translated yet) covers the
  // per-category detail notes.
  if (language === "Hindi") {
    return [
      `यह Samradhi Classes द्वारा बनाई गई ${category.fullName} टाइपिंग परीक्षा के लिए एक स्वतंत्र अभ्यास सिमुलेशन है। यह संबंधित भर्ती या परीक्षा प्राधिकरण से संबद्ध, अनुमोदित या उसका आधिकारिक उत्पाद नहीं है।`,
      `लक्ष्य पैटर्न: हिंदी में ${speed} शब्द प्रति मिनट (WPM), ${category.durationMinutes} मिनट, न्यूनतम ${category.accuracy}% सटीकता, बैकस्पेस ${category.backspaceMode === "disabled" ? "की अनुमति नहीं" : "की अनुमति"}।`,
      category.patternSourced
        ? "ये आंकड़े इस पद पर प्रकाशित परीक्षा-पैटर्न शोध पर आधारित हैं। सरकारी परीक्षा पैटर्न भर्ती चक्रों के बीच बदल सकते हैं — अपनी वास्तविक परीक्षा से पहले हमेशा मौजूदा आधिकारिक अधिसूचना से जांच करें।"
        : "इस सटीक पद के लिए कोई पुष्ट आधिकारिक पैटर्न नहीं मिला; ऊपर दिए गए आंकड़े निकटतम तुलनीय परीक्षा परिवार पर आधारित एक अनुमानित आधार रेखा हैं, न कि सत्यापित आधिकारिक पैटर्न। यदि आपके पास आधिकारिक अधिसूचना है तो कृपया हमें वास्तविक पैटर्न बताएं, और हम इसे अपडेट कर देंगे।",
      ...(category.patternNotesHindi ?? category.patternNotes),
      "टाइमर आपकी पहली कीस्ट्रोक से शुरू होता है, पेज लोड होने पर नहीं।",
      "ध्यान भटकाए बिना, परीक्षा जैसा माहौल पाने के लिए टूलबार से फ़ुल-स्क्रीन मोड उपलब्ध है, साथ ही फ़ुल स्क्रीन से बाहर निकलने के लिए एक समर्पित बटन भी है।",
    ];
  }
  return [
    `This is an independent practice simulation for the ${category.fullName} typing test, created by Samradhi Classes. It is not affiliated with, endorsed by, or an official product of the concerned recruitment or examination authority.`,
    `Target pattern: ${speed} WPM in ${language}, ${category.durationMinutes} minutes, ${category.accuracy}% minimum accuracy, backspace ${category.backspaceMode === "disabled" ? "not allowed" : "allowed"}.`,
    category.patternSourced
      ? "These figures are based on published exam-pattern research for this post. Government exam patterns change between recruitment cycles — always cross-check against the current official notification before your real exam."
      : "No confirmed official pattern was found for this exact post; the figures above are a reasoned baseline from the closest comparable exam family, not a verified official pattern. Please tell us the real pattern if you have the official notification, and we will update it.",
    ...category.patternNotes,
    "The timer starts on your first keystroke, not when the page loads.",
    "Full-screen mode is available from the toolbar for a distraction-free, exam-like environment, with a dedicated button to exit full screen.",
  ];
}
