import{unzipSync}from"fflate";
import{XMLParser}from"fast-xml-parser";
import{looksLikeKrutiDevText}from"./word-pdf-extraction.ts";

export type MatterRun={text:string;bold:boolean;italic:boolean;underline:boolean;strike:boolean;fontFamily:string|null;fontSize:number|null;color:string|null;highlight:string|null};
export type MatterParagraph={id:string;type:"paragraph"|"list-item";paragraphNumber:number|null;listGroup:string|null;runs:MatterRun[];alignment:"left"|"center"|"right"|"justify";leftIndent:number;rightIndent:number;lineSpacing:number;spaceBefore:number;spaceAfter:number};
export type WorkingMatterSnapshot={schemaVersion:1|"1";language:"English"|"Hindi";source?:{fileName:string;sizeBytes:number};paragraphs:MatterParagraph[];formattingSummary:{paragraphs:number;runs:number;italicParagraphs:number;justifiedParagraphs:number;listItems:number;fonts:string[]};warnings:string[]};
const MAX_DOCX_BYTES=10*1024*1024,MAX_UNCOMPRESSED_BYTES=40*1024*1024;
const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:"@",textNodeName:"#text",isArray:(name)=>name==="w:p"||name==="w:r"||name==="w:t"});
const own=(value:unknown,key:string)=>Boolean(value&&typeof value==="object"&&Object.prototype.hasOwnProperty.call(value,key));
const attr=(value:unknown,key:string)=>value&&typeof value==="object"?String((value as Record<string,unknown>)[`@w:${key}`]??""):"";
const points=(value:string,divisor:number)=>Number.isFinite(Number(value))?Number(value)/divisor:0;
const cleanText=(value:string)=>value.normalize("NFC").replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/gu,"").slice(0,200000);

export function validateWorkingMatterFile(file:{name:string;type:string;size:number}){const errors:string[]=[];const lower=file.name.toLowerCase();if(!lower.endsWith(".docx")||lower.endsWith(".doc")||lower.endsWith(".docm"))errors.push("Upload a Microsoft Word .docx file only.");if(file.type&&file.type!=="application/vnd.openxmlformats-officedocument.wordprocessingml.document")errors.push("The file MIME type is not a valid DOCX document.");if(file.size<=0||file.size>MAX_DOCX_BYTES)errors.push("Working Matter DOCX must be between 1 byte and 10 MB.");return errors}

export function parseWorkingMatterDocx(bytes:Uint8Array):WorkingMatterSnapshot{
 if(bytes.byteLength>MAX_DOCX_BYTES)throw new Error("Working Matter DOCX exceeds 10 MB.");let expanded=0;const files=unzipSync(bytes,{filter:file=>{if(file.name.includes("..")||file.name.startsWith("/")||file.name.includes("\\"))throw new Error("DOCX contains an unsafe package path.");expanded+=file.originalSize;if(expanded>MAX_UNCOMPRESSED_BYTES)throw new Error("DOCX expands beyond the safe 40 MB limit.");return true}});const names=Object.keys(files);if(!files["[Content_Types].xml"]||!files["word/document.xml"])throw new Error("Malformed DOCX: required Word document parts are missing.");if(names.some(name=>/(?:vbaProject\.bin|activeX|embeddings|oleObject|\.exe$|\.dll$|\.js$)/iu.test(name)))throw new Error("DOCX contains executable or embedded content that is not allowed.");const decoder=new TextDecoder();for(const name of names.filter(name=>name.endsWith(".rels"))){const rels=decoder.decode(files[name]);if(/TargetMode\s*=\s*["']External["']/iu.test(rels))throw new Error("DOCX contains unsafe external relationships.")}
 const xml=decoder.decode(files["word/document.xml"]);const doc=parser.parse(xml);const body=doc?.["w:document"]?.["w:body"];if(!body)throw new Error("Malformed DOCX document body.");const rawParagraphs=(Array.isArray(body["w:p"])?body["w:p"]:[]).map(parseParagraph).filter((paragraph:MatterParagraph)=>paragraph.runs.some(run=>run.text.trim()));if(!rawParagraphs.length)throw new Error("DOCX contains no supported editable paragraphs.");const warnings:string[]=[];if(/<w:(?:tbl|drawing|pict|object|altChunk)\b/iu.test(xml))warnings.push("Unsupported tables, drawings, or embedded elements were omitted; supported paragraph text was preserved.");const paragraphs=groupShortList(rawParagraphs);let number=0;for(const paragraph of paragraphs)paragraph.paragraphNumber=paragraph.type==="paragraph"?++number:null;const text=paragraphs.flatMap(p=>p.runs.map(r=>r.text)).join(" ");if(looksLikeKrutiDevText(text))throw new Error("Legacy Kruti Dev text detected. Select an explicit Kruti Dev-to-Unicode conversion workflow before importing.");const language:"English"|"Hindi"=/[\u0900-\u097f]/u.test(text)?"Hindi":"English";const fonts=[...new Set(paragraphs.flatMap(p=>p.runs.map(r=>r.fontFamily).filter((font):font is string=>Boolean(font))))];return{schemaVersion:1,language,paragraphs,formattingSummary:{paragraphs:number,runs:paragraphs.reduce((sum,p)=>sum+p.runs.length,0),italicParagraphs:paragraphs.filter(p=>p.runs.some(r=>r.italic)).length,justifiedParagraphs:paragraphs.filter(p=>p.alignment==="justify").length,listItems:paragraphs.filter(p=>p.type==="list-item").length,fonts},warnings}
}

function parseParagraph(value:Record<string,unknown>,index:number):MatterParagraph{const pPr=(value["w:pPr"]??{})as Record<string,unknown>;const paragraphRun=(pPr["w:rPr"]??{})as Record<string,unknown>;const rawRuns=Array.isArray(value["w:r"])?value["w:r"] as Record<string,unknown>[]:[];const runs=rawRuns.map(run=>parseRun(run,paragraphRun)).filter(run=>run.text);const alignmentValue=attr(pPr["w:jc"],"val");const alignment:MatterParagraph["alignment"]=alignmentValue==="both"?"justify":alignmentValue==="center"?"center":alignmentValue==="right"?"right":"left";const ind=pPr["w:ind"],spacing=pPr["w:spacing"];return{id:`matter-p-${index+1}`,type:"paragraph",paragraphNumber:null,listGroup:null,runs,alignment,leftIndent:points(attr(ind,"left")||attr(ind,"start"),1440),rightIndent:points(attr(ind,"right")||attr(ind,"end"),1440),lineSpacing:points(attr(spacing,"line"),240)||1,spaceBefore:points(attr(spacing,"before"),20),spaceAfter:points(attr(spacing,"after"),20)}}
function parseRun(value:Record<string,unknown>,paragraphRun:Record<string,unknown>):MatterRun{const rPr=(value["w:rPr"]??{})as Record<string,unknown>;const texts=Array.isArray(value["w:t"])?value["w:t"]:[];const text=cleanText(texts.map(item=>typeof item==="string"?item:typeof item==="object"&&item?String((item as Record<string,unknown>)["#text"]??""):"").join(""));const prop=(key:string)=>own(rPr,key)||own(paragraphRun,key);const fonts=rPr["w:rFonts"]??paragraphRun["w:rFonts"],size=attr(rPr["w:sz"]??paragraphRun["w:sz"],"val");return{text,bold:prop("w:b"),italic:prop("w:i"),underline:prop("w:u"),strike:prop("w:strike")||prop("w:dstrike"),fontFamily:attr(fonts,"ascii")||attr(fonts,"hAnsi")||null,fontSize:size?points(size,2):null,color:attr(rPr["w:color"]??paragraphRun["w:color"],"val")||null,highlight:attr(rPr["w:highlight"]??paragraphRun["w:highlight"],"val")||null}}
function groupShortList(items:MatterParagraph[]){const result=items.map(item=>({...item,runs:item.runs.map(run=>({...run}))}));for(let start=0;start<result.length;){if(textOf(result[start]).length>40){start++;continue}let end=start;while(end<result.length&&textOf(result[end]).length>0&&textOf(result[end]).length<=40)end++;if(end-start>=2)for(let index=start;index<end;index++){result[index].type="list-item";result[index].listGroup=`matter-list-${start+1}`}start=Math.max(end,start+1)}return result}
function textOf(paragraph:MatterParagraph){return paragraph.runs.map(run=>run.text).join("").trim()}
export function cloneMatterSnapshot(snapshot:WorkingMatterSnapshot):WorkingMatterSnapshot{return structuredClone(snapshot)}
