"use client";
const SAFE_IMAGE_TYPES=new Set(["image/png","image/jpeg","image/webp","image/gif"]),MAX_IMAGE_BYTES=512*1024;
export function sortSelectedBlocks(editor:HTMLDivElement,selected:HTMLElement[],direction:"asc"|"desc"="asc"){
  const all=[...editor.children]as HTMLElement[];
  const targets=selected.length>1?selected:all;
  const targetSet=new Set(targets);
  const sorted=[...targets].sort((a,b)=>(a.textContent??"").localeCompare(b.textContent??"",undefined,{numeric:true,sensitivity:"base"}));
  const ordered=direction==="desc"?sorted.reverse():sorted;
  let cursor=0;
  const final=all.map(block=>targetSet.has(block)?ordered[cursor++]:block);
  editor.replaceChildren(...final);
}
export async function insertOnlinePicture(editor:HTMLDivElement,changed:()=>void,message:(value:string)=>void){const input=window.prompt("Online picture URL (http or https):","https://")?.trim();if(!input)return;let url:URL;try{url=new URL(input)}catch{message("Enter a valid online picture URL.");return}if(!["https:","http:"].includes(url.protocol)||input.startsWith("//")||url.username||url.password){message("Only direct http or https image URLs are allowed.");return}try{const response=await fetch(url.toString(),{credentials:"omit",referrerPolicy:"no-referrer",redirect:"error"});const type=(response.headers.get("content-type")??"").split(";",1)[0].toLowerCase();if(!response.ok||!SAFE_IMAGE_TYPES.has(type))throw new Error("The URL did not return a supported image.");const declared=Number(response.headers.get("content-length")??0);if(declared>MAX_IMAGE_BYTES)throw new Error("The online picture exceeds 512 KB.");const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.byteLength<8||bytes.byteLength>MAX_IMAGE_BYTES||!matchesSignature(bytes,type))throw new Error("The image content did not match its declared safe format.");const source=`data:${type};base64,${toBase64(bytes)}`;const dimensions=await imageDimensions(source);if(dimensions.width>6000||dimensions.height>6000)throw new Error("The online picture dimensions exceed 6000 × 6000.");const figure=document.createElement("figure");figure.dataset.blockType="image";const image=document.createElement("img");image.src=source;image.alt="Online picture";image.width=dimensions.width;image.height=dimensions.height;image.style.maxWidth="320px";image.style.maxHeight="320px";image.style.width="auto";image.style.height="auto";figure.append(image);const selection=getSelection();if(selection?.rangeCount){const range=selection.getRangeAt(0);range.deleteContents();range.insertNode(figure)}else editor.append(figure);changed();message("Online picture inserted safely.")}catch(error){message(error instanceof Error?error.message:"Online picture could not be inserted.")}}
function matchesSignature(bytes:Uint8Array,type:string){if(type==="image/png")return bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47;if(type==="image/jpeg")return bytes[0]===0xff&&bytes[1]===0xd8&&bytes.at(-2)===0xff&&bytes.at(-1)===0xd9;if(type==="image/gif")return new TextDecoder("ascii").decode(bytes.slice(0,6))in{"GIF87a":1,"GIF89a":1};if(type==="image/webp")return new TextDecoder("ascii").decode(bytes.slice(0,4))==="RIFF"&&new TextDecoder("ascii").decode(bytes.slice(8,12))==="WEBP";return false}
function toBase64(bytes:Uint8Array){let binary="";for(let index=0;index<bytes.length;index+=0x8000)binary+=String.fromCharCode(...bytes.subarray(index,index+0x8000));return btoa(binary)}
function imageDimensions(source:string){return new Promise<{width:number;height:number}>((resolve,reject)=>{const image=new Image();image.onload=()=>image.naturalWidth&&image.naturalHeight?resolve({width:image.naturalWidth,height:image.naturalHeight}):reject(new Error("The image dimensions are invalid."));image.onerror=()=>reject(new Error("The online picture could not be decoded."));image.src=source})}
