export const WORD_EDITOR_TABS = ["File", "Home", "Insert", "Design", "Page Layout", "View"] as const;
export type WordEditorTab = (typeof WORD_EDITOR_TABS)[number];
export const APPROVED_WORD_FONTS = [
  "Calibri Light (Headings)", "Calibri (Body)", "Calibri", "Calibri Light", "Calibri Semibold",
  "Arial", "Arial Black", "Arial Narrow", "Arial Rounded MT Bold", "Arial Unicode MS",
  "Bahnschrift", "Bahnschrift Condensed", "Bahnschrift Light", "Bahnschrift Light Condensed",
  "Bahnschrift Light SemiCondensed", "Bahnschrift SemiBold", "Bahnschrift SemiBold Condensed",
  "Bahnschrift SemiBold SemiCondensed", "Bahnschrift SemiCondensed", "Bahnschrift SemiLight",
  "Bahnschrift SemiLight Condensed", "Bahnschrift SemiLight SemiCondensed",
  "Bookman Old Style", "Cambria", "Cambria Math", "Candara", "Century", "Century Gothic",
  "Comic Sans MS", "Consolas", "Constantia", "Corbel", "Courier New", "Franklin Gothic Medium",
  "Garamond", "Georgia", "Gill Sans MT", "Lucida Console", "Lucida Sans Unicode", "Microsoft Sans Serif",
  "Palatino Linotype", "Segoe UI", "Tahoma", "Times New Roman", "Trebuchet MS", "Verdana",
  "Aparajita", "Kokila", "Kruti Dev 010", "Mangal", "Nirmala UI", "Sanskrit Text", "Utsaah",
  "Noto Sans Devanagari", "Noto Serif Devanagari",
] as const;
export const WORD_THEME_FONTS = ["Calibri Light (Headings)", "Calibri (Body)"] as const;
export type RibbonOption = { id:string;label:string;icon:string;kind?:"button"|"font"|"size"|"color";menu?:boolean;unsupported?:string };
export type RibbonGroup = { id:string;label:string;options:readonly RibbonOption[] };
export type RibbonTabDefinition = { id:WordEditorTab;groups:readonly RibbonGroup[] };
const option=(id:string,label:string,icon:string,kind:RibbonOption["kind"]="button",menu=false):RibbonOption=>({id,label,icon,kind,menu});

export const WORD_EDITOR_RIBBON:readonly RibbonTabDefinition[]=[
 {id:"File",groups:[]},
 {id:"Home",groups:[
  {id:"clipboard",label:"Clipboard",options:[option("undo","Undo","↶"),option("redo","Redo","↷"),option("paste","Paste","▣","button",true),option("cut","Cut","✂"),option("copy","Copy","▤"),option("formatPainter","Format Painter","◩")]},
  {id:"font",label:"Font",options:[option("fontName","Font family","Aa","font",true),option("fontSize","Font size","11","size",true),option("increaseFontSize","Increase font size","A↑"),option("decreaseFontSize","Decrease font size","A↓"),option("changeCase","Change case","Aa","button",true),option("bold","Bold","B"),option("italic","Italic","I"),option("underline","Underline","U","button",true),option("strikeThrough","Strikethrough","S̶"),option("subscript","Subscript","x₂"),option("superscript","Superscript","x²"),option("textEffects","Text effects","A✦","button",true),option("highlightColor","Text highlight color","▰","color",true),option("fontColor","Font color","A̲","color",true),option("fontDialog","Font Settings…","⋱","button",true)]},
  {id:"paragraph",label:"Paragraph",options:[option("bullets","Bullets","•≡","button",true),option("numbering","Numbering","1≡","button",true),option("multilevelList","Multilevel list","1↳","button",true),option("decreaseIndent","Decrease indent","⇤"),option("increaseIndent","Increase indent","⇥"),option("sort","Sort","A↧"),option("formattingMarks","Show/hide formatting marks","¶"),option("alignLeft","Align left","≡←"),option("alignCenter","Center","≡"),option("alignRight","Align right","→≡"),option("justify","Justify","▤"),option("lineSpacing","Line spacing","↕≡","button",true),option("shading","Shading","▧","color",true),option("borders","Borders","□","button",true),option("paragraphDialog","Paragraph Settings…","⧉","button",true)]},
  {id:"editing",label:"Editing",options:[option("find","Find","⌕","button",true),option("replace","Replace","ab↔"),option("selectAll","Select","▣","button",true)]}
 ]},
 {id:"Insert",groups:[
  {id:"pages",label:"Pages",options:[option("coverPage","Cover Page","▤","button",true),option("blankPage","Blank Page","□"),option("pageBreak","Page Break","⋯")]},
  {id:"tables",label:"Tables",options:[option("insertTable","Table","▦","button",true)]},
  {id:"illustrations",label:"Illustrations",options:[option("insertPicture","Pictures","▧","button",true),option("onlinePictures","Online Pictures","◎▧"),option("shapes","Shapes","○□","button",true)]},
  {id:"links",label:"Links",options:[option("hyperlink","Hyperlink","↗"),option("bookmark","Bookmark","🔖"),option("crossReference","Cross-reference","↪")]},
  {id:"headerFooter",label:"Header & Footer",options:[option("header","Header","▔","button",true),option("footer","Footer","▁","button",true),option("pageNumber","Page Number","#","button",true)]},
  {id:"text",label:"Text",options:[option("dropCap","Drop Cap","Aᵇ","button",true),option("dateTime","Date & Time","◷")]},
  {id:"symbols",label:"Symbols",options:[option("symbol","Symbol","Ω","button",true)]}
 ]},
 {id:"Design",groups:[{id:"pageBackground",label:"Page Background",options:[option("watermark","Watermark","W","button",true),option("pageColor","Page Color","◫","color",true),option("pageBorders","Page Borders","▣","button",true)]}]},
 {id:"Page Layout",groups:[{id:"pageSetup",label:"Page Setup",options:[option("margins","Margins","▯","button",true),option("orientation","Orientation","▭","button",true),option("pageSize","Size","A4","button",true),option("columns","Columns","▥","button",true),option("sectionBreak","Breaks","§⋯","button",true),option("lineNumbers","Line Numbers","#≡","button",true)]}]},
 {id:"View",groups:[
  {id:"views",label:"Document Views",options:[option("printLayout","Print Layout","▥"),option("fullScreenReading","Full Screen Reading","▤"),option("webLayout","Web Layout","🌐"),option("outlineView","Outline","☷"),option("draftView","Draft","≋")]},
  {id:"show",label:"Show/Hide",options:[option("ruler","Ruler","⌇"),option("gridlines","Gridlines","▦"),option("documentMap","Document Map","☰")]},
  {id:"zoom",label:"Zoom",options:[option("zoom100","100%","100"),option("onePage","One Page","▯"),option("twoPages","Two Pages","▯▯")]}
 ]}
]as const;

export type HierarchicalEditorCapabilities={schemaVersion:"2";tabs:Record<string,{enabled:boolean;groups:Record<string,{enabled:boolean;options:Record<string,boolean>}>}>;fonts:string[];fontSizeMin:number;fontSizeMax:number};
export const SUPPORTED_WORD_COMMANDS=new Set(WORD_EDITOR_RIBBON.flatMap(tab=>tab.groups.flatMap(group=>group.options.map(item=>item.id))));
export function recommendedWordEditorCapabilities():HierarchicalEditorCapabilities{return{schemaVersion:"2",tabs:Object.fromEntries(WORD_EDITOR_RIBBON.map(tab=>[tab.id,{enabled:true,groups:Object.fromEntries(tab.groups.map(group=>[group.id,{enabled:true,options:Object.fromEntries(group.options.map(item=>[item.id,true]))}]))}])),fonts:[...APPROVED_WORD_FONTS],fontSizeMin:8,fontSizeMax:72}}
export function normalizeWordEditorCapabilities(value:unknown):HierarchicalEditorCapabilities{const defaults=recommendedWordEditorCapabilities();if(!value||typeof value!=="object")return defaults;const raw=value as Record<string,unknown>;if(raw.schemaVersion!=="2"){const oldTabs=new Set(Array.isArray(raw.tabs)?raw.tabs.filter((item):item is string=>typeof item==="string"):[]),commands=new Set(Array.isArray(raw.commands)?raw.commands.filter((item):item is string=>typeof item==="string"):[]);for(const tab of WORD_EDITOR_RIBBON){defaults.tabs[tab.id].enabled=tab.id==="File"||tab.id==="Design"?false:oldTabs.has(tab.id);for(const group of tab.groups)for(const item of group.options)defaults.tabs[tab.id].groups[group.id].options[item.id]=commands.has(legacyCommand(item.id))}defaults.fonts=approvedFonts(raw.fonts);defaults.fontSizeMin=boundedSize(raw.fontSizeMin,8);defaults.fontSizeMax=Math.max(defaults.fontSizeMin,boundedSize(raw.fontSizeMax,72));return defaults}const configuredTabs=raw.tabs&&typeof raw.tabs==="object"?raw.tabs as Record<string,unknown>:{};for(const tab of WORD_EDITOR_RIBBON){const configured=configuredTabs[tab.id]as Record<string,unknown>|undefined;defaults.tabs[tab.id].enabled=configured?.enabled!==false;const groups=configured?.groups&&typeof configured.groups==="object"?configured.groups as Record<string,unknown>:{};for(const group of tab.groups){const configuredGroup=groups[group.id]as Record<string,unknown>|undefined;defaults.tabs[tab.id].groups[group.id].enabled=configuredGroup?.enabled!==false;const options=configuredGroup?.options&&typeof configuredGroup.options==="object"?configuredGroup.options as Record<string,unknown>:{};for(const item of group.options)defaults.tabs[tab.id].groups[group.id].options[item.id]=options[item.id]!==false}}defaults.fonts=approvedFonts(raw.fonts);defaults.fontSizeMin=boundedSize(raw.fontSizeMin,8);defaults.fontSizeMax=Math.max(defaults.fontSizeMin,boundedSize(raw.fontSizeMax,72));return defaults}
export function validateWordEditorCapabilities(value:unknown):HierarchicalEditorCapabilities{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Editor capabilities must be an object.");const raw=value as Record<string,unknown>;if(raw.schemaVersion!=="2"||Object.keys(raw).some(key=>!["schemaVersion","tabs","fonts","fontSizeMin","fontSizeMax","pause"].includes(key))||!raw.tabs||typeof raw.tabs!=="object"||Array.isArray(raw.tabs))throw new Error("Editor capability schema is invalid.");if("pause"in raw&&raw.pause!==false)throw new Error("Pause is not supported.");const tabs=raw.tabs as Record<string,unknown>;if(Object.keys(tabs).length!==WORD_EDITOR_RIBBON.length||Object.keys(tabs).some(key=>!WORD_EDITOR_TABS.includes(key as WordEditorTab)))throw new Error("Unknown editor tab.");for(const tab of WORD_EDITOR_RIBBON){const candidate=tabs[tab.id];if(!candidate||typeof candidate!=="object"||Array.isArray(candidate))throw new Error("Malformed editor tab.");const tabObject=candidate as Record<string,unknown>;if(Object.keys(tabObject).some(key=>!["enabled","groups"].includes(key))||typeof tabObject.enabled!=="boolean"||!tabObject.groups||typeof tabObject.groups!=="object"||Array.isArray(tabObject.groups))throw new Error("Malformed editor tab.");const groups=tabObject.groups as Record<string,unknown>;if(Object.keys(groups).length!==tab.groups.length||Object.keys(groups).some(key=>!tab.groups.some(group=>group.id===key)))throw new Error("Unknown editor group.");for(const group of tab.groups){const candidateGroup=groups[group.id];if(!candidateGroup||typeof candidateGroup!=="object"||Array.isArray(candidateGroup))throw new Error("Malformed editor group.");const groupObject=candidateGroup as Record<string,unknown>;if(Object.keys(groupObject).some(key=>!["enabled","options"].includes(key))||typeof groupObject.enabled!=="boolean"||!groupObject.options||typeof groupObject.options!=="object"||Array.isArray(groupObject.options))throw new Error("Malformed editor group.");const options=groupObject.options as Record<string,unknown>;if(Object.keys(options).length!==group.options.length||Object.keys(options).some(key=>!group.options.some(item=>item.id===key)))throw new Error("Unknown editor option.");for(const item of group.options)if(typeof options[item.id]!=="boolean")throw new Error(`Invalid editor option ${item.id}.`)}}if(!Array.isArray(raw.fonts)||raw.fonts.length<1||raw.fonts.length>APPROVED_WORD_FONTS.length||new Set(raw.fonts).size!==raw.fonts.length||raw.fonts.some(font=>typeof font!=="string"||!(APPROVED_WORD_FONTS as readonly string[]).includes(font)))throw new Error("Unknown editor font.");if(!Number.isInteger(raw.fontSizeMin)||!Number.isInteger(raw.fontSizeMax)||Number(raw.fontSizeMin)<8||Number(raw.fontSizeMax)>72||Number(raw.fontSizeMin)>Number(raw.fontSizeMax))throw new Error("Editor font-size range is invalid.");return normalizeWordEditorCapabilities(value)}
export function isWordCommandEnabled(capabilities:HierarchicalEditorCapabilities,command:string){for(const tab of WORD_EDITOR_RIBBON)for(const group of tab.groups)for(const item of group.options)if(item.id===command)return capabilities.tabs[tab.id].enabled&&capabilities.tabs[tab.id].groups[group.id].enabled&&capabilities.tabs[tab.id].groups[group.id].options[item.id]===true;return false}
function approvedFonts(value:unknown){const values=Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"&&(APPROVED_WORD_FONTS as readonly string[]).includes(item)):[];return values.length?[...new Set(values)]:["Calibri","Arial","Times New Roman","Mangal"]}function boundedSize(value:unknown,fallback:number){const number=Number(value);return Number.isFinite(number)?Math.max(8,Math.min(72,Math.round(number))):fallback}function legacyCommand(command:string){return({bullets:"insertUnorderedList",numbering:"insertOrderedList",decreaseIndent:"outdent",increaseIndent:"indent",alignLeft:"justifyLeft",alignCenter:"justifyCenter",alignRight:"justifyRight",justify:"justifyFull",replace:"findReplace",insertTable:"insertHTML",dateTime:"insertText",symbol:"insertText"}as Record<string,string>)[command]??command}
