export type WordLanguage="English"|"Hindi";
export type WordDelivery="onscreen"|"pdf";
export const MAX_WORD_QUESTION_MARKS=1000;
export type WordGradingCriterion={target:string;expectedValue:string};
export type WordGradingRule={target:string;expectedOperation:string;expectedValue:string;allocatedMarks:number;partialMarks:number|null;additionalCriteria?:WordGradingCriterion[]};
export type WordQuestion={id?:string;source_fingerprint?:string;number:number;instruction:string;marks:number;section:string|null;display_order:number;is_visible:boolean;gradingRule?:WordGradingRule|null};
export type WordVersion={id:string;test_id:string;version_number:number;title:string;language:WordLanguage;description:string;instructions_markdown:string;delivery_onscreen:boolean;delivery_pdf:boolean;question_count:number;maximum_marks:number;duration_options:number[];passing_marks:number|null;pdf_path:string|null;pdf_file_name:string|null;pdf_size_bytes:number|null;pdf_page_count:number|null;pdf_uploaded_at:string|null;working_matter_snapshot?:import("./word-docx").WorkingMatterSnapshot|null;editor_capabilities?:Record<string,unknown>|null};
export type WordTest={id:string;slug:string;title:string;language:WordLanguage;status:string;current_version_id:string;current_version_number:number;published_at:string|null;updated_at:string};

export const DEFAULT_WORD_INSTRUCTIONS:Record<WordLanguage,string>={English:"1. Carefully read the instructions and solve the questions accordingly.\n2. All questions are mandatory.\n3. The question paper contains the configured number of questions.\n4. **Maximum marks** and question-wise marks are shown with the questions.\n5. Permitted keyboard and mouse commands may be used.",Hindi:"1. दिए गए निर्देशों को ध्यानपूर्वक पढ़ें।\n2. सभी प्रश्न अनिवार्य हैं।\n3. प्रश्नपत्र में निर्धारित संख्या में प्रश्न हैं।\n4. **अधिकतम अंक** और प्रत्येक प्रश्न के अंक प्रश्न के साथ दिए गए हैं।\n5. विद्यार्थी अनुमत keyboard and mouse commands का उपयोग कर सकता है।"};

export function parseDurationOptions(value:string){const values=[...new Set(value.split(/[\s,]+/u).map(Number).filter(item=>Number.isInteger(item)&&item>=1&&item<=240))].sort((a,b)=>a-b);return values.map(minutes=>minutes*60)}
export function parseWordQuestions(value:string):WordQuestion[]{
  try{
    const parsed=JSON.parse(value) as Partial<WordQuestion>[];
    if(Array.isArray(parsed))return parsed.map((question,index)=>({...(question.id?{id:question.id}:{}),...(question.source_fingerprint?{source_fingerprint:question.source_fingerprint}:{}),number:Number(question.number),instruction:String(question.instruction??"").trim(),marks:question.marks===null||question.marks===undefined?Number.NaN:Number(question.marks),section:String(question.section??"").trim()||null,display_order:Number(question.display_order??index+1),is_visible:question.is_visible!==false,...(question.gradingRule&&typeof question.gradingRule==="object"?{gradingRule:question.gradingRule}: {})}));
  }catch{}
  return value.replace(/\r\n?/g,"\n").split("\n").filter(line=>line.trim()).map((line,index)=>{const[marksText,...instruction]=line.split("|");return{number:index+1,marks:Number(marksText),instruction:instruction.join("|").trim(),section:null,display_order:index+1,is_visible:true}})
}
export function calculateWordQuestionTotal(questions:WordQuestion[]){return Number(questions.reduce((sum,question)=>sum+(Number.isFinite(question.marks)?question.marks:0),0).toFixed(2))}
export function calculateWordQuestionSummary(questions:WordQuestion[]){const total=calculateWordQuestionTotal(questions);const missing=questions.filter(question=>!Number.isFinite(question.marks)||question.marks<=0).length;return{questionCount:questions.length,maximumMarks:total,questionsWithoutMarks:missing,averageMarks:questions.length?Number((total/questions.length).toFixed(2)):0}}
export function validateAwardedMarks(awarded:number,maximum:number){return Number.isFinite(awarded)&&awarded>=0&&awarded<=maximum}
export function validateWordDraft(input:{title:string;language:WordLanguage;instructions:string;durations:number[];questionCount:number;maximumMarks:number;passingMarks:number|null;onscreen:boolean;pdf:boolean;questions:WordQuestion[];hasPdf:boolean}){const errors:string[]=[];const numbers=input.questions.map(q=>q.number);const orders=input.questions.map(q=>q.display_order);const total=calculateWordQuestionTotal(input.questions);if(input.title.trim().length<2)errors.push("Enter a test title.");if(input.instructions.trim().length<10)errors.push("Instructions are required.");if(/<\/?(?:script|iframe|object|embed|style)|on\w+\s*=/iu.test(input.instructions))errors.push("Executable HTML is not allowed in instructions.");if(!input.durations.length)errors.push("Add at least one allowed duration between 1 and 240 minutes.");if(!input.onscreen&&!input.pdf)errors.push("Enable at least one question-delivery method.");if(!input.questions.length)errors.push("Add at least one question.");if(input.questions.length!==input.questionCount)errors.push("Configured question count must match the question rows.");if(new Set(numbers).size!==numbers.length||numbers.some(number=>!Number.isInteger(number)||number<1))errors.push("Question numbers must be unique positive whole numbers.");if(new Set(orders).size!==orders.length||orders.some(order=>!Number.isInteger(order)||order<1)||[...orders].sort((a,b)=>a-b).some((order,index)=>order!==index+1))errors.push("Question display order must be consecutive and unique.");if(input.questions.some(q=>!Number.isFinite(q.marks)||q.marks<=0||q.marks>MAX_WORD_QUESTION_MARKS))errors.push(`Each question must have marks greater than zero and no more than ${MAX_WORD_QUESTION_MARKS}.`);if(input.questions.some(q=>q.gradingRule&&(!q.gradingRule.target.trim()||!q.gradingRule.expectedOperation.trim()||q.gradingRule.allocatedMarks<=0||q.gradingRule.allocatedMarks>q.marks||q.gradingRule.partialMarks!==null&&(q.gradingRule.partialMarks<0||q.gradingRule.partialMarks>q.gradingRule.allocatedMarks))))errors.push("Each automatic grading rule needs an exact target, operation, expected value, valid allocated marks, and optional partial marks within the allocation.");if(input.onscreen&&input.questions.some(q=>q.is_visible&&!q.instruction.trim()))errors.push("Every visible on-screen question requires instruction text.");if(Math.abs(total-input.maximumMarks)>.001)errors.push("Maximum marks must equal the sum of individual question marks.");if(input.passingMarks!==null&&(input.passingMarks<0||input.passingMarks>total))errors.push("Passing marks must not exceed maximum marks.");if(input.pdf&&!input.hasPdf)errors.push("Upload a valid PDF before enabling PDF delivery.");return errors}
export function safeWordSlug(value:string){return value.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)||`word-test-${Date.now()}`}
export function formatWordDuration(seconds:number){const minutes=seconds/60;return `${minutes} minute${minutes===1?"":"s"}`}
export function safePdfName(value:string){return value.normalize("NFKC").replace(/[^a-zA-Z0-9._ -]/g,"_").replace(/\s+/g,"-").slice(0,120)}
export function validatePdfUpload(file:File){const errors:string[]=[];const name=safePdfName(file.name);if(file.type!=="application/pdf")errors.push("The uploaded file must use the application/pdf MIME type.");if(!name.toLowerCase().endsWith(".pdf"))errors.push("The uploaded file must have a .pdf extension.");if(file.size<5||file.size>15*1024*1024)errors.push("PDF size must be between 5 bytes and 15 MB.");return{name,errors}}
