"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { LessonProgress } from "@/lib/typing-curriculum";
import type { ManagedLearningTest } from "@/lib/managed-learning";
import { TypingBrandHeader } from "../_components/typing-brand";

const PROGRESS_KEY = "samradhi-typing-lesson-progress-v2";
const accents = ["from-blue-600 to-cyan-500", "from-violet-600 to-fuchsia-500", "from-emerald-600 to-teal-500", "from-orange-500 to-amber-400", "from-rose-600 to-pink-500", "from-indigo-600 to-blue-500"];

export function LearningCatalog({ lessons }: { lessons: ManagedLearningTest[] }) {
  const [progress, setProgress] = useState<Record<string, LessonProgress>>({});
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<"all" | "new" | "completed">("all");
  useEffect(() => { const timer = window.setTimeout(() => { try { setProgress(JSON.parse(localStorage.getItem(PROGRESS_KEY) ?? "{}")); } catch { setProgress({}); } }, 0); return () => window.clearTimeout(timer); }, []);
  const completed = lessons.filter((lesson) => progress[lesson.id]?.completed);
  const attempts = lessons.reduce((total, lesson) => total + (progress[lesson.id]?.attempts ?? 0), 0);
  const bestWpm = Math.max(0, ...lessons.map((lesson) => progress[lesson.id]?.bestWpm ?? 0));
  const completion = lessons.length ? Math.round(completed.length / lessons.length * 100) : 0;
  const recommended = lessons.find((lesson) => !progress[lesson.id]?.completed) ?? lessons[0];
  const filtered = useMemo(() => lessons.filter((lesson) => {
    const matchesQuery = `${lesson.title} ${lesson.shortDescription}`.toLowerCase().includes(query.toLowerCase());
    const done = progress[lesson.id]?.completed === true;
    return matchesQuery && (filter === "all" || (filter === "completed" ? done : !done));
  }), [filter, lessons, progress, query]);

  return <main className="min-h-screen bg-[#f3f6fb]"><TypingBrandHeader/><section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute -left-20 top-0 h-72 w-72 rounded-full bg-blue-600/25 blur-3xl"/><div className="absolute right-0 top-0 h-72 w-72 rounded-full bg-violet-600/20 blur-3xl"/><div className="relative mx-auto max-w-7xl px-4 py-10 sm:px-6"><Link href="/typing/learn" className="text-xs font-black uppercase tracking-[0.18em] text-cyan-300">← Learning paths</Link><div className="mt-5 grid gap-7 lg:grid-cols-[1fr_420px] lg:items-end"><div><span className="rounded-full border border-white/10 bg-white/10 px-3 py-1 text-[11px] font-black uppercase tracking-widest text-blue-200">Personal learning dashboard</span><h1 className="mt-4 max-w-3xl text-3xl font-black tracking-tight sm:text-5xl">Train smarter. Type faster.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300 sm:text-base">Every lesson is available. Search your course, track improvement, and continue from exactly where you stopped.</p></div><ProgressPanel completion={completion} completed={completed.length} total={lessons.length}/></div><div className="mt-7 grid grid-cols-3 gap-2 sm:max-w-xl"><Metric value={String(attempts)} label="Total attempts"/><Metric value={`${bestWpm}`} label="Best WPM"/><Metric value={`${completion}%`} label="Course progress"/></div></div></section>
  <section className="mx-auto max-w-7xl px-4 py-7 sm:px-6">{recommended && <Link href={`/typing/learn/${recommended.slug}`} className="group flex flex-col justify-between gap-4 overflow-hidden rounded-2xl bg-gradient-to-r from-blue-700 via-indigo-700 to-violet-700 p-5 text-white shadow-lg transition hover:-translate-y-0.5 hover:shadow-xl sm:flex-row sm:items-center"><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/15 text-xl font-black backdrop-blur">▶</span><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-blue-200">Recommended next</p><h2 className="mt-1 text-xl font-black">{recommended.title}</h2><p className="mt-1 text-xs text-blue-100">{progress[recommended.id] ? "Continue your latest training" : "Start your next learning session"}</p></div></div><span className="rounded-xl bg-white px-5 py-2 text-center text-sm font-black text-blue-700 transition group-hover:scale-105">{progress[recommended.id] ? "Continue" : "Start now"} →</span></Link>}
  <div className="mt-6 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:flex-row sm:items-center sm:justify-between"><label className="relative flex-1"><span className="sr-only">Search lessons</span><span aria-hidden="true" className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search lessons…" className="w-full rounded-xl bg-slate-100 py-2.5 pr-3 pl-9 text-sm font-semibold text-slate-900 outline-none ring-blue-500 focus:ring-2"/></label><div className="grid grid-cols-3 gap-1 rounded-xl bg-slate-100 p-1" aria-label="Filter lessons">{(["all", "new", "completed"] as const).map((value) => <button key={value} type="button" onClick={() => setFilter(value)} className={`rounded-lg px-4 py-2 text-xs font-black capitalize transition ${filter === value ? "bg-white text-blue-700 shadow-sm" : "text-slate-500 hover:text-slate-900"}`}>{value === "new" ? "To practise" : value}</button>)}</div></div>
  {lessons.length === 0 ? <EmptyState/> : filtered.length === 0 ? <div className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><p className="font-black text-slate-800">No lessons match this view.</p><button type="button" onClick={() => { setQuery(""); setFilter("all"); }} className="mt-3 text-sm font-black text-blue-700">Clear filters</button></div> : <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map((lesson) => <LessonCard key={lesson.id} lesson={lesson} index={lessons.indexOf(lesson)} result={progress[lesson.id]}/>)}</div>}</section></main>;
}

function ProgressPanel({ completion, completed, total }: { completion: number; completed: number; total: number }) { return <div className="rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-300">Overall completion</p><p className="mt-1 text-3xl font-black">{completion}%</p></div><div className="relative flex h-16 w-16 items-center justify-center rounded-full" style={{ background: `conic-gradient(#22d3ee ${completion * 3.6}deg, rgba(255,255,255,.12) 0deg)` }}><div className="flex h-12 w-12 items-center justify-center rounded-full bg-slate-950 text-xs font-black">{completed}/{total}</div></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-blue-500 transition-all duration-700" style={{ width: `${completion}%` }}/></div></div>; }
function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-xl border border-white/10 bg-white/5 px-3 py-2"><strong className="block text-lg font-black text-white">{value}</strong><span className="text-[10px] font-bold text-slate-400">{label}</span></div>; }

function LessonCard({ lesson, index, result }: { lesson: ManagedLearningTest; index: number; result?: LessonProgress }) {
  const accent = accents[index % accents.length]; const done = result?.completed === true; const words = lesson.content.trim().split(/\s+/u).filter(Boolean).length;
  return <article className="group relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className={`absolute inset-x-0 top-0 h-1 bg-gradient-to-r ${accent}`}/><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br text-sm font-black text-white shadow-md ${accent}`}>{String(index + 1).padStart(2, "0")}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${done ? "bg-emerald-100 text-emerald-700" : "bg-blue-50 text-blue-700"}`}>{done ? "✓ Completed" : "Ready"}</span></div><h2 className="mt-3 line-clamp-2 min-h-10 text-sm font-black leading-5 text-slate-950">{lesson.title}</h2><div className="mt-3 flex flex-wrap gap-1.5 text-[10px] font-bold text-slate-500"><span className="rounded-md bg-slate-100 px-2 py-1">{words} words</span><span className="rounded-md bg-slate-100 px-2 py-1">{lesson.unlockAccuracy}% target</span></div><div className="mt-3 grid grid-cols-2 gap-2"><MiniStat label="Best WPM" value={result ? String(result.bestWpm) : "—"}/><MiniStat label="Accuracy" value={result ? `${result.bestAccuracy}%` : "—"}/></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full bg-gradient-to-r ${accent}`} style={{ width: done ? "100%" : result ? `${Math.min(100, result.bestAccuracy)}%` : "4%" }}/></div><Link href={`/typing/learn/${lesson.slug}`} className="mt-3 flex items-center justify-between rounded-xl bg-slate-950 px-3 py-2 text-xs font-black text-white transition group-hover:bg-blue-700"><span>{result ? "Continue lesson" : "Start lesson"}</span><span aria-hidden="true">→</span></Link></article>;
}
function MiniStat({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 px-2.5 py-2"><span className="block text-[9px] font-bold uppercase tracking-wide text-slate-400">{label}</span><strong className="mt-0.5 block text-xs text-slate-900">{value}</strong></div>; }
function EmptyState() { return <div className="mt-6 rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><div className="text-4xl">⌨️</div><h2 className="mt-4 text-xl font-black text-slate-900">Your course is being prepared</h2><p className="mt-2 text-sm text-slate-500">Admin-published learning tests will appear here automatically.</p></div>; }

