"use client";

import Link from "next/link";
import { useActionState, useEffect, useMemo, useState } from "react";
import { MANAGED_INPUT_SYSTEMS, countPassageWords, type ManagedTestMode, type ManagedTestStatus } from "@/lib/admin-tests";
import { STENOGRAPHY_TASK_CATEGORIES } from "@/lib/stenography-task-library";
import { encodingValidationMessage, type HindiTextFormat } from "@/lib/hindi-font-converter";
import { FontConverter } from "@/app/admin/font-converter/font-converter";
import { deleteManagedTest, duplicateManagedTest, saveExamManagedTest, saveLearningManagedTest, saveManagedTest, savePracticeManagedTest, saveStenographyManagedTest, setManagedTestStatus, type TestFormState } from "./actions";

type Version = { id:string; description:string|null; language:"English"|"Hindi"; mode:ManagedTestMode; input_system_id:string; duration_seconds:number; passage:string; required_wpm:number; required_accuracy:number; backspace_mode:string; word_method:string; highlight_mode:string; visibility:"public"|"private"; passage_characters:number; passage_words:number; configuration?:Record<string,unknown>|null };
export type ManagedTestRow = { id:string; title:string; slug:string; description:string|null; language:string|null; status:ManagedTestStatus; mode:ManagedTestMode; input_system_id:string; visibility:"public"|"private"; duration_seconds:number|null; current_version_id:string|null; current_version_number:number; updated_at:string; is_live:boolean; live_starts_at:string|null; live_ends_at:string|null; results_publish_at:string|null; currentVersion:Version|null; attempts:number };
const initialState: TestFormState = {};
const localDateTime = (value:string|null|undefined) => value ? new Date(value).toISOString().slice(0,16) : "";

export default function TestManager({ tests, lockedMode, learningOnly:legacyLearningOnly=false }: { tests:ManagedTestRow[]; lockedMode?:ManagedTestMode; learningOnly?:boolean }) {
  const effectiveMode = lockedMode ?? (legacyLearningOnly ? "learn" : undefined);
  const learningOnly = effectiveMode === "learn";
  const saveAction = effectiveMode === "learn" ? saveLearningManagedTest : effectiveMode === "practice" ? savePracticeManagedTest : effectiveMode === "exam" ? saveExamManagedTest : effectiveMode === "stenography" ? saveStenographyManagedTest : saveManagedTest;
  const [editing,setEditing] = useState<ManagedTestRow|null>(null);
  const [preview,setPreview] = useState(false);
  const [query,setQuery] = useState("");
  const [status,setStatus] = useState("all");
  const [kind,setKind] = useState(effectiveMode ?? "all");
  const [sort,setSort] = useState("updated");
  const [passage,setPassage] = useState("");
  const [language,setLanguage] = useState<"English"|"Hindi">("English");
  const [inputSystem,setInputSystem] = useState("english-qwerty");
  const [formMode,setFormMode] = useState<ManagedTestMode>(effectiveMode ?? "practice");
  const [isLive,setIsLive] = useState(false);
  const [converterOpen,setConverterOpen] = useState(false);
  const [showRawPassage,setShowRawPassage] = useState(false);
  const [krutiFontReady,setKrutiFontReady] = useState(true);
  const [state,action,pending] = useActionState(saveAction,initialState);
  const filtered = useMemo(() => tests.filter((item) => { const q=query.toLowerCase(); const kindMatch=kind==="all"||item.mode===kind||item.language===kind||item.input_system_id.includes(kind)||(kind==="typing"&&item.mode!=="stenography"); return (!q||`${item.title} ${item.slug}`.toLowerCase().includes(q))&&(status==="all"||item.status===status)&&kindMatch; }).sort((a,b)=>sort==="title"?a.title.localeCompare(b.title):sort==="attempts"?b.attempts-a.attempts:new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime()), [tests,query,status,kind,sort]);
  const choose = (test:ManagedTestRow|null) => { setEditing(test); setPassage(test?.currentVersion?.passage??""); setLanguage(test?.currentVersion?.language??"English"); setInputSystem(test?.currentVersion?.input_system_id??"english-qwerty"); setFormMode(effectiveMode??test?.currentVersion?.mode??"practice"); setIsLive(Boolean(test?.is_live)); setPreview(false); setShowRawPassage(false); };
  const systems = MANAGED_INPUT_SYSTEMS.filter((system) => system.language === language);
  const showAdminRules = formMode !== "practice" || isLive;
  const passageFormat:HindiTextFormat=inputSystem.includes("krutidev")?"krutidev":"unicode";
  const encodingWarning=language==="Hindi"?encodingValidationMessage(passage,passageFormat):null;
  useEffect(()=>{if(language!=="Hindi"||passageFormat!=="krutidev")return;let active=true;document.fonts.load('20px "Kruti Dev 010"').then(()=>{if(active)setKrutiFontReady(document.fonts.check('20px "Kruti Dev 010"'));}).catch(()=>{if(active)setKrutiFontReady(false);});return()=>{active=false};},[language,passageFormat]);

  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_430px]">
    <section className="rounded-2xl bg-white p-5 shadow">
      <div className="grid gap-3 md:grid-cols-4"><input aria-label="Search tests" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search title or slug" className="input"/><select aria-label="Filter status" value={status} onChange={(event)=>setStatus(event.target.value)} className="input"><option value="all">All statuses</option>{["draft","published","unpublished","archived"].map((value)=><option key={value}>{value}</option>)}</select><select aria-label="Filter language or mode" value={kind} onChange={(event)=>setKind(event.target.value)} className="input"><option value="all">All languages and modes</option><option>English</option><option>Hindi</option><option value="unicode">Hindi Unicode</option><option value="krutidev">Kruti Dev</option><option value="typing">Typing</option>{["learn","practice","exam","stenography"].map((value)=><option key={value}>{value}</option>)}</select><select aria-label="Sort tests" value={sort} onChange={(event)=>setSort(event.target.value)} className="input"><option value="updated">Recently updated</option><option value="title">Title</option><option value="attempts">Attempts</option></select></div>
      <div className="mt-5 space-y-3">{filtered.length ? filtered.map((test)=><TestRow key={test.id} test={test} learningOnly={learningOnly} onEdit={()=>choose(test)}/>) : <p className="rounded-xl border border-dashed p-8 text-center text-slate-500">No tests match these filters.</p>}</div>
    </section>
    <aside className="rounded-2xl bg-white p-5 shadow xl:sticky xl:top-5 xl:self-start">
      <div className="flex justify-between"><h2 className="text-xl font-black">{editing ? "Edit and create version" : "Create test"}</h2>{editing&&<button type="button" className="font-bold text-blue-700" onClick={()=>choose(null)}>New</button>}</div>
      <form action={action} className="mt-4 space-y-3">
        <input type="hidden" name="testId" value={editing?.id??""}/>
        {effectiveMode&&<input type="hidden" name="mode" value={effectiveMode}/>} {learningOnly&&<input type="hidden" name="visibility" value="public"/>}
        <Field label="Title"><input className="input" name="title" defaultValue={editing?.title} style={{fontFamily:language==="Hindi"?'"Nirmala UI", Mangal, "Noto Sans Devanagari", sans-serif':undefined}} required/><span className="mt-1 block text-xs font-normal text-slate-500">Titles always use Unicode; only Passage / matter may use legacy Kruti Dev encoding.</span></Field>
        <Field label="URL slug"><input className="input" name="slug" defaultValue={editing?.slug}/></Field>
        <Field label="Description"><textarea className="input min-h-20" name="description" defaultValue={editing?.currentVersion?.description??""}/></Field>
        <div className="grid grid-cols-2 gap-3"><Field label="Language"><select className="input" name="language" value={language} onChange={(event)=>{const value=event.target.value as "English"|"Hindi";setLanguage(value);const first=MANAGED_INPUT_SYSTEMS.find((system)=>system.language===value);if(first)setInputSystem(first.id);}}><option>English</option><option>Hindi</option></select></Field><Field label="Input system"><select className="input" name="inputSystemId" value={inputSystem} onChange={(event)=>setInputSystem(event.target.value)}>{systems.map((system)=><option key={system.id} value={system.id}>{system.label}</option>)}</select></Field></div>
        <div className="grid grid-cols-2 gap-3">{!effectiveMode&&<Field label="Mode"><select className="input" name="mode" value={formMode} onChange={(event)=>setFormMode(event.target.value as ManagedTestMode)}>{["learn","practice","exam","stenography"].map((value)=><option key={value}>{value}</option>)}</select></Field>}<Field label="Duration (minutes, optional)"><input className="input" name="durationMinutes" type="number" min={1} max={60} defaultValue={(editing?.currentVersion?.duration_seconds??600)/60}/></Field></div>
        <Field label="Passage / matter"><div className="mb-2 flex flex-wrap items-center justify-between gap-2">{language==="Hindi"&&<span className={`rounded-full px-3 py-1 text-xs font-black ${passageFormat==="krutidev"?"bg-amber-100 text-amber-900":"bg-emerald-100 text-emerald-900"}`}>{passageFormat==="krutidev"?"Kruti Dev 010 · Legacy encoded text":"Unicode Hindi · Mangal display"}</span>}<div className="flex gap-2">{passageFormat==="krutidev"&&<button type="button" aria-pressed={showRawPassage} onClick={()=>setShowRawPassage(value=>!value)} className="rounded-lg border px-3 py-2 text-xs font-black">{showRawPassage?"View Hindi preview":"View raw encoding"}</button>}{language==="Hindi"&&<button type="button" onClick={()=>setConverterOpen(true)} className="rounded-lg border border-violet-300 px-3 py-2 text-xs font-black text-violet-800">Open Font Converter</button>}</div></div><textarea className="input min-h-48 text-lg leading-8" name="passage" value={passage} onChange={(event)=>setPassage(event.target.value)} data-encoding={passageFormat} style={{fontFamily:language==="Hindi"?(passageFormat==="krutidev"&&!showRawPassage?'"Kruti Dev 010", sans-serif':passageFormat==="krutidev"?'ui-monospace, Consolas, monospace':'Mangal, "Nirmala UI", sans-serif'):undefined}} required/><p className="mt-1 text-xs text-slate-500">{[...passage].length.toLocaleString()} characters · {countPassageWords(passage).toLocaleString()} words</p>{encodingWarning&&<p role="alert" className="mt-2 rounded-lg bg-amber-50 p-3 text-sm font-bold text-amber-900">{encodingWarning}</p>}{passageFormat==="krutidev"&&krutiFontReady===false&&<p role="alert" className="mt-2 rounded-lg bg-red-50 p-3 text-sm font-bold text-red-700">Kruti Dev 010 could not be loaded from /fonts/KrutiDev010.ttf. Legacy text cannot be previewed reliably.</p>}</Field>
        <div className="grid grid-cols-2 gap-3"><Field label="Required WPM"><input className="input" name="requiredWpm" type="number" min={0} max={300} step="0.01" defaultValue={editing?.currentVersion?.required_wpm??30}/></Field><Field label="Required accuracy"><input className="input" name="requiredAccuracy" type="number" min={0} max={100} step="0.01" defaultValue={editing?.currentVersion?.required_accuracy??90}/></Field></div>
        {formMode==="stenography" && <Field label="Task category"><select className="input" name="taskCategory" defaultValue={(editing?.currentVersion?.configuration?.task_category as string|undefined)??"Task"}>{STENOGRAPHY_TASK_CATEGORIES.map((category)=><option key={category} value={category}>{category}</option>)}</select></Field>}
        {formMode==="stenography" && <Field label="Dictation audio (optional)"><input type="hidden" name="existingAudioPath" value={(editing?.currentVersion?.configuration?.audio_path as string|undefined)??""}/>{(editing?.currentVersion?.configuration?.audio_path as string|undefined) && <p className="mb-2 text-xs font-bold text-emerald-700">Audio attached ✓ <label className="ml-2 font-normal text-slate-600"><input type="checkbox" name="removeAudio"/> Remove on save</label></p>}<input className="input" name="audioFile" type="file" accept="audio/*"/><p className="mt-1 text-xs text-slate-500">Students hear this recording (speed adjustable) instead of reading the passage; the passage is still used to score their typed text.</p></Field>}
        {showAdminRules ? <><Field label="Backspace"><select className="input" name="backspaceMode" defaultValue={editing?.currentVersion?.backspace_mode??"full"}><option value="full">Full</option><option value="word">Current word</option><option value="disabled">Disabled</option></select></Field><Field label="Word calculation"><select className="input" name="wordMethod" defaultValue={editing?.currentVersion?.word_method??"characters"}><option value="characters">5 characters</option><option value="spaces">Space-separated words</option></select></Field><Field label="Highlight default"><select className="input" name="highlightMode" defaultValue={editing?.currentVersion?.highlight_mode??"character"}><option value="character">Character</option><option value="word">Current word</option><option value="none">None</option></select></Field></> : <p className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm font-black text-blue-900">Practice settings are controlled by the student.</p>}
        <Field label="Visibility"><select className="input" name="visibility" defaultValue={editing?.currentVersion?.visibility??"private"}><option value="private">Private</option><option value="public">Public</option></select></Field>
        {!effectiveMode&&<fieldset className="rounded-xl border border-blue-200 bg-blue-50 p-3"><label className="flex items-center gap-2 font-black text-blue-950"><input type="checkbox" name="isLive" checked={isLive} onChange={(event)=>setIsLive(event.target.checked)}/>Free scheduled live test</label><p className="mt-1 text-xs text-blue-800">Live tests must be public. Each registered student receives one attempt; results unlock at the publication time.</p>{isLive&&<div className="mt-3 grid gap-2"><Field label="Starts"><input className="input" name="startsAt" type="datetime-local" defaultValue={localDateTime(editing?.live_starts_at)}/></Field><Field label="Ends"><input className="input" name="endsAt" type="datetime-local" defaultValue={localDateTime(editing?.live_ends_at)}/></Field><Field label="Publish results"><input className="input" name="resultsPublishAt" type="datetime-local" defaultValue={localDateTime(editing?.results_publish_at)}/></Field></div>}</fieldset>}
        <button type="button" onClick={()=>setPreview((value)=>!value)} className="w-full rounded-lg border py-2 font-bold">{preview?"Hide preview":"Preview"}</button>
        {preview&&<div className="max-h-56 overflow-auto rounded-xl bg-slate-50 p-4"><h3 className="font-bold">Passage preview</h3>{passageFormat==="krutidev"&&<span className="mt-2 inline-flex rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-900">Kruti Dev 010 · Legacy encoded text</span>}<p className="mt-2 whitespace-pre-wrap text-lg leading-8" style={{fontFamily:inputSystem.includes("krutidev")?'"Kruti Dev 010", sans-serif':language==="Hindi"?'"Nirmala UI", Mangal, sans-serif':"Arial, sans-serif"}}>{passage||"No passage entered."}</p></div>}
        {state.error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.error}</p>}{state.success&&<p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{state.success}</p>}
        {learningOnly?<button disabled={pending} className="w-full rounded-lg bg-blue-700 py-3 font-bold text-white">{editing?"Save and Publish Changes":"Create and Publish Test"}</button>:<div className="grid grid-cols-2 gap-2"><button disabled={pending} name="intent" value="draft" className="rounded-lg border border-blue-700 py-3 font-bold text-blue-700">Save draft</button><button disabled={pending} name="intent" value="publish" className="rounded-lg bg-blue-700 py-3 font-bold text-white">Publish</button></div>}
      </form>{converterOpen&&<div role="dialog" aria-modal="true" aria-label="Font and text converter" className="fixed inset-0 z-[100] overflow-y-auto bg-slate-950/70 p-3 sm:p-6"><div className="mx-auto max-w-[1500px] rounded-3xl bg-slate-100 p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-black">Font & Text Converter</h2><button type="button" aria-label="Close converter" onClick={()=>setConverterOpen(false)} className="rounded-lg bg-white px-4 py-2 text-xl font-black">×</button></div><FontConverter initialText={passage} initialSource={passageFormat} expectedOutput={passageFormat} onUse={(result)=>{if(result.encoding!==passageFormat){alert(`Select ${passageFormat==="krutidev"?"Kruti Dev 010":"Unicode Hindi — Mangal"} output before inserting.`);return;}if(confirm("Replace the Passage / matter field with this converted text? The current passage will remain unchanged until you confirm.")){setPassage(result.text);setConverterOpen(false);}}}/></div></div>}
    </aside>
  </div>;
}

function TestRow({test,onEdit,learningOnly}:{test:ManagedTestRow;onEdit:()=>void;learningOnly:boolean}) { const version=test.currentVersion; return <article className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{test.title}</h3><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{test.status}</span>{test.is_live&&<span className="rounded-full bg-red-100 px-2 py-1 text-xs font-black text-red-700">FREE LIVE</span>}<span className="text-xs">v{test.current_version_number}</span></div><p className="mt-1 text-sm text-slate-600">{test.language} · {test.input_system_id} · {test.mode} · {Math.round((test.duration_seconds??0)/60)} min</p><p className="mt-1 text-xs text-slate-500">{version?.passage_characters??0} characters · {version?.passage_words??0} words · {test.attempts} attempts · {test.visibility}</p>{test.is_live&&<p className="mt-1 text-xs font-bold text-blue-700">{new Date(test.live_starts_at??"").toLocaleString()} → {new Date(test.live_ends_at??"").toLocaleString()} · results {new Date(test.results_publish_at??"").toLocaleString()}</p>}</div><div className="flex gap-2"><Link className="rounded-lg border px-3 py-2 text-sm font-bold" href={`/tests/${test.slug}`}>View</Link><button className="rounded-lg border px-3 py-2 text-sm font-bold" onClick={onEdit}>Edit</button></div></div><div className="mt-3 flex flex-wrap gap-2"><Status test={test} status={test.status==="published"?"unpublished":"published"} label={test.status==="published"?"Unpublish":"Publish"}/>{test.status!=="archived"&&<Status test={test} status="archived" label="Archive"/>}{!learningOnly&&<form action={duplicateManagedTest}><input type="hidden" name="testId" value={test.id}/><button className="rounded-lg border px-3 py-2 text-sm font-bold">Duplicate</button></form>}<form action={deleteManagedTest} onSubmit={(event)=>{if(!confirm(test.attempts?"This test has attempts and cannot be deleted. Archive it instead.":`Permanently delete ${test.title}?`))event.preventDefault();}}><input type="hidden" name="testId" value={test.id}/><button disabled={test.attempts>0} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700 disabled:opacity-40">Delete</button></form></div></article>; }
function Status({test,status,label}:{test:ManagedTestRow;status:ManagedTestStatus;label:string}) { return <form action={setManagedTestStatus}><input type="hidden" name="testId" value={test.id}/><input type="hidden" name="status" value={status}/><button className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white">{label}</button></form>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { if(label==="URL slug")return <span hidden>{children}</span>; return <label className="block text-sm font-bold text-slate-700"><span className="mb-1 block">{label}</span>{children}</label>; }
