"use server";
import { redirect } from "next/navigation";
import { requireStudent } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import{validateWordEditorDocument,validateWordEditorOperations}from"@/lib/word-editor-document";

export async function prepareWordAttempt(form:FormData){await requireStudent();if(form.get("accepted")!=="on")return;const testId=String(form.get("testId")??"");const duration=Number(form.get("duration"));const language=String(form.get("language")==="hindi"?"hindi":"english");const supabase=await createClient();const{data:test}=await supabase.from("word_efficiency_tests").select("current_version_id").eq("id",testId).eq("status","published").maybeSingle();const{data:version}=test?.current_version_id?await supabase.from("word_efficiency_versions").select("id,delivery_onscreen,delivery_pdf,pdf_path").eq("id",test.current_version_id).maybeSingle():{data:null};if(!version)redirect(`/typing/word-efficiency/${language}/${testId}/instructions?duration=${duration}&error=Test%20version%20unavailable`);if(version.delivery_pdf&&(!version.pdf_path||form.get("pdfAcknowledged")!==version.id))redirect(`/typing/word-efficiency/${language}/${testId}/instructions?duration=${duration}&error=Download%20the%20question%20paper%20before%20starting`);const delivery=version.delivery_onscreen?"onscreen":"pdf";const{data,error}=await supabase.rpc("prepare_word_efficiency_attempt",{p_test_id:testId,p_duration_seconds:duration,p_delivery:delivery});if(error||!data)redirect(`/typing/word-efficiency/${language}/${testId}/instructions?duration=${duration}&error=${encodeURIComponent(error?.message??"Unable to prepare attempt")}`);const{error:documentError}=await supabase.rpc("initialize_word_efficiency_document",{p_attempt_id:data,p_show_questions:form.get("showQuestions")==="on"});if(documentError)redirect(`/typing/word-efficiency/${language}/${testId}/instructions?duration=${duration}&error=${encodeURIComponent(documentError.message)}`);const{error:startError}=await supabase.rpc("start_word_efficiency_attempt",{p_attempt_id:data});if(startError)redirect(`/typing/word-efficiency/${language}/${testId}/instructions?duration=${duration}&error=${encodeURIComponent("The attempt could not be started.")}`);redirect(`/typing/word-efficiency/${language}/${testId}/workspace?attempt=${data}`)}
export async function startWordAttempt(attemptId:string){await requireStudent();const supabase=await createClient();const {data,error}=await supabase.rpc("start_word_efficiency_attempt",{p_attempt_id:attemptId});if(error)throw new Error("The attempt could not be started.");return String(data)}
export async function autosaveWordDocument(attemptId:string,document:unknown):Promise<{ok:boolean;error:string}>{await requireStudent();const safeDocument=validateWordEditorDocument(document);const supabase=await createClient();const{data:attempt,error:attemptError}=await supabase.from("word_efficiency_attempts").select("snapshot").eq("id",attemptId).maybeSingle();if(!attempt)return{ok:false,error:process.env.NODE_ENV==="development"?`Autosave failed: ${attemptError?.message??"attempt unavailable"}`:"Autosave failed."};validateWordEditorOperations(safeDocument,(attempt.snapshot as Record<string,unknown>)?.editor_capabilities);const{error}=await supabase.rpc("autosave_word_efficiency_document",{p_attempt_id:attemptId,p_document:safeDocument});if(error)return{ok:false,error:process.env.NODE_ENV==="development"?`Autosave failed: ${error.message}`:"Autosave failed."};return{ok:true,error:""}}
export async function submitWordDocument(attemptId:string,document:unknown):Promise<{ok:boolean;error:string}>{await requireStudent();try{const safeDocument=validateWordEditorDocument(document);const supabase=await createClient();const{data:attempt,error:attemptError}=await supabase.from("word_efficiency_attempts").select("snapshot").eq("id",attemptId).maybeSingle();if(!attempt)return{ok:false,error:submissionError(attemptError??{message:"attempt unavailable"})};validateWordEditorOperations(safeDocument,(attempt.snapshot as Record<string,unknown>)?.editor_capabilities);const{error}=await supabase.rpc("submit_word_efficiency_document",{p_attempt_id:attemptId,p_document:safeDocument});if(error){if(process.env.NODE_ENV==="development")console.error("[Word Efficiency submission RPC failed]",{message:error.message,code:error.code,details:error.details,hint:error.hint});return{ok:false,error:submissionError(error)}}return{ok:true,error:""}}catch(error){return{ok:false,error:submissionError(error)}}}

function submissionError(error:unknown){if(process.env.NODE_ENV!=="development")return"Submission failed.";const candidate=error as{message?:unknown;code?:unknown;details?:unknown;hint?:unknown};const fields=[`message=${String(candidate?.message??"unknown submission error")}`];if(candidate?.code)fields.push(`code=${String(candidate.code)}`);if(candidate?.details)fields.push(`details=${String(candidate.details)}`);if(candidate?.hint)fields.push(`hint=${String(candidate.hint)}`);return`Submission failed: ${fields.join(" · ")}`}
