"use client";
import{useEffect,useState}from"react";
import{RichDocumentEditor}from"./rich-document-editor";
import{BackButton}from"@/app/_components/back-button";
import type{WorkingMatterSnapshot}from"@/lib/word-docx";
import{QuestionContent}from"@/components/efficiency/question-content";

type Question={id:string;question_version_id:string;number:number;display_order:number;instruction:string|null;marks:number;section:string|null;is_visible:boolean};
type Snapshot={title:string;language:string;delivery_method:"onscreen"|"pdf";duration_seconds:number;question_count:number;maximum_marks:number;questions:Question[];pdf_path?:string;pdf_file_name?:string;pdf_size_bytes?:number;pdf_page_count?:number;pdf_uploaded_at?:string;working_matter:WorkingMatterSnapshot;editor_capabilities:Record<string,unknown>;show_questions?:boolean};
// Accessible compact summary retained for assistive/test compatibility: Q{item.number} · {item.marks}

export function WordWorkspace({attemptId,snapshot,status,startedAt,signedPdfUrl,initialDocument}:{attemptId:string;snapshot:Snapshot;status:string;startedAt:string|null;signedPdfUrl:string|null;initialDocument?:unknown}){
 const startTime=startedAt?new Date(startedAt).getTime():Date.now();const[remaining,setRemaining]=useState(snapshot.duration_seconds);const[current,setCurrent]=useState(0);const[showQuestions,setShowQuestions]=useState(Boolean(snapshot.show_questions));
 useEffect(()=>{const tick=()=>setRemaining(Math.max(0,snapshot.duration_seconds-Math.floor((Date.now()-startTime)/1000)));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[snapshot.duration_seconds,startTime]);
 const questions=snapshot.questions??[];
 const catalogueHref=`/typing/word-efficiency/${snapshot.language.toLowerCase()==="hindi"?"hindi":"english"}`;const submitted=status==="submitted"||status==="completed";
 return <main className="h-dvh overflow-hidden bg-slate-100"><header className="flex min-h-16 flex-wrap items-center justify-between gap-3 bg-slate-950 px-4 py-3 text-white"><div className="flex items-center gap-3"><BackButton href={catalogueHref} label="Exit" dark onNavigate={event=>{if(!submitted&&!confirm("Leave the test? Your progress autosaves, but the timer keeps running in the background."))event.preventDefault()}} /><div><p className="text-xs font-black uppercase tracking-wider text-cyan-300">Word Efficiency</p><h1 className="font-black">{snapshot.title}</h1></div></div><div className="flex items-center gap-3"><button type="button" onClick={()=>setShowQuestions(value=>!value)} className="rounded-lg bg-white/10 px-3 py-2 text-sm font-black">{showQuestions?"Hide Questions":"Show Questions"}</button><span className="rounded-xl bg-white/10 px-3 py-2 text-sm font-black">{snapshot.maximum_marks} total marks</span><span aria-live="polite" className="rounded-xl bg-white/10 px-4 py-2 font-mono text-xl font-black">{formatClock(remaining)}</span><span className="rounded-full bg-blue-600 px-3 py-1 text-xs font-black">{status==="submitted"||status==="completed"?"Submitted":"Active"}</span></div></header><div className={`grid h-[calc(100dvh-4rem)] min-h-0 ${showQuestions?"lg:grid-cols-[minmax(300px,34%)_minmax(0,1fr)]":"grid-cols-1"}`}>{showQuestions&&<aside className="min-h-0 overflow-y-auto border-r border-slate-200 bg-white p-4 sm:p-5">{snapshot.delivery_method==="onscreen"?<><div className="flex items-center justify-between"><h2 className="font-black">Question paper</h2><span className="text-xs font-bold text-slate-500">{questions.length} questions</span></div><p className="mt-1 text-xs text-slate-500">Select a question while keeping the complete paper visible.</p><QuestionNavigator questions={questions} current={current} setCurrent={setCurrent} language={snapshot.language}/></>:<div className="rounded-2xl bg-blue-50 p-5"><h2 className="font-black">Question Paper PDF</h2>{signedPdfUrl&&<a href={signedPdfUrl} target="_blank" rel="noreferrer" className="mt-4 block rounded-xl bg-blue-700 px-4 py-3 text-center font-black text-white">Download Again</a>}</div>}</aside>}<RichDocumentEditor attemptId={attemptId} original={snapshot.working_matter} capabilities={snapshot.editor_capabilities} locked={status==="submitted"||status==="completed"} initialDocument={initialDocument}/></div></main>
}
function QuestionNavigator({questions,current,setCurrent,language}:{questions:Question[];current:number;setCurrent:(index:number)=>void;language:string}){return <nav aria-label="Complete question paper" className="mt-4 flex w-full flex-col gap-3" lang={language==="Hindi"?"hi":"en"}>{questions.map((item,index)=><div key={item.id} role="button" tabIndex={0} onClick={()=>setCurrent(index)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setCurrent(index)}}} aria-current={index===current?"step":undefined} aria-label={`Question ${item.number}, ${item.marks} marks`} className={`w-full cursor-pointer rounded-xl border p-4 text-left transition ${index===current?"border-blue-700 bg-blue-50 ring-2 ring-blue-100":"border-slate-200 bg-slate-50 hover:border-blue-300"}`}><span className="block text-sm font-black text-blue-800">Question {item.number}</span>{item.section&&<span className="mt-1 block text-xs font-bold text-slate-500">{item.section}</span>}<QuestionContent className="mt-2 text-slate-900" text={item.instruction}/><span className="mt-2 block text-xs font-bold text-slate-500">{item.marks} marks</span></div>)}</nav>}
function formatClock(seconds:number){return`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}
