"use client";

import{useEffect,useState}from"react";
import{prepareWordAttempt}from"../../../actions";

export function StudentTestLaunch({testId,versionId,language,duration,hasPdf,hasOnscreen,pdfFileName,serverError}:{testId:string;versionId:string;language:string;duration:number;hasPdf:boolean;hasOnscreen:boolean;pdfFileName:string|null;serverError?:string}){
 const storageKey=`word-efficiency-pdf-ack:${testId}:${versionId}`;const[downloaded,setDownloaded]=useState(false);const[downloading,setDownloading]=useState(false);const[downloadError,setDownloadError]=useState("");const[accepted,setAccepted]=useState(false);const[showQuestions,setShowQuestions]=useState(hasOnscreen);
 useEffect(()=>{if(hasPdf)setDownloaded(localStorage.getItem(storageKey)==="downloaded")},[hasPdf,storageKey]);
 const download=async()=>{setDownloading(true);setDownloadError("");try{const response=await fetch(`/typing/word-efficiency/${language}/${testId}/question-paper`,{credentials:"same-origin",cache:"no-store"});if(!response.ok)throw new Error("download failed");const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=pdfFileName||"word-efficiency-question-paper.pdf";document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);localStorage.setItem(storageKey,"downloaded");setDownloaded(true)}catch{localStorage.removeItem(storageKey);setDownloaded(false);setDownloadError("Question paper download failed. Please retry.")}finally{setDownloading(false)}};
 const canStart=accepted&&(!hasPdf||downloaded);const delivery=hasOnscreen?"onscreen":"pdf";
 return <form action={prepareWordAttempt} className="h-fit rounded-2xl border border-blue-200 bg-blue-50 p-5"><input type="hidden" name="testId" value={testId}/><input type="hidden" name="versionId" value={versionId}/><input type="hidden" name="duration" value={duration}/><input type="hidden" name="language" value={language}/><input type="hidden" name="delivery" value={delivery}/><input type="hidden" name="pdfAcknowledged" value={downloaded?versionId:""}/><h2 className="font-black">Question delivery</h2>{hasOnscreen&&<div className="mt-3 rounded-xl bg-white p-4"><strong className="block">On-screen questions</strong><span className="mt-1 block text-xs leading-5 text-slate-600">Questions and navigation will be available in the workspace.</span><label className="mt-3 flex gap-2 text-sm font-bold"><input type="checkbox" name="showQuestions" checked={showQuestions} onChange={event=>setShowQuestions(event.target.checked)}/>Show questions inside the test workspace</label>{!showQuestions&&<p className="mt-2 text-xs text-amber-700">The panel starts hidden; use Show Questions in the workspace to reopen it.</p>}</div>}{hasPdf&&<section className="mt-3 rounded-xl border border-violet-200 bg-white p-4" aria-labelledby="question-paper-heading"><h3 id="question-paper-heading" className="font-black">Private question paper PDF</h3>{hasOnscreen&&<p className="mt-1 text-xs text-slate-600">This test includes both the downloadable PDF and on-screen questions.</p>}<button type="button" onClick={download} disabled={downloading} aria-describedby="pdf-download-status" className="mt-4 w-full rounded-xl bg-violet-700 px-5 py-3 font-black text-white disabled:opacity-60">{downloading?"Downloading…":downloadError?"Retry Download":"Download Question Paper PDF"}</button><div id="pdf-download-status" aria-live="polite">{downloaded&&<p role="status" className="mt-3 text-sm font-bold text-green-700">Question paper downloaded. You may now start the test.</p>}{downloadError&&<p role="alert" className="mt-3 text-sm font-bold text-red-700">{downloadError}</p>}</div></section>}<label className="mt-5 flex gap-3 rounded-xl border border-blue-200 bg-white p-4 text-sm font-bold"><input type="checkbox" name="accepted" checked={accepted} onChange={event=>setAccepted(event.target.checked)} required/>I have read and understood the instructions.</label>{serverError&&<p role="alert" className="mt-3 text-sm font-bold text-red-700">{serverError}</p>}<button disabled={!canStart} className="mt-5 w-full rounded-xl bg-blue-700 px-5 py-3 font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300" aria-describedby={hasPdf?"pdf-download-status":undefined}>Start Test</button><p className="mt-3 text-center text-xs text-slate-500">Your attempt and timer begin only when Start Test is pressed.</p></form>
}
