"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { MY_MATTERS_KEY, parseMatterList, type MyTestMatter } from "@/lib/typing-matters";
import { TypingBrandHeader } from "../_components/typing-brand";
import { UploadMatterButton } from "../_components/upload-matter-modal";

export default function MyMattersPage(){const [matters,setMatters]=useState<MyTestMatter[]>([]); useEffect(()=>{const timer=setTimeout(()=>{try{setMatters(parseMatterList(JSON.parse(localStorage.getItem(MY_MATTERS_KEY)??"[]")))}catch{setMatters([])}},0);return()=>clearTimeout(timer)},[]); const save=(next:MyTestMatter[])=>{setMatters(next);localStorage.setItem(MY_MATTERS_KEY,JSON.stringify(next))}; const rename=(matter:MyTestMatter)=>{const title=prompt("Rename matter",matter.title)?.trim();if(title)save(matters.map(item=>item.id===matter.id?{...item,title,updatedAt:new Date().toISOString()}:item))}; const duplicate=(matter:MyTestMatter)=>{const now=new Date().toISOString();save([{...matter,id:crypto.randomUUID(),title:`${matter.title} (Copy)`,createdAt:now,updatedAt:now},...matters])}; const remove=(matter:MyTestMatter)=>{if(confirm(`Delete “${matter.title}”? This cannot be undone.`))save(matters.filter(item=>item.id!==matter.id))}; return <main className="min-h-screen bg-slate-100"><TypingBrandHeader/><section className="mx-auto max-w-7xl px-4 py-10"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-600">Local library</p><h1 className="mt-2 text-4xl font-black">My Matters</h1></div><UploadMatterButton/></div><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{matters.map(matter=><article key={matter.id} className="rounded-2xl bg-white p-6 shadow"><div className="flex justify-between gap-3"><h2 className="text-xl font-black">{matter.title}</h2><span className="rounded-lg bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{matter.visibility}</span></div><p className="mt-2 text-sm text-slate-500">{matter.language} · {matter.mode} · {matter.durationSeconds/60} min</p><p className="mt-4 line-clamp-3 whitespace-pre-wrap text-sm text-slate-600">{matter.passage}</p><div className="mt-5 grid grid-cols-2 gap-2"><Link href={`/typing/my-matters/${matter.id}`} className="rounded-lg bg-blue-600 px-3 py-2 text-center text-sm font-bold text-white">View</Link><Link href={`/typing/my-matters/${matter.id}`} className="rounded-lg bg-green-600 px-3 py-2 text-center text-sm font-bold text-white">Practice</Link><button onClick={()=>rename(matter)} className="rounded-lg bg-slate-100 px-3 py-2 text-sm font-bold">Rename</button><button onClick={()=>duplicate(matter)} className="rounded-lg bg-slate-100 px-3 py-2 text-sm font-bold">Duplicate</button><button onClick={()=>remove(matter)} className="rounded-lg bg-red-50 px-3 py-2 text-sm font-bold text-red-700">Delete</button></div></article>)}{!matters.length&&<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-500">No saved matters yet.</div>}</div></section></main>}
