begin;

create or replace function public.word_efficiency_default_editor_capabilities()
returns jsonb language sql immutable set search_path=pg_catalog,public as $$
with commands(tab_name,group_name,command_name,supported)as(values
 ('Home','clipboard','paste',true),('Home','clipboard','cut',true),('Home','clipboard','copy',true),('Home','clipboard','formatPainter',true),
 ('Home','font','fontName',true),('Home','font','fontSize',true),('Home','font','increaseFontSize',true),('Home','font','decreaseFontSize',true),('Home','font','changeCase',true),('Home','font','bold',true),('Home','font','italic',true),('Home','font','underline',true),('Home','font','strikeThrough',true),('Home','font','subscript',true),('Home','font','superscript',true),('Home','font','textEffects',true),('Home','font','highlightColor',true),('Home','font','fontColor',true),
 ('Home','paragraph','bullets',true),('Home','paragraph','numbering',true),('Home','paragraph','multilevelList',true),('Home','paragraph','decreaseIndent',true),('Home','paragraph','increaseIndent',true),('Home','paragraph','sort',true),('Home','paragraph','formattingMarks',true),('Home','paragraph','alignLeft',true),('Home','paragraph','alignCenter',true),('Home','paragraph','alignRight',true),('Home','paragraph','justify',true),('Home','paragraph','lineSpacing',true),('Home','paragraph','shading',true),('Home','paragraph','borders',true),
 ('Home','editing','find',true),('Home','editing','replace',true),('Home','editing','selectAll',true),
 ('Insert','pages','coverPage',true),('Insert','pages','blankPage',true),('Insert','pages','pageBreak',true),('Insert','tables','insertTable',true),
 ('Insert','illustrations','insertPicture',true),('Insert','illustrations','onlinePictures',true),('Insert','illustrations','shapes',true),
 ('Insert','links','hyperlink',true),('Insert','links','bookmark',true),('Insert','links','crossReference',true),('Insert','headerFooter','header',true),('Insert','headerFooter','footer',true),('Insert','headerFooter','pageNumber',true),
 ('Insert','text','dropCap',true),('Insert','text','dateTime',true),('Insert','symbols','symbol',true),
 ('Design','pageBackground','watermark',true),('Design','pageBackground','pageColor',true),('Design','pageBackground','pageBorders',true),
 ('Page Layout','pageSetup','margins',true),('Page Layout','pageSetup','orientation',true),('Page Layout','pageSetup','pageSize',true),('Page Layout','pageSetup','columns',true),('Page Layout','pageSetup','sectionBreak',true),('Page Layout','pageSetup','lineNumbers',true),
 ('View','views','fullScreenReading',true),('View','views','printLayout',true),('View','views','webLayout',true),('View','views','outlineView',true),('View','views','draftView',true),('View','show','ruler',true),('View','show','gridlines',true),('View','show','documentMap',true),('View','zoom','zoom100',true),('View','zoom','onePage',true),('View','zoom','twoPages',true)
),groups as(select tab_name,group_name,jsonb_build_object('enabled',true,'options',jsonb_object_agg(command_name,to_jsonb(supported)order by command_name))body from commands group by tab_name,group_name),tabs as(select tab_name,jsonb_build_object('enabled',true,'groups',jsonb_object_agg(group_name,body order by group_name))body from groups group by tab_name)
select jsonb_build_object('schemaVersion','2','tabs',jsonb_build_object('File',jsonb_build_object('enabled',true,'groups','{}'::jsonb))||jsonb_object_agg(tab_name,body order by case tab_name when'Home'then 2 when'Insert'then 3 when'Design'then 4 when'Page Layout'then 5 else 6 end),'fonts',jsonb_build_array('Calibri (Body)','Calibri','Arial','Times New Roman','Mangal'),'fontSizeMin',8,'fontSizeMax',72)from tabs
$$;

create or replace function public.normalize_word_efficiency_editor_capabilities(c jsonb)
returns jsonb language plpgsql immutable set search_path=pg_catalog,public as $$
declare result jsonb:=public.word_efficiency_default_editor_capabilities();tab_name text;group_name text;option_name text;legacy_command text;old_tabs jsonb;old_commands jsonb;
begin
 if c is null or jsonb_typeof(c)<>'object'then return result;end if;
 if c->>'schemaVersion'='2'then return c;end if;
 old_tabs:=coalesce(c->'tabs','[]'::jsonb);old_commands:=coalesce(c->'commands','[]'::jsonb);
 for tab_name in select key_rows.key_name from jsonb_object_keys(result->'tabs')as key_rows(key_name)loop result:=jsonb_set(result,array['tabs',tab_name,'enabled'],to_jsonb(old_tabs?tab_name));for group_name in select key_rows.key_name from jsonb_object_keys(result#>array['tabs',tab_name,'groups'])as key_rows(key_name)loop result:=jsonb_set(result,array['tabs',tab_name,'groups',group_name,'enabled'],to_jsonb(old_tabs?tab_name));for option_name in select key_rows.key_name from jsonb_object_keys(result#>array['tabs',tab_name,'groups',group_name,'options'])as key_rows(key_name)loop legacy_command:=case option_name when'bullets'then'insertUnorderedList'when'numbering'then'insertOrderedList'when'decreaseIndent'then'outdent'when'increaseIndent'then'indent'when'alignLeft'then'justifyLeft'when'alignCenter'then'justifyCenter'when'alignRight'then'justifyRight'when'justify'then'justifyFull'when'clearCharacterFormatting'then'removeFormat'when'clearParagraphFormatting'then'removeFormat'when'clearSelectionFormatting'then'removeFormat'when'replace'then'findReplace'when'reviewReplace'then'findReplace'else option_name end;result:=jsonb_set(result,array['tabs',tab_name,'groups',group_name,'options',option_name],to_jsonb((old_commands?legacy_command)and coalesce((result#>>array['tabs',tab_name,'groups',group_name,'options',option_name])::boolean,false)));end loop;end loop;end loop;
 result:=jsonb_set(result,'{fonts}',case when jsonb_typeof(c->'fonts')='array'then c->'fonts'else result->'fonts'end);result:=jsonb_set(result,'{fontSizeMin}',coalesce(c->'fontSizeMin',result->'fontSizeMin'));result:=jsonb_set(result,'{fontSizeMax}',coalesce(c->'fontSizeMax',result->'fontSizeMax'));return result;
end $$;

create or replace function public.normalize_new_word_efficiency_version_capabilities()
returns trigger language plpgsql set search_path=pg_catalog,public as $$begin new.editor_capabilities:=public.normalize_word_efficiency_editor_capabilities(new.editor_capabilities);perform public.assert_word_efficiency_editor_capabilities(new.editor_capabilities);return new;end $$;
drop trigger if exists normalize_new_word_efficiency_version_capabilities on public.word_efficiency_versions;
create trigger normalize_new_word_efficiency_version_capabilities before insert on public.word_efficiency_versions for each row execute function public.normalize_new_word_efficiency_version_capabilities();

create or replace function public.word_efficiency_command_enabled(c jsonb,command_name text)
returns boolean language sql immutable set search_path=pg_catalog,public as $$select exists(select 1 from jsonb_each(c->'tabs')as tab_entries(tab_name,tab_value)join lateral jsonb_each(tab_entries.tab_value->'groups')as group_entries(group_name,group_value)on true join lateral jsonb_each(group_entries.group_value->'options')as option_entries(option_name,option_value)on true where option_entries.option_name=command_name and(tab_entries.tab_value->>'enabled')::boolean and(group_entries.group_value->>'enabled')::boolean and(option_entries.option_value#>>'{}')::boolean)$$;

-- Schema-v2 capability objects are exact. Legacy flat objects are normalized only
-- while preparing/validating an attempt; immutable version rows are never updated.
create or replace function public.assert_word_efficiency_editor_capabilities(c jsonb)
returns void language plpgsql immutable set search_path=pg_catalog,public as $$
declare allowed jsonb:=public.word_efficiency_default_editor_capabilities();tab_name text;group_name text;option_name text;
begin
 if c->>'schemaVersion'is distinct from'2'then if c is null or jsonb_typeof(c)<>'object'or not(c?&array['tabs','commands','fonts','fontSizeMin','fontSizeMax','clipboard','findReplace','tables','pageLayout','pause'])or exists(select 1 from jsonb_object_keys(c)as capability_keys(key_name)where capability_keys.key_name<>all(array['tabs','commands','fonts','fontSizeMin','fontSizeMax','clipboard','findReplace','tables','pageLayout','pause']))then raise exception'Legacy editor capability schema is invalid';end if;c:=public.normalize_word_efficiency_editor_capabilities(c);end if;
 if c is null or jsonb_typeof(c)<>'object'or pg_column_size(c)>131072 or c->>'schemaVersion'<>'2'or not(c?&array['schemaVersion','tabs','fonts','fontSizeMin','fontSizeMax'])or exists(select 1 from jsonb_object_keys(c)as capability_keys(key_name)where capability_keys.key_name<>all(array['schemaVersion','tabs','fonts','fontSizeMin','fontSizeMax','pause']))then raise exception'Editor capability schema is invalid';end if;
 if c?'pause'and c->'pause'<>to_jsonb(false)then raise exception'Pause is not supported';end if;
 if jsonb_typeof(c->'tabs')<>'object'or(select count(*)from jsonb_object_keys(c->'tabs'))<>6 or exists(select 1 from jsonb_object_keys(c->'tabs')as tab_keys(key_name)where not((allowed->'tabs')?tab_keys.key_name))then raise exception'Unknown editor tab';end if;
 for tab_name in select tab_keys.key_name from jsonb_object_keys(allowed->'tabs')as tab_keys(key_name)loop
  if not((c->'tabs')?tab_name)or jsonb_typeof(c#>array['tabs',tab_name])<>'object'or exists(select 1 from jsonb_object_keys(c#>array['tabs',tab_name])as tab_field_keys(key_name)where tab_field_keys.key_name<>all(array['enabled','groups']))or jsonb_typeof(c#>array['tabs',tab_name,'enabled'])<>'boolean'or jsonb_typeof(c#>array['tabs',tab_name,'groups'])<>'object'or(select count(*)from jsonb_object_keys(c#>array['tabs',tab_name,'groups']))<>(select count(*)from jsonb_object_keys(allowed#>array['tabs',tab_name,'groups']))then raise exception'Malformed editor tab %',tab_name;end if;
  if exists(select 1 from jsonb_object_keys(c#>array['tabs',tab_name,'groups'])as group_keys(key_name)where not((allowed#>array['tabs',tab_name,'groups'])?group_keys.key_name))then raise exception'Unknown editor group';end if;
  for group_name in select group_keys.key_name from jsonb_object_keys(allowed#>array['tabs',tab_name,'groups'])as group_keys(key_name)loop
   if not((c#>array['tabs',tab_name,'groups'])?group_name)or jsonb_typeof(c#>array['tabs',tab_name,'groups',group_name])<>'object'or exists(select 1 from jsonb_object_keys(c#>array['tabs',tab_name,'groups',group_name])as group_field_keys(key_name)where group_field_keys.key_name<>all(array['enabled','options']))or jsonb_typeof(c#>array['tabs',tab_name,'groups',group_name,'enabled'])<>'boolean'or jsonb_typeof(c#>array['tabs',tab_name,'groups',group_name,'options'])<>'object'or(select count(*)from jsonb_object_keys(c#>array['tabs',tab_name,'groups',group_name,'options']))<>(select count(*)from jsonb_object_keys(allowed#>array['tabs',tab_name,'groups',group_name,'options']))then raise exception'Malformed editor group';end if;
   if exists(select 1 from jsonb_object_keys(c#>array['tabs',tab_name,'groups',group_name,'options'])as option_keys(key_name)where not((allowed#>array['tabs',tab_name,'groups',group_name,'options'])?option_keys.key_name))then raise exception'Unknown editor option';end if;
   for option_name in select option_keys.key_name from jsonb_object_keys(allowed#>array['tabs',tab_name,'groups',group_name,'options'])as option_keys(key_name)loop
    if jsonb_typeof(c#>array['tabs',tab_name,'groups',group_name,'options',option_name])<>'boolean'then raise exception'Malformed editor option';end if;
    if(c#>>array['tabs',tab_name,'groups',group_name,'options',option_name])::boolean and not(allowed#>>array['tabs',tab_name,'groups',group_name,'options',option_name])::boolean then raise exception'Unsupported editor command %',option_name;end if;
   end loop;
  end loop;
 end loop;
 if jsonb_typeof(c->'fonts')<>'array'or jsonb_array_length(c->'fonts')not between 1 and 6 or exists(select 1 from jsonb_array_elements(c->'fonts')as font_values(font_value)where jsonb_typeof(font_values.font_value)<>'string'or font_values.font_value#>>'{}'<>all(array['Calibri (Body)','Calibri','Arial','Times New Roman','Mangal','Kruti Dev 010']))or jsonb_array_length(c->'fonts')<>(select count(distinct font_values.font_value#>>'{}')from jsonb_array_elements(c->'fonts')as font_values(font_value))then raise exception'Unknown or duplicate editor font';end if;
 if jsonb_typeof(c->'fontSizeMin')<>'number'or jsonb_typeof(c->'fontSizeMax')<>'number'or(c->>'fontSizeMin')::numeric<>trunc((c->>'fontSizeMin')::numeric)or(c->>'fontSizeMax')::numeric<>trunc((c->>'fontSizeMax')::numeric)or(c->>'fontSizeMin')::numeric<8 or(c->>'fontSizeMax')::numeric>72 or(c->>'fontSizeMin')::numeric>(c->>'fontSizeMax')::numeric then raise exception'Editor font-size range is invalid';end if;
end $$;

create or replace function public.word_efficiency_initial_editor_document(m jsonb)
returns jsonb language plpgsql immutable set search_path=pg_catalog,public as $$
declare blocks jsonb;
begin
 if jsonb_typeof(m->'blocks')='array'then return m;end if;
 if jsonb_typeof(m->'paragraphs')<>'array'then raise exception'Attempt original document cannot be converted';end if;
 select jsonb_agg(jsonb_build_object('id','block-'||(paragraph_entries.ordinality-1),'type',case when paragraph_entries.value->>'type'='list-item'then'list-item'else'paragraph'end,'alignment',paragraph_entries.value->>'alignment','runs',(select jsonb_agg(jsonb_build_object('text',run_entries.value->>'text','bold',(run_entries.value->>'bold')::boolean,'italic',(run_entries.value->>'italic')::boolean,'underline',(run_entries.value->>'underline')::boolean,'strike',(run_entries.value->>'strike')::boolean,'superscript',false,'subscript',false,'fontFamily',run_entries.value->'fontFamily','fontSize',run_entries.value->'fontSize','color',run_entries.value->'color','highlight',run_entries.value->'highlight')order by run_entries.ordinality)from jsonb_array_elements(paragraph_entries.value->'runs')with ordinality as run_entries(value,ordinality)))order by paragraph_entries.ordinality)into blocks from jsonb_array_elements(m->'paragraphs')with ordinality as paragraph_entries(value,ordinality);
 return jsonb_build_object('schemaVersion','1','blocks',blocks,'savedAt','1970-01-01T00:00:00.000Z');
end $$;

create or replace function public.assert_word_efficiency_document_schema(d jsonb,caps jsonb)
returns void language plpgsql immutable set search_path=pg_catalog,public as $$
declare block_value jsonb;run_value jsonb;document_version text;block_ids text[]:='{}';block_id text;run_count integer:=0;text_count bigint:=0;image_count integer:=0;image_bytes bigint:=0;image_payload text;field_name text;
begin
 if d is null or jsonb_typeof(d)<>'object'or pg_column_size(d)>2097152 then raise exception'Document snapshot must be a bounded JSON object';end if;document_version:=d->>'schemaVersion';if document_version not in('1','2')then raise exception'Document schema/version is incompatible';end if;
 if document_version='1'then if not(d?&array['schemaVersion','blocks','savedAt'])or exists(select 1 from jsonb_object_keys(d)as document_keys(key_name)where document_keys.key_name<>all(array['schemaVersion','blocks','savedAt']))then raise exception'Unknown schema-v1 document field';end if;else if not(d?&array['schemaVersion','blocks','pageLayout','operations','savedAt'])or exists(select 1 from jsonb_object_keys(d)as document_keys(key_name)where document_keys.key_name<>all(array['schemaVersion','blocks','pageLayout','operations','savedAt']))then raise exception'Unknown schema-v2 document field';end if;end if;
 if jsonb_typeof(d->'blocks')<>'array'or jsonb_array_length(d->'blocks')not between 1 and 1000 or jsonb_typeof(d->'savedAt')<>'string'or length(d->>'savedAt')>64 or(d->>'savedAt')::timestamptz is null then raise exception'Document snapshot content is invalid';end if;
 if document_version='2'then
  if jsonb_typeof(d->'operations')<>'array'or jsonb_array_length(d->'operations')>256 or exists(select 1 from jsonb_array_elements(d->'operations')as operation_values(operation_value)where jsonb_typeof(operation_values.operation_value)<>'string'or not public.word_efficiency_command_enabled(public.word_efficiency_default_editor_capabilities(),operation_values.operation_value#>>'{}'))or jsonb_array_length(d->'operations')<>(select count(distinct operation_values.operation_value#>>'{}')from jsonb_array_elements(d->'operations')as operation_values(operation_value))then raise exception'Invalid editor operation history';end if;
  if jsonb_typeof(d->'pageLayout')<>'object'or not(d->'pageLayout'?&array['padding','maxWidth','aspectRatio','columnCount','backgroundColor','border','watermark'])or exists(select 1 from jsonb_object_keys(d->'pageLayout')as layout_keys(key_name)where layout_keys.key_name<>all(array['padding','maxWidth','aspectRatio','columnCount','backgroundColor','border','watermark']))then raise exception'Invalid page layout fields';end if;
  foreach field_name in array array['padding','maxWidth','aspectRatio','columnCount','backgroundColor','border','watermark']loop if jsonb_typeof(d->'pageLayout'->field_name)not in('string','null')or(jsonb_typeof(d->'pageLayout'->field_name)='string'and length(d->'pageLayout'->>field_name)>case when field_name='watermark'then 40 else 100 end)then raise exception'Invalid page layout value %',field_name;end if;end loop;
  if jsonb_typeof(d#>'{pageLayout,padding}')='string'and d#>>'{pageLayout,padding}'!~'^\d{1,2}(\.\d{1,2})?mm$'then raise exception'Invalid page margins';end if;if jsonb_typeof(d#>'{pageLayout,columnCount}')='string'and d#>>'{pageLayout,columnCount}'!~'^[1-3]$'then raise exception'Invalid page columns';end if;if jsonb_typeof(d#>'{pageLayout,backgroundColor}')='string'and d#>>'{pageLayout,backgroundColor}'!~'^#?[0-9A-Fa-f]{6}$'then raise exception'Invalid page color';end if;
 end if;
 for block_value in select block_values.value from jsonb_array_elements(d->'blocks')as block_values(value)loop
  if jsonb_typeof(block_value)<>'object'or not(block_value?&array['id','type','alignment','runs'])or exists(select 1 from jsonb_object_keys(block_value)as block_keys(key_name)where block_keys.key_name<>all(case when document_version='1'then array['id','type','alignment','runs']else array['id','type','alignment','runs','attrs']end))then raise exception'Unknown document block field';end if;
  block_id:=block_value->>'id';if jsonb_typeof(block_value->'id')<>'string'or block_id!~'^[A-Za-z0-9][A-Za-z0-9._:-]{0,99}$'or block_id=any(block_ids)then raise exception'Invalid or duplicate document block ID';end if;block_ids:=array_append(block_ids,block_id);
  if jsonb_typeof(block_value->'type')<>'string'or(document_version='1'and block_value->>'type'not in('paragraph','list-item','table-cell','page-break'))or(document_version='2'and block_value->>'type'not in('paragraph','list-item','table','image','page-break','section-break','cover-page','header','footer','shape'))or jsonb_typeof(block_value->'alignment')<>'string'or block_value->>'alignment'not in('left','center','right','justify')or jsonb_typeof(block_value->'runs')<>'array'or jsonb_array_length(block_value->'runs')not between 1 and 500 then raise exception'Invalid document block';end if;
  if document_version='2'then
   if jsonb_typeof(block_value->'attrs')<>'object'then raise exception'Invalid document attributes';end if;
   if block_value->>'type'='table'then if exists(select 1 from jsonb_object_keys(block_value->'attrs')as attribute_keys(key_name)where attribute_keys.key_name<>'rows')or jsonb_typeof(block_value#>'{attrs,rows}')<>'array'or jsonb_array_length(block_value#>'{attrs,rows}')not between 1 and 50 or exists(select 1 from jsonb_array_elements(block_value#>'{attrs,rows}')as table_rows(row_value)where jsonb_typeof(table_rows.row_value)<>'array'or jsonb_array_length(table_rows.row_value)not between 1 and 20 or exists(select 1 from jsonb_array_elements(table_rows.row_value)as table_cells(cell_value)where jsonb_typeof(table_cells.cell_value)<>'string'or length(table_cells.cell_value#>>'{}')>10000))then raise exception'Invalid table attributes';end if;
   elsif block_value->>'type'='image'then if not(block_value->'attrs'?&array['src','alt','width','height','localAsset'])or exists(select 1 from jsonb_object_keys(block_value->'attrs')as attribute_keys(key_name)where attribute_keys.key_name<>all(array['src','alt','width','height','localAsset']))or jsonb_typeof(block_value#>'{attrs,src}')<>'string'or jsonb_typeof(block_value#>'{attrs,alt}')<>'string'or length(block_value#>>'{attrs,alt}')>200 or jsonb_typeof(block_value#>'{attrs,width}')<>'number'or jsonb_typeof(block_value#>'{attrs,height}')<>'number'or(block_value#>>'{attrs,width}')::numeric<>trunc((block_value#>>'{attrs,width}')::numeric)or(block_value#>>'{attrs,height}')::numeric<>trunc((block_value#>>'{attrs,height}')::numeric)or(block_value#>>'{attrs,width}')::integer not between 1 and 6000 or(block_value#>>'{attrs,height}')::integer not between 1 and 6000 or jsonb_typeof(block_value#>'{attrs,localAsset}')<>'boolean'then raise exception'Invalid image attributes';end if;image_payload:=block_value#>>'{attrs,src}';if image_payload='asset:samradhi-mark'then if not(block_value#>>'{attrs,localAsset}')::boolean then raise exception'Invalid local asset';end if;else if image_payload!~'^data:image/(png|jpeg|webp|gif);base64,[A-Za-z0-9+/]+={0,2}$'then raise exception'Unsafe embedded image';end if;begin image_bytes:=image_bytes+octet_length(decode(split_part(image_payload,',',2),'base64'));exception when others then raise exception'Malformed embedded image';end;if octet_length(decode(split_part(image_payload,',',2),'base64'))>524288 then raise exception'Embedded image is too large';end if;end if;image_count:=image_count+1;if image_count>20 or image_bytes>1048576 then raise exception'Embedded image count or total size exceeds limit';end if;
   elsif block_value->>'type'in('page-break','section-break')then if exists(select 1 from jsonb_object_keys(block_value->'attrs')as attribute_keys(key_name)where attribute_keys.key_name<>'kind')or jsonb_typeof(block_value#>'{attrs,kind}')<>'string'or block_value#>>'{attrs,kind}'not in('page','blank-page','section-next-page','section-continuous')then raise exception'Invalid break attributes';end if;
   else if exists(select 1 from jsonb_object_keys(block_value->'attrs')as attribute_keys(key_name)where attribute_keys.key_name<>all(case when block_value->>'type'='paragraph'then array['marginLeft','marginRight','lineHeight','marginTop','marginBottom','border','backgroundColor','hyphens','lineNumbers','dropCap']when block_value->>'type'='list-item'then array['marginLeft','marginRight','lineHeight','marginTop','marginBottom','border','backgroundColor','hyphens','listStyle']else array['marginLeft','marginRight','lineHeight','marginTop','marginBottom','border','backgroundColor','hyphens']end))then raise exception'Unknown block attribute';end if;if block_value->>'type'='paragraph'and((block_value->'attrs'?'lineNumbers'and jsonb_typeof(block_value#>'{attrs,lineNumbers}')<>'boolean')or(block_value->'attrs'?'dropCap'and jsonb_typeof(block_value#>'{attrs,dropCap}')<>'boolean'))then raise exception'Invalid paragraph attribute';end if;if block_value->>'type'='list-item'and(jsonb_typeof(block_value#>'{attrs,listStyle}')<>'string'or block_value#>>'{attrs,listStyle}'not in('bullet','decimal','upper-roman'))then raise exception'Invalid list attributes';end if;end if;
  end if;
  for run_value in select run_values.value from jsonb_array_elements(block_value->'runs')as run_values(value)loop
   run_count:=run_count+1;if run_count>20000 or jsonb_typeof(run_value)<>'object'or not(run_value?&array['text','bold','italic','underline','strike','superscript','subscript','fontFamily','fontSize','color','highlight'])or exists(select 1 from jsonb_object_keys(run_value)as run_keys(key_name)where run_keys.key_name<>all(case when document_version='1'then array['text','bold','italic','underline','strike','superscript','subscript','fontFamily','fontSize','color','highlight']else array['text','bold','italic','underline','strike','superscript','subscript','fontFamily','fontSize','color','highlight','doubleStrike','href','bookmark','field']end))then raise exception'Unknown document run field';end if;
   if document_version='2'and(not(run_value?&array['doubleStrike','href','bookmark','field'])or jsonb_typeof(run_value->'doubleStrike')<>'boolean'or jsonb_typeof(run_value->'href')not in('string','null')or jsonb_typeof(run_value->'bookmark')not in('string','null')or jsonb_typeof(run_value->'field')not in('string','null'))then raise exception'Invalid schema-v2 run metadata';end if;
   if jsonb_typeof(run_value->'text')<>'string'or length(run_value->>'text')>200000 then raise exception'Invalid run text';end if;text_count:=text_count+length(run_value->>'text');if text_count>1000000 then raise exception'Document text is too large';end if;foreach field_name in array array['bold','italic','underline','strike','superscript','subscript']loop if jsonb_typeof(run_value->field_name)<>'boolean'then raise exception'Invalid run mark';end if;end loop;
   if jsonb_typeof(run_value->'fontFamily')not in('string','null')or(jsonb_typeof(run_value->'fontFamily')='string'and(not((caps->'fonts')?(run_value->>'fontFamily'))or run_value->>'fontFamily'<>all(array['Calibri (Body)','Arial','Calibri','Times New Roman','Mangal','Kruti Dev 010'])))then raise exception'Disabled or unknown document font';end if;if jsonb_typeof(run_value->'fontSize')not in('number','null')or(jsonb_typeof(run_value->'fontSize')='number'and((run_value->>'fontSize')::numeric<(caps->>'fontSizeMin')::numeric or(run_value->>'fontSize')::numeric>(caps->>'fontSizeMax')::numeric))then raise exception'Document font size is outside capability bounds';end if;if jsonb_typeof(run_value->'color')not in('string','null')or(jsonb_typeof(run_value->'color')='string'and run_value->>'color'!~'^[0-9A-Fa-f]{6}$')or jsonb_typeof(run_value->'highlight')not in('string','null')or(jsonb_typeof(run_value->'highlight')='string'and run_value->>'highlight'!~'^(?:[0-9A-Fa-f]{6}|[A-Za-z]{1,30})$')then raise exception'Invalid run color';end if;
   if document_version='2'and jsonb_typeof(run_value->'href')='string'and(run_value->>'href'!~'^(https?://[^[:space:]]+|mailto:[^[:space:]@]+@[^[:space:]@]+|#bookmark-[A-Za-z0-9_-]{1,50})$'or run_value->>'href'~'^//')then raise exception'Unsafe hyperlink protocol';end if;if document_version='2'and jsonb_typeof(run_value->'bookmark')='string'and run_value->>'bookmark'!~'^[A-Za-z0-9_-]{1,50}$'then raise exception'Invalid bookmark';end if;if document_version='2'and jsonb_typeof(run_value->'field')='string'and run_value->>'field'not in('page-number','date-time','symbol','special-character')then raise exception'Invalid document field';end if;
  end loop;
 end loop;
end $$;

create or replace function public.word_efficiency_document_feature(d jsonb,f text)
returns jsonb language plpgsql immutable set search_path=pg_catalog,public as $$
declare result jsonb;
begin
 if f like'page:%'then return coalesce(d#>array['pageLayout',substr(f,6)],'null'::jsonb);end if;
 if f like'alignment:%'then select coalesce(jsonb_object_agg(b->>'id',to_jsonb((b->>'alignment')=substr(f,11))order by b->>'id'),'{}'::jsonb)into result from jsonb_array_elements(d->'blocks')b;return result;end if;
 if f like'list:%'then select coalesce(jsonb_object_agg(b->>'id',to_jsonb((b#>>'{attrs,listStyle}')=substr(f,6))order by b->>'id')filter(where b->>'type'='list-item'),'{}'::jsonb)into result from jsonb_array_elements(d->'blocks')b;return result;end if;
 if f like'type:%'then select coalesce(jsonb_object_agg(b->>'id',to_jsonb(b->>'type')order by b->>'id')filter(where b->>'type'=substr(f,6)),'{}'::jsonb)into result from jsonb_array_elements(d->'blocks')b;return result;end if;
 if f in('alignment','attrs','marginLeft','marginRight','lineHeight','marginTop','marginBottom','border','backgroundColor','hyphens','lineNumbers','dropCap','listStyle','rows','src','kind')then select coalesce(jsonb_object_agg(b->>'id',case when f='alignment'then b->'alignment'when f='attrs'then b->'attrs'else coalesce(b#>array['attrs',f],'null'::jsonb)end order by b->>'id'),'{}'::jsonb)into result from jsonb_array_elements(d->'blocks')b;return result;end if;
 select coalesce(jsonb_object_agg(b->>'id',(select jsonb_agg(case f when'bold'then coalesce(r->'bold','false'::jsonb)when'italic'then coalesce(r->'italic','false'::jsonb)when'underline'then coalesce(r->'underline','false'::jsonb)when'strike'then coalesce(r->'strike','false'::jsonb)when'doubleStrike'then coalesce(r->'doubleStrike','false'::jsonb)when'superscript'then coalesce(r->'superscript','false'::jsonb)when'subscript'then coalesce(r->'subscript','false'::jsonb)when'href:external'then case when coalesce(r->>'href','')~'^(https?://|mailto:)'then r->'href'else'null'::jsonb end when'href:internal'then case when coalesce(r->>'href','')~'^#bookmark-'then r->'href'else'null'::jsonb end else coalesce(r->f,'null'::jsonb)end order by ordinality)from jsonb_array_elements(b->'runs')with ordinality x(r,ordinality))order by b->>'id'),'{}'::jsonb)into result from jsonb_array_elements(d->'blocks')b;return result;
end $$;

create or replace function public.assert_word_efficiency_capability_changes(d jsonb,baseline jsonb,caps jsonb)
returns void language plpgsql immutable set search_path=pg_catalog,public as $$
declare op jsonb;rule record;enabled boolean;
begin
 if d->>'schemaVersion'='2'then for op in select value from jsonb_array_elements(d->'operations')loop if not public.word_efficiency_command_enabled(caps,op#>>'{}')then raise exception'Disabled editor command %',op#>>'{}';end if;end loop;end if;
 for rule in select * from(values
  ('bold',array['bold']),('italic',array['italic']),('underline',array['underline']),('strike',array['strikeThrough']),('doubleStrike',array['textEffects']),('superscript',array['superscript']),('subscript',array['subscript']),('fontFamily',array['fontName']),('fontSize',array['fontSize','increaseFontSize','decreaseFontSize']),('color',array['fontColor']),('highlight',array['highlightColor']),('alignment:left',array['alignLeft']),('alignment:center',array['alignCenter']),('alignment:right',array['alignRight']),('alignment:justify',array['justify']),('list:bullet',array['bullets']),('list:decimal',array['numbering']),('list:upper-roman',array['multilevelList']),('marginLeft',array['increaseIndent','decreaseIndent']),('marginRight',array[]::text[]),('lineHeight',array['lineSpacing']),('marginTop',array[]::text[]),('marginBottom',array[]::text[]),('backgroundColor',array['shading']),('border',array['borders']),('hyphens',array[]::text[]),('lineNumbers',array['lineNumbers']),('dropCap',array['dropCap']),('href:external',array['hyperlink']),('href:internal',array['crossReference']),('bookmark',array['bookmark']),('field',array['pageNumber','dateTime','symbol']),('type:cover-page',array['coverPage']),('type:shape',array['shapes']),('type:header',array['header']),('type:footer',array['footer']),('type:section-break',array['sectionBreak']),('page:padding',array['margins']),('page:aspectRatio',array['orientation']),('page:maxWidth',array['pageSize']),('page:columnCount',array['columns']),('page:backgroundColor',array['pageColor']),('page:watermark',array['watermark']),('page:border',array['pageBorders'])
 )as rules(feature,commands)loop
  if public.word_efficiency_document_feature(d,rule.feature)is distinct from public.word_efficiency_document_feature(baseline,rule.feature)then select coalesce(bool_or(public.word_efficiency_command_enabled(caps,c)),false)into enabled from unnest(rule.commands)c;if not enabled then raise exception'Disabled capability changed document feature %',rule.feature;end if;end if;
 end loop;
 if public.word_efficiency_document_feature(d,'type:table')is distinct from public.word_efficiency_document_feature(baseline,'type:table')or public.word_efficiency_document_feature(d,'rows')is distinct from public.word_efficiency_document_feature(baseline,'rows')then if not public.word_efficiency_command_enabled(caps,'insertTable')then raise exception'Disabled table capability';end if;end if;
 if public.word_efficiency_document_feature(d,'type:image')is distinct from public.word_efficiency_document_feature(baseline,'type:image')or public.word_efficiency_document_feature(d,'src')is distinct from public.word_efficiency_document_feature(baseline,'src')then if not public.word_efficiency_command_enabled(caps,'insertPicture')and not public.word_efficiency_command_enabled(caps,'onlinePictures')then raise exception'Disabled image capability';end if;end if;
 if public.word_efficiency_document_feature(d,'type:page-break')is distinct from public.word_efficiency_document_feature(baseline,'type:page-break')or public.word_efficiency_document_feature(d,'kind')is distinct from public.word_efficiency_document_feature(baseline,'kind')then if not public.word_efficiency_command_enabled(caps,'pageBreak')and not public.word_efficiency_command_enabled(caps,'blankPage')then raise exception'Disabled page break capability';end if;end if;
end $$;

create or replace function public.assert_word_efficiency_edited_document(d jsonb,v uuid)
returns void language plpgsql stable security definer set search_path=pg_catalog,public as $$declare caps jsonb;begin select public.normalize_word_efficiency_editor_capabilities(editor_capabilities)into caps from public.word_efficiency_versions where id=v;if not found then raise exception'Unknown test version';end if;perform public.assert_word_efficiency_editor_capabilities(caps);perform public.assert_word_efficiency_document_schema(d,caps);end $$;

create or replace function public.initialize_word_efficiency_document(p_attempt_id uuid,p_show_questions boolean)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare matter jsonb;caps jsonb;original jsonb;initial_editor jsonb;
begin
 if not public.is_active_word_efficiency_student()then raise exception'active student account required';end if;select v.working_matter_snapshot,public.normalize_word_efficiency_editor_capabilities(v.editor_capabilities),a.original_document_snapshot into matter,caps,original from public.word_efficiency_attempts a join public.word_efficiency_versions v on v.id=a.version_id where a.id=p_attempt_id and a.student_id=auth.uid()and a.status='prepared'for update of a;if not found then raise exception'attempt unavailable';end if;if original is not null then return original;end if;perform public.assert_word_efficiency_working_matter(matter);perform public.assert_word_efficiency_editor_capabilities(caps);initial_editor:=public.word_efficiency_initial_editor_document(matter);perform public.assert_word_efficiency_document_schema(initial_editor,caps);update public.word_efficiency_attempts set original_document_snapshot=coalesce(original_document_snapshot,matter),document_autosave=null,snapshot=coalesce(snapshot,'{}'::jsonb)||jsonb_build_object('working_matter',matter,'editor_capabilities',caps,'initial_editor_document',initial_editor,'show_questions',coalesce(p_show_questions,false)),updated_at=now()where id=p_attempt_id and student_id=auth.uid()and status='prepared'and original_document_snapshot is null;return matter;
end $$;

create or replace function public.autosave_word_efficiency_document(p_attempt_id uuid,p_document jsonb)
returns void language plpgsql security definer set search_path=pg_catalog,public as $$declare a public.word_efficiency_attempts%rowtype;caps jsonb;baseline jsonb;begin if not public.is_active_word_efficiency_student()then raise exception'active student account required';end if;select * into a from public.word_efficiency_attempts where id=p_attempt_id and student_id=auth.uid()for update;if not found or a.status<>'active'or a.started_at is null or a.final_document_snapshot is not null then raise exception'attempt unavailable';end if;if now()>a.started_at+make_interval(secs=>a.selected_duration_seconds)then raise exception'autosave deadline expired';end if;if a.original_document_snapshot is null then raise exception'attempt original document is invalid';end if;select public.normalize_word_efficiency_editor_capabilities(editor_capabilities)into caps from public.word_efficiency_versions where id=a.version_id;baseline:=coalesce(a.snapshot->'initial_editor_document',public.word_efficiency_initial_editor_document(a.original_document_snapshot));perform public.assert_word_efficiency_editor_capabilities(caps);perform public.assert_word_efficiency_document_schema(p_document,caps);perform public.assert_word_efficiency_document_schema(baseline,caps);perform public.assert_word_efficiency_capability_changes(p_document,baseline,caps);update public.word_efficiency_attempts set document_autosave=p_document,updated_at=now()where id=p_attempt_id and student_id=auth.uid()and final_document_snapshot is null;end $$;

create or replace function public.submit_word_efficiency_document(p_attempt_id uuid,p_document jsonb)
returns void language plpgsql security definer set search_path=pg_catalog,public as $$declare a public.word_efficiency_attempts%rowtype;caps jsonb;baseline jsonb;begin if not public.is_active_word_efficiency_student()then raise exception'active student account required';end if;select * into a from public.word_efficiency_attempts where id=p_attempt_id and student_id=auth.uid()for update;if not found or a.status<>'active'or a.started_at is null or a.final_document_snapshot is not null then raise exception'attempt unavailable or already submitted';end if;if now()>a.started_at+make_interval(secs=>a.selected_duration_seconds+300)then raise exception'submission grace expired';end if;if a.original_document_snapshot is null then raise exception'attempt original document is invalid';end if;select public.normalize_word_efficiency_editor_capabilities(editor_capabilities)into caps from public.word_efficiency_versions where id=a.version_id;baseline:=coalesce(a.snapshot->'initial_editor_document',public.word_efficiency_initial_editor_document(a.original_document_snapshot));if now()<=a.started_at+make_interval(secs=>a.selected_duration_seconds)then perform public.assert_word_efficiency_document_schema(p_document,caps);perform public.assert_word_efficiency_capability_changes(p_document,baseline,caps);else if a.document_autosave is null or p_document is distinct from a.document_autosave then raise exception'post-deadline submission must match the last valid autosave';end if;perform public.assert_word_efficiency_document_schema(a.document_autosave,caps);perform public.assert_word_efficiency_capability_changes(a.document_autosave,baseline,caps);p_document:=a.document_autosave;end if;update public.word_efficiency_attempts set document_autosave=p_document,final_document_snapshot=p_document,status='submitted',submitted_at=now(),updated_at=now()where id=p_attempt_id and student_id=auth.uid()and status='active'and final_document_snapshot is null;if not found then raise exception'attempt unavailable or already submitted';end if;end $$;

revoke all on function public.word_efficiency_default_editor_capabilities(),public.normalize_word_efficiency_editor_capabilities(jsonb),public.assert_word_efficiency_editor_capabilities(jsonb),public.normalize_new_word_efficiency_version_capabilities(),public.word_efficiency_command_enabled(jsonb,text),public.word_efficiency_initial_editor_document(jsonb),public.assert_word_efficiency_document_schema(jsonb,jsonb),public.word_efficiency_document_feature(jsonb,text),public.assert_word_efficiency_capability_changes(jsonb,jsonb,jsonb),public.assert_word_efficiency_edited_document(jsonb,uuid)from public,anon,authenticated;
grant execute on function public.assert_word_efficiency_edited_document(jsonb,uuid)to authenticated;
commit;
