begin;

-- Real, severe bug: every submitted Word Efficiency attempt scored 0/50
-- against version 4 of "Efficiency Test 1" regardless of what was actually
-- typed or formatted -- confirmed live across five different real
-- submissions, including ones authored to exactly match the model answer.
--
-- Root cause: word_efficiency_grading_target_value resolved a target like
-- "blocks.block-5.runs.0.bold" by searching the document's blocks array for
-- one whose `id` field equals "block-5" (`where block_value->>'id'=parts[2]`).
-- Block ids are NOT stable identifiers -- they're assigned fresh every time
-- toSnapshot() runs, either "matter-p-N" (the pristine, never-saved render,
-- N being that paragraph's position in the ORIGINAL working matter) or
-- "block-N" (N being that block's position in whatever snapshot was most
-- recently loaded via renderStructuredSnapshot -- i.e. only after at least
-- one save+reload round trip). Two independent editing sessions of the
-- "same" document -- the admin authoring the model answer, and any student
-- attempting the test -- essentially never assign the same id to the same
-- paragraph, even when every character and every formatting choice is
-- byte-for-byte identical. So `where block_value->>'id'=parts[2]` matched
-- nothing, `word_efficiency_grading_target_value` returned null for every
-- criterion on every attempt, and evaluate_word_efficiency_grading_rule's
-- `actual is not null and ... actual=expected_value` was never true.
--
-- Fix: address blocks by their ARRAY INDEX (position - 1) instead of their
-- id -- position is what diffWordDocuments already compares by internally
-- (before/after arrays walked strictly in parallel by index), and unlike an
-- id it doesn't depend on how many times either document happened to be
-- saved and reloaded. This migration only fixes the READ side (how a
-- target string is resolved against a document); the matching fix in
-- lib/word-document-diff.ts changes what target strings get GENERATED
-- going forward (blocks.<index>... instead of blocks.<id>...). Any grading
-- rule already saved with an id-based target is unrecoverable -- it must be
-- regenerated by re-authoring that question's Model Answer after this
-- ships, which also means going through Save (creating a fresh, unlocked
-- version) if the current version already has attempts against it.
create or replace function public.word_efficiency_grading_target_value(document jsonb,target text)
returns jsonb language plpgsql immutable set search_path=pg_catalog,public as $$
declare parts text[];value jsonb;segment text;index_value integer;
begin
 if document is null or target is null or target=''then return null;end if;
 parts:=string_to_array(target,'.');
 if parts[1]='pageLayout'then
  value:=document->'pageLayout';
  for i in 2..coalesce(array_length(parts,1),1)loop if value is null then return null;end if;value:=value->parts[i];end loop;
  return value;
 end if;
 if parts[1]<>'blocks'or coalesce(array_length(parts,1),0)<3 then return null;end if;
 if parts[2] !~ '^[0-9]+$' then return null; end if;
 value:=(coalesce(document->'blocks','[]'::jsonb))->(parts[2]::integer);
 for i in 3..array_length(parts,1)loop
  if value is null then return null;end if;
  segment:=parts[i];
  if jsonb_typeof(value)='array'and segment~'^[0-9]+$'then index_value:=segment::integer;value:=value->index_value;
  elsif jsonb_typeof(value)='object'then value:=value->segment;
  else return null;end if;
 end loop;
 return value;
end $$;

commit;
