"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import{createAdminClient}from"@/lib/supabase/admin";
import { calculateWordQuestionTotal,parseDurationOptions,parseWordQuestions,safePdfName,safeWordSlug,validatePdfUpload,validateWordDraft,type WordLanguage,type WordVersion } from "@/lib/word-efficiency";
import{detectPdfQuestions,looksLikeKrutiDevText}from"@/lib/word-pdf-extraction";
import{extractPdfTextPages,PdfReaderStartError}from"@/lib/word-pdf-server";
import{parseWorkingMatterDocx,validateWorkingMatterFile}from"@/lib/word-docx";
import{recommendedWordEditorCapabilities}from"@/lib/word-editor-capabilities";

const canonicalJson=(input:unknown):string=>Array.isArray(input)?`[${input.map(canonicalJson).join(",")}]`:input&&typeof input==="object"?`{${Object.entries(input as Record<string,unknown>).sort(([left],[right])=>left.localeCompare(right)).map(([key,item])=>`${globalThis.JSON.stringify(key)}:${canonicalJson(item)}`).join(",")}}`:globalThis.JSON.stringify(input);
const JSON={parse:globalThis.JSON.parse,stringify:canonicalJson};
const value=(form:FormData,key:string)=>String(form.get(key)??"").trim();
const refresh=(testId?:string)=>{revalidatePath("/admin/word-efficiency-tests");revalidatePath("/typing/word-efficiency");revalidatePath("/typing/word-efficiency/english");revalidatePath("/typing/word-efficiency/hindi");revalidatePath("/student/results");if(testId){revalidatePath(`/typing/word-efficiency/english/${testId}/instructions`);revalidatePath(`/typing/word-efficiency/hindi/${testId}/instructions`);revalidatePath(`/typing/word-efficiency/english/${testId}/workspace`);revalidatePath(`/typing/word-efficiency/hindi/${testId}/workspace`);revalidatePath(`/typing/word-efficiency/english/${testId}/question-paper`);revalidatePath(`/typing/word-efficiency/hindi/${testId}/question-paper`)}};
export async function saveWordEfficiencyTest(form:FormData){await requireAdmin();const supabase=await createClient();const testId=value(form,"testId")||null;const language:WordLanguage=value(form,"language")==="Hindi"?"Hindi":"English";const onscreen=form.get("deliveryOnscreen")==="on";const pdf=form.get("deliveryPdf")==="on";const realfile=form.get("deliveryRealFile")==="on";const removePdf=form.get("removePdf")==="on";let existing:Partial<WordVersion>={};if(testId){const {data:test}=await supabase.from("word_efficiency_tests").select("current_version_id").eq("id",testId).single();if(test?.current_version_id){const {data}=await supabase.from("word_efficiency_versions").select("pdf_path,pdf_file_name,pdf_size_bytes,pdf_page_count,pdf_uploaded_at").eq("id",test.current_version_id).single();existing=data??{}}}
  let pdfMeta=removePdf?{}:existing;const upload=form.get("pdfFile");if(pdf&&upload instanceof File&&upload.size){const checked=validatePdfUpload(upload);if(checked.errors.length)redirect(`/admin/word-efficiency-tests?error=${encodeURIComponent(checked.errors[0])}`);const bytes=new Uint8Array(await upload.arrayBuffer());if(new TextDecoder("latin1").decode(bytes.slice(0,5))!=="%PDF-")redirect("/admin/word-efficiency-tests?error=Invalid%20PDF%20file%20signature.");const decoded=new TextDecoder("latin1").decode(bytes);const pageCount=(decoded.match(/\/Type\s*\/Page\b/g)??[]).length||null;if(pageCount&&pageCount>100)redirect("/admin/word-efficiency-tests?error=PDF%20question%20papers%20may%20not%20exceed%20100%20pages.");const fileName=safePdfName(checked.name);const path=`${testId??crypto.randomUUID()}/${crypto.randomUUID()}-${fileName}`;const {error}=await supabase.storage.from("word-efficiency-pdfs").upload(path,bytes,{contentType:"application/pdf",upsert:false});if(error)redirect(`/admin/word-efficiency-tests?error=${encodeURIComponent(`PDF upload failed: ${error.message}`)}`);pdfMeta={pdf_path:path,pdf_file_name:fileName,pdf_size_bytes:bytes.byteLength,pdf_page_count:pageCount,pdf_uploaded_at:new Date().toISOString()}}
  const questions=parseWordQuestions(value(form,"questions"));const durations=parseDurationOptions(value(form,"durationOptions"));const passing=value(form,"passingMarks")?Number(value(form,"passingMarks")):null;let hasRealFileSource=false;try{const peek=value(form,"workingMatterSnapshot");const parsedPeek=peek?JSON.parse(peek):null;hasRealFileSource=parsedPeek?.source?.bucket==="word-efficiency-working-matter"}catch{}const draft={title:value(form,"title"),language,instructions:value(form,"instructions"),durations,questionCount:questions.length,maximumMarks:calculateWordQuestionTotal(questions),passingMarks:passing,onscreen,pdf,realfile,questions,hasPdf:Boolean(pdfMeta.pdf_path),hasRealFileSource};const errors=validateWordDraft(draft);if(errors.length)redirect(`/admin/word-efficiency-tests?error=${encodeURIComponent(errors[0])}`);
  const matterRaw=value(form,"workingMatterSnapshot");let workingMatter:Record<string,unknown>|null=null;const capabilities:Record<string,unknown>=recommendedWordEditorCapabilities();try{workingMatter=matterRaw?JSON.parse(matterRaw):null;if(workingMatter)workingMatter.schemaVersion="1"}catch(error){redirect(`/admin/word-efficiency-tests?error=${encodeURIComponent(error instanceof Error?error.message:"Working Matter is invalid")}`)};if(!workingMatter)redirect("/admin/word-efficiency-tests?error=Upload%20Working%20Matter%20DOCX%20before%20saving");const databaseQuestions=questions.map(({gradingRule:_,...question})=>question),payload={title:draft.title,slug:safeWordSlug(value(form,"slug")||draft.title),language,description:value(form,"description"),instructions_markdown:draft.instructions,delivery_onscreen:onscreen,delivery_pdf:pdf,delivery_realfile:realfile,question_count:draft.questionCount,maximum_marks:draft.maximumMarks,duration_options:durations,passing_marks:passing??"",questions:databaseQuestions,publish:value(form,"intent")==="publish",working_matter_snapshot:workingMatter,editor_capabilities:capabilities,...pdfMeta};const {data:savedId,error}=await supabase.rpc("save_word_efficiency_test",{p_test_id:testId,p_payload:payload});if(error||!savedId)redirect(`/admin/word-efficiency-tests?error=${encodeURIComponent(error?.message??"Unable to save test")}`);const{data:savedTest,error:testReadError}=await supabase.from("word_efficiency_tests").select("current_version_id").eq("id",savedId).single();const{data:savedVersion,error:versionReadError}=savedTest?.current_version_id?await supabase.from("word_efficiency_versions").select("editor_capabilities").eq("id",savedTest.current_version_id).single():{data:null,error:null};if(testReadError||versionReadError||!savedVersion||JSON.stringify(savedVersion.editor_capabilities)!==JSON.stringify(capabilities))redirect(`/admin/word-efficiency-tests?error=${encodeURIComponent("The test version was created, but its editor capabilities were not persisted exactly. Do not start new attempts; contact an administrator.")}`);const gradingRules=questions.flatMap(question=>question.gradingRule?[{questionNumber:question.number,exactTarget:question.gradingRule.target,expectedOperation:question.gradingRule.expectedOperation,expectedValue:question.gradingRule.expectedValue,allocatedMarks:question.gradingRule.allocatedMarks,partialMarks:question.gradingRule.partialMarks,additionalCriteria:question.gradingRule.additionalCriteria??[]}]:[]),{error:ruleError}=await supabase.rpc("save_word_efficiency_grading_rules",{p_version_id:savedTest.current_version_id,p_rules:gradingRules});if(ruleError)redirect(`/admin/word-efficiency-tests?error=${encodeURIComponent(`Test version saved, but grading rules failed: ${ruleError.message}`)}`);refresh();redirect("/admin/word-efficiency-tests?saved=1")}
export async function setWordEfficiencyStatus(form:FormData){await requireAdmin();const supabase=await createClient();const testId=value(form,"testId");await supabase.rpc("set_word_efficiency_status",{p_test_id:testId,p_status:value(form,"status")});refresh(testId)}
type CleanupJob={id:string;bucket:string;path:string;status:string;attempt_count:number};
async function processCleanupJob(job:CleanupJob){const admin=createAdminClient();if(!admin)return{failed:true};const safeBucket=job.bucket==="word-efficiency-pdfs"||job.bucket==="word-efficiency-working-matter";const safePath=Boolean(job.path)&&!job.path.startsWith("/")&&!job.path.includes("\\")&&!job.path.split("/").includes("..");let status:"removed"|"failed"|"retained_shared"="failed",cleanupError:string|null=null;if(!safeBucket||!safePath)cleanupError="Cleanup job failed application scope validation.";else{const referenceQuery=job.bucket==="word-efficiency-pdfs"?admin.from("word_efficiency_versions").select("id").eq("pdf_path",job.path).limit(1):admin.from("word_efficiency_versions").select("id").contains("working_matter_snapshot",{source:{bucket:job.bucket,storagePath:job.path}}).limit(1);const{data:references,error:referenceError}=await referenceQuery;if(referenceError)cleanupError=`Reference check failed: ${referenceError.message}`;else if(references?.length)status="retained_shared";else{const{error:removeError}=await admin.storage.from(job.bucket).remove([job.path]);cleanupError=removeError?.message??null;status=cleanupError?"failed":"removed"}}await admin.from("word_efficiency_storage_cleanup").update({status,attempt_count:(job.attempt_count??0)+1,last_error:cleanupError?.slice(0,1000)??null,last_attempted_at:new Date().toISOString()}).eq("id",job.id);return{failed:status==="failed"}}
export async function permanentlyDeleteWordEfficiencyTest(form:FormData){await requireAdmin();const testId=value(form,"testId"),typedTitle=String(form.get("typedTitle")??"");if(!testId||!typedTitle||form.get("destroyAcknowledged")!=="on")redirect("/admin/word-efficiency-tests?error=Exact%20title%20and%20destruction%20acknowledgement%20are%20required");const requestId=value(form,"requestId")||crypto.randomUUID();const supabase=await createClient();const{data,error}=await supabase.rpc("permanently_delete_word_efficiency_test",{p_test_id:testId,p_typed_title:typedTitle,p_acknowledged:true,p_request_id:requestId});if(error||!data)redirect(`/admin/word-efficiency-tests?error=${encodeURIComponent(error?.message??"Permanent deletion failed")}`);const result=data as{cleanup_jobs?:CleanupJob[]};let cleanupFailures=0;for(const job of result.cleanup_jobs??[]){if(job.status==="removed"||job.status==="retained_shared")continue;if((await processCleanupJob(job)).failed)cleanupFailures++}refresh(testId);redirect(`/admin/word-efficiency-tests?deleted=1${cleanupFailures?`&cleanup=${cleanupFailures}`:""}`)}
export async function retryWordEfficiencyStorageCleanup(form:FormData){await requireAdmin();const auditId=value(form,"auditId");if(!auditId)redirect("/admin/word-efficiency-tests?error=Cleanup%20audit%20identifier%20is%20required");const supabase=await createClient();const{data,error}=await supabase.from("word_efficiency_storage_cleanup").select("id,bucket_id,object_path,status,attempt_count").eq("audit_id",auditId).in("status",["pending","failed"]);if(error)redirect(`/admin/word-efficiency-tests?error=${encodeURIComponent(error.message)}`);let failures=0;for(const row of data??[]){const job={id:row.id,bucket:row.bucket_id,path:row.object_path,status:row.status,attempt_count:row.attempt_count}as CleanupJob;if((await processCleanupJob(job)).failed)failures++}refresh();redirect(`/admin/word-efficiency-tests?cleanupRetried=1${failures?`&cleanup=${failures}`:""}`)}
export async function duplicateWordEfficiencyTest(form:FormData){await requireAdmin();const supabase=await createClient();const id=value(form,"testId");const{data:test}=await supabase.from("word_efficiency_tests").select("current_version_id,title,language,slug").eq("id",id).single();if(!test?.current_version_id)return;const{data:version}=await supabase.from("word_efficiency_versions").select("*").eq("id",test.current_version_id).single();const{data:questions}=await supabase.from("word_efficiency_questions").select("question_number,instruction,marks,section,display_order,is_visible").eq("version_id",test.current_version_id).order("display_order");if(!version)return;let duplicatePdfPath=version.pdf_path as string|null,copiedPdfPath:string|null=null;if(version.delivery_pdf&&version.pdf_path){const destination=`duplicates/${crypto.randomUUID()}/${crypto.randomUUID()}-${safePdfName(version.pdf_file_name??"question-paper.pdf")}`;const{error:copyError}=await supabase.storage.from("word-efficiency-pdfs").copy(version.pdf_path,destination);if(!copyError){duplicatePdfPath=destination;copiedPdfPath=destination}}const payload={title:`${version.title} Copy`,slug:`${test.slug}-copy-${crypto.randomUUID().slice(0,6)}`,language:version.language,description:version.description,instructions_markdown:version.instructions_markdown,delivery_onscreen:version.delivery_onscreen,delivery_pdf:version.delivery_pdf,delivery_realfile:version.delivery_realfile,question_count:version.question_count,maximum_marks:version.maximum_marks,duration_options:version.duration_options,passing_marks:version.passing_marks??"",questions:(questions??[]).map(q=>({number:q.question_number,instruction:q.instruction,marks:q.marks,section:q.section,display_order:q.display_order,is_visible:q.is_visible})),publish:false,working_matter_snapshot:version.working_matter_snapshot,editor_capabilities:version.editor_capabilities,pdf_path:duplicatePdfPath,pdf_file_name:version.pdf_file_name,pdf_size_bytes:version.pdf_size_bytes,pdf_page_count:version.pdf_page_count,pdf_uploaded_at:version.pdf_uploaded_at};const{error}=await supabase.rpc("save_word_efficiency_test",{p_test_id:null,p_payload:payload});if(error&&copiedPdfPath)await supabase.storage.from("word-efficiency-pdfs").remove([copiedPdfPath]);refresh();if(error)redirect(`/admin/word-efficiency-tests?error=${encodeURIComponent(error.message)}`)}

export async function extractWordEfficiencyPdf(form:FormData){
 await requireAdmin();const language:WordLanguage=value(form,"language")==="Hindi"?"Hindi":"English";const upload=form.get("pdfFile");if(!(upload instanceof File)||!upload.size)return{ok:false,error:"Choose a PDF before extracting questions.",questions:[]};const checked=validatePdfUpload(upload);if(checked.errors.length)return{ok:false,error:checked.errors[0],questions:[]};const bytes=new Uint8Array(await upload.arrayBuffer());if(new TextDecoder("latin1").decode(bytes.slice(0,5))!=="%PDF-")return{ok:false,error:"Invalid PDF file signature.",questions:[]};
 try{const{pages,pageCount}=await extractPdfTextPages(bytes);if(pageCount>100)return{ok:false,error:"PDF question papers may not exceed 100 pages.",questions:[]};const text=pages.join("\n").trim();if(text.length<20)return{ok:false,error:"This PDF appears to contain scanned pages. OCR is required. You can paste question text manually.",questions:[],scanned:true};if(language==="Hindi"&&looksLikeKrutiDevText(text))return{ok:false,error:"This PDF appears to use Kruti Dev or malformed legacy font extraction. Choose the PDF encoding and convert the question metadata to Unicode Hindi before importing.",questions:[],krutidev:true};const questions=detectPdfQuestions(pages);if(!questions.length)return{ok:false,error:"No numbered questions were detected. Review the PDF text or paste questions manually.",questions:[]};return{ok:true,error:null,questions,pageCount,language};}catch(error){if(error instanceof PdfReaderStartError)return{ok:false,error:error.message,questions:[]};console.error("[Word Efficiency PDF extraction failed]",error);const message=error instanceof Error?error.message:"PDF extraction failed.";if(/password|encrypted/iu.test(message))return{ok:false,error:"This PDF is encrypted or password-protected and cannot be extracted.",questions:[]};if(/worker|pdf\.worker|fake worker/iu.test(message))return{ok:false,error:"The PDF reader could not start. Please retry after the application restarts.",questions:[]};return{ok:false,error:"The PDF could not be read. Check the file and try again.",questions:[]}}
}

export async function extractWorkingMatterDocx(form:FormData){await requireAdmin();const upload=form.get("workingMatterFile");if(!(upload instanceof File)||!upload.size)return{ok:false,error:"Choose a .docx Working Matter file.",snapshot:null};const errors=validateWorkingMatterFile(upload);if(errors.length)return{ok:false,error:errors[0],snapshot:null};const bytes=new Uint8Array(await upload.arrayBuffer());try{const snapshot=parseWorkingMatterDocx(bytes);const fileName=safePdfName(upload.name);const storagePath=`${crypto.randomUUID()}/${fileName}`;const supabase=await createClient();const{error:uploadError}=await supabase.storage.from("word-efficiency-working-matter").upload(storagePath,bytes,{contentType:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",upsert:false});snapshot.source={fileName:upload.name,sizeBytes:upload.size,...(uploadError?{}:{bucket:"word-efficiency-working-matter",storagePath})};return{ok:true,error:null,snapshot}}catch(error){return{ok:false,error:error instanceof Error?error.message:"Working Matter DOCX could not be read.",snapshot:null}}}

// Model Answer authoring: the admin solves the question paper in the exact
// same rich document editor a student uses (RichDocumentEditor's
// mode="authoring"), and this persists that solved document on the
// version. It reuses the editor's own autosave/submit call shape
// ((id, document) => {ok, error}) so no editor code needs to know the
// difference between an attempt and an authoring session.
export async function saveWordEfficiencyModelAnswer(versionId:string,document:unknown):Promise<{ok:boolean;error:string}>{
 await requireAdmin();
 const supabase=await createClient();
 const{error}=await supabase.rpc("save_word_efficiency_model_answer",{p_version_id:versionId,p_document:document});
 if(error)return{ok:false,error:process.env.NODE_ENV==="development"?`Save failed: ${error.message}`:"Save failed."};
 return{ok:true,error:""};
}

// Turns the admin's selected changes (each already carrying the exact
// target path + value the diff engine detected) into real grading rules:
// one rule per question, the first assigned change becomes the rule's
// primary target/expectedValue and the rest become additionalCriteria --
// every one of them must match for the question to earn full marks.
export async function generateWordEfficiencyGradingRulesFromModelAnswer(versionId:string,assignments:{questionNumber:number;allocatedMarks:number;criteria:{target:string;expectedValue:string}[]}[]){
 await requireAdmin();
 const supabase=await createClient();
 const rules=assignments.filter(assignment=>assignment.criteria.length>0).map(assignment=>{
  const[primary,...rest]=assignment.criteria;
  return{questionNumber:assignment.questionNumber,exactTarget:primary.target,expectedOperation:"model-answer-match",expectedValue:primary.expectedValue,allocatedMarks:assignment.allocatedMarks,partialMarks:null,additionalCriteria:rest};
 });
 const{error}=await supabase.rpc("save_word_efficiency_grading_rules",{p_version_id:versionId,p_rules:rules});
 if(error)return{ok:false,error:error.message};
 revalidatePath("/admin/word-efficiency-tests");
 return{ok:true,error:""};
}
