"use client";
/* eslint-disable react-hooks/set-state-in-effect -- restoration intentionally synchronizes persisted form state on mount */
import{useEffect,useRef,useState}from"react";

export function DraftPreserver(){
 const marker=useRef<HTMLSpanElement>(null);const[status,setStatus]=useState("");const[dirty,setDirty]=useState(false);
 useEffect(()=>{const form=marker.current?.closest("form");if(!form)return;const params=new URLSearchParams(location.search);const key=`samradhi-word-efficiency-draft-v2:${params.get("edit")??"new"}`;const draftButton=form.querySelector<HTMLButtonElement>('button[name="intent"][value="draft"]');if(draftButton){draftButton.type="button";draftButton.removeAttribute("name");draftButton.removeAttribute("value");draftButton.textContent="Save Draft"}
  if(params.get("saved")==="1"){localStorage.removeItem(key);localStorage.removeItem("samradhi-word-efficiency-pdf-preview-v1");setStatus("Saved record confirmed · local draft cleared");return}
  const stored=localStorage.getItem(key);if(stored&&confirm("Restore Draft from your previous Word Efficiency editing session?")){try{const values=JSON.parse(stored)as Record<string,string|string[]>;for(const[name,raw]of Object.entries(values)){const controls=form.elements.namedItem(name);const value=Array.isArray(raw)?raw[0]??"":raw;if(controls instanceof RadioNodeList){for(const control of Array.from(controls))if(control instanceof HTMLInputElement)control.checked=Array.isArray(raw)?raw.includes(control.value):value==="on"}else if(controls instanceof HTMLInputElement){if(controls.type!=="file"){if(controls.type==="checkbox")controls.checked=value==="on";else controls.value=value}}else if(controls instanceof HTMLSelectElement||controls instanceof HTMLTextAreaElement)controls.value=value}window.dispatchEvent(new CustomEvent("word-efficiency:draft-restored",{detail:values}));setStatus("Draft restored locally");setDirty(true)}catch{localStorage.removeItem(key)}}
  let timer:number|undefined;const save=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{const data=new FormData(form);const values:Record<string,string|string[]>={};for(const[name,value]of data){if(value instanceof File)continue;const current=values[name];values[name]=current===undefined?String(value):Array.isArray(current)?[...current,String(value)]:[current,String(value)]}localStorage.setItem(key,JSON.stringify(values));setStatus("Draft saved locally");setDirty(true)},500)};draftButton?.addEventListener("click",save);form.addEventListener("input",save);form.addEventListener("change",save);window.addEventListener("word-efficiency:questions-import",save);window.addEventListener("word-efficiency:save-draft",save);return()=>{window.clearTimeout(timer);draftButton?.removeEventListener("click",save);form.removeEventListener("input",save);form.removeEventListener("change",save);window.removeEventListener("word-efficiency:questions-import",save);window.removeEventListener("word-efficiency:save-draft",save)}
 },[]);
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=""};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 return <span ref={marker} role="status" className="text-sm font-bold text-green-700">{status}</span>
}
export function SaveLocalDraftButton(){return <button type="button" onClick={()=>window.dispatchEvent(new Event("word-efficiency:save-draft"))} className="rounded-xl bg-slate-700 px-5 py-3 font-black text-white">Save Draft</button>}
