"use client";
import { useMemo, useState } from "react";
import { APPROVED_WORD_FONTS, normalizeWordEditorCapabilities, recommendedWordEditorCapabilities, WORD_EDITOR_RIBBON, type HierarchicalEditorCapabilities } from "@/lib/word-editor-capabilities";
import { WordEditorRibbon } from "@/components/word-efficiency/word-editor-ribbon";

export function EditorCapabilityFields({ initialCapabilities }: { initialCapabilities?: unknown }) {
  const [caps, setCaps] = useState(() => normalizeWordEditorCapabilities(initialCapabilities));
  const [previewTab, setPreviewTab] = useState(() => WORD_EDITOR_RIBBON.find(tab => caps.tabs[tab.id].enabled)?.id ?? "Home");
  const count = useMemo(() => WORD_EDITOR_RIBBON.flatMap(tab => tab.groups.flatMap(group => group.options.filter(item => caps.tabs[tab.id].enabled && caps.tabs[tab.id].groups[group.id].enabled && caps.tabs[tab.id].groups[group.id].options[item.id]))).length, [caps]);
  const mutate = (fn: (next: HierarchicalEditorCapabilities) => void) => setCaps(current => { const next = structuredClone(current); fn(next); return next; });
  const all = (enabled: boolean) => mutate(next => { for (const tab of WORD_EDITOR_RIBBON) { next.tabs[tab.id].enabled = enabled; for (const group of tab.groups) { next.tabs[tab.id].groups[group.id].enabled = enabled; for (const item of group.options) next.tabs[tab.id].groups[group.id].options[item.id] = enabled && !item.unsupported; } } });
  return <fieldset className="mt-4 rounded-2xl border border-cyan-200 bg-white p-4"><legend className="px-2 font-black">Student editor capabilities</legend><input type="hidden" name="editorCapabilities" value={JSON.stringify(caps)}/>
    <div className="flex flex-wrap items-center gap-2"><Action label="Select all supported" run={() => all(true)}/><Action label="Clear all" run={() => all(false)} tone="muted"/><Action label="Restore recommended defaults" run={() => setCaps(recommendedWordEditorCapabilities())} tone="light"/><span className="ml-auto text-xs font-bold text-slate-500">{count} tools enabled</span></div>
    <div className="mt-4 space-y-3">{WORD_EDITOR_RIBBON.map(tab => <section key={tab.id} className="rounded-xl border"><label className="flex gap-2 bg-slate-100 px-3 py-2 font-black"><input type="checkbox" checked={caps.tabs[tab.id].enabled} onChange={e => mutate(next => { next.tabs[tab.id].enabled = e.target.checked; })}/>{tab.id} tab</label><div className="grid gap-2 p-3 lg:grid-cols-2">{tab.groups.map(group => <fieldset key={group.id} disabled={!caps.tabs[tab.id].enabled} className="rounded-lg border p-3 disabled:opacity-50"><legend className="px-1"><label className="flex gap-2 text-sm font-black"><input type="checkbox" checked={caps.tabs[tab.id].groups[group.id].enabled} onChange={e => mutate(next => { next.tabs[tab.id].groups[group.id].enabled = e.target.checked; })}/>{group.label}</label></legend><div className="grid gap-1 sm:grid-cols-2">{group.options.map(item => <label key={item.id} title={item.unsupported} className={`flex gap-2 rounded p-1.5 text-xs ${item.unsupported ? "bg-amber-50 text-amber-900" : "hover:bg-slate-50"}`}><input type="checkbox" disabled={Boolean(item.unsupported) || !caps.tabs[tab.id].groups[group.id].enabled} checked={caps.tabs[tab.id].groups[group.id].options[item.id]} onChange={e => mutate(next => { next.tabs[tab.id].groups[group.id].options[item.id] = e.target.checked; })}/><span>{item.label}{item.unsupported && <small className="block font-bold">Intentionally unavailable: {item.unsupported}</small>}</span></label>)}</div></fieldset>)}</div></section>)}</div>
    <section className="mt-5 overflow-hidden rounded-xl border bg-white"><h3 className="border-b bg-slate-50 px-3 py-2 font-black">Admin-only live ribbon preview</h3><WordEditorRibbon capabilities={caps} activeTab={previewTab} onTabChange={setPreviewTab} preview/></section>
    <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_120px_120px]"><fieldset><legend className="text-sm font-black">Allowed fonts</legend><div className="mt-2 flex flex-wrap gap-3">{APPROVED_WORD_FONTS.map(font => <label key={font} className="text-sm"><input className="mr-1" type="checkbox" checked={caps.fonts.includes(font)} onChange={e => mutate(next => { next.fonts = e.target.checked ? [...new Set([...next.fonts, font])] : next.fonts.filter(value => value !== font); })}/>{font}</label>)}</div></fieldset><label className="text-sm font-bold">Minimum size<input className="input mt-1" type="number" min="8" max="72" value={caps.fontSizeMin} onChange={e => mutate(next => { next.fontSizeMin = Math.min(next.fontSizeMax, Number(e.target.value)); })}/></label><label className="text-sm font-bold">Maximum size<input className="input mt-1" type="number" min="8" max="72" value={caps.fontSizeMax} onChange={e => mutate(next => { next.fontSizeMax = Math.max(next.fontSizeMin, Number(e.target.value)); })}/></label></div>
  </fieldset>;
}
function Action({label,run,tone="dark"}:{label:string;run:()=>void;tone?:"dark"|"muted"|"light"}){return <button type="button" onClick={run} className={`rounded-lg px-3 py-2 text-xs font-black ${tone==="dark"?"bg-blue-700 text-white":tone==="muted"?"bg-slate-200":"bg-cyan-100 text-cyan-950"}`}>{label}</button>}
