"use client";
import{useState}from"react";
import{useFormStatus}from"react-dom";
import{permanentlyDeleteWordEfficiencyTest}from"./actions";

export type DeleteImpact={testId:string;title:string;status:string;versionCount:number;attemptCount:number;activeAttemptCount:number;resultCount:number;fileCount:number;requestId:string};

export function PermanentDeleteDangerZone({impact}:{impact:DeleteImpact}){const[typed,setTyped]=useState("");const[acknowledged,setAcknowledged]=useState(false);const valid=typed===impact.title&&acknowledged;return <section className="col-span-2 mt-3 rounded-2xl border-2 border-red-300 bg-red-50 p-4" aria-labelledby={`danger-${impact.testId}`}><h4 id={`danger-${impact.testId}`} className="font-black text-red-900">Danger Zone · Permanently Delete</h4><p className="mt-1 text-sm font-bold text-red-800">This cannot be undone. Archive is the recommended reversible action.</p>{impact.activeAttemptCount>0&&<p role="alert" className="mt-3 rounded-xl bg-red-700 p-3 font-black text-white">Warning: {impact.activeAttemptCount} prepared or active attempt{impact.activeAttemptCount===1?" is":"s are"} currently in progress and will be destroyed.</p>}<dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><Item label="Test title" value={impact.title}/><Item label="Status" value={impact.status}/><Item label="Versions" value={impact.versionCount}/><Item label="All attempts" value={impact.attemptCount}/><Item label="Prepared / active" value={impact.activeAttemptCount}/><Item label="Submitted / completed results" value={impact.resultCount}/><Item label="Stored PDF / source files" value={impact.fileCount}/></dl><form action={permanentlyDeleteWordEfficiencyTest} className="mt-4 grid gap-3"><input type="hidden" name="testId" value={impact.testId}/><input type="hidden" name="requestId" value={impact.requestId}/><label className="grid gap-1 text-sm font-black text-red-950"><span>Type the exact test title: <span className="select-all">{impact.title}</span></span><input className="input border-red-300" name="typedTitle" autoComplete="off" value={typed} onChange={event=>setTyped(event.target.value)} aria-describedby={`delete-help-${impact.testId}`}/></label><label className="flex items-start gap-2 text-sm font-bold text-red-950"><input className="mt-1" type="checkbox" name="destroyAcknowledged" checked={acknowledged} onChange={event=>setAcknowledged(event.target.checked)}/><span>I understand that all attempts, student results, documents, grading records, versions, questions, and files will be permanently destroyed.</span></label><p id={`delete-help-${impact.testId}`} className="text-xs text-red-700">Both confirmations are required. Submission is protected against duplicate requests.</p><DeleteButton valid={valid}/></form></section>}
function Item({label,value}:{label:string;value:string|number}){return <div className="rounded-lg bg-white p-2"><dt className="text-xs font-black uppercase text-red-700">{label}</dt><dd className="font-bold text-slate-950">{value}</dd></div>}
function DeleteButton({valid}:{valid:boolean}){const{pending}=useFormStatus();return <button type="submit" disabled={!valid||pending} aria-disabled={!valid||pending} className="rounded-xl bg-red-800 px-4 py-3 font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300">{pending?"Permanently deleting…":"Permanently delete test and all data"}</button>}
