"use client";

import {useEffect,useMemo,useState} from "react";
import {calculateWordQuestionSummary,MAX_WORD_QUESTION_MARKS,type WordQuestion} from "@/lib/word-efficiency";
import type{ExtractedWordQuestion}from"@/lib/word-pdf-extraction";
import{DraftPreserver}from"./draft-preserver";
import{QuestionContentEditor}from"@/components/efficiency/question-content-editor";
import{QuestionContent}from"@/components/efficiency/question-content";

type EditorQuestion=WordQuestion&{clientId:string;selected:boolean};

const fresh=(number:number):EditorQuestion=>({clientId:crypto.randomUUID(),selected:false,number,instruction:"",marks:1,section:null,display_order:number,is_visible:true,gradingRule:null});
const normalize=(items:EditorQuestion[])=>items.map((item,index)=>({...item,display_order:index+1}));

export function QuestionEditor({initialQuestions}:{initialQuestions:WordQuestion[]}){
 // clientId must be deterministic here, not crypto.randomUUID() -- this
 // initializer runs once during the server's SSR pass of this Client
 // Component and again during browser hydration, both starting from the
 // same initialQuestions prop. A random id would compute a different value
 // each time, silently desyncing every <article key={question.clientId}>
 // between server and client and forcing React to remount every existing
 // question's card (and its focus/scroll state) right after hydration.
 // Existing DB questions already have a stable id; only the synthetic
 // fresh(1) placeholder (shown when a test has no questions yet) needs a
 // fallback, which is derived from its index so it's still deterministic.
 const[questions,setQuestions]=useState<EditorQuestion[]>(()=>normalize((initialQuestions.length?initialQuestions:[fresh(1)]).map((question,index)=>({...question,clientId:question.id??`new-${index}`,selected:false,display_order:index+1}))));
 const[bulkMarks,setBulkMarks]=useState("1");const[preview,setPreview]=useState(false);const[dragged,setDragged]=useState<number|null>(null);
 useEffect(()=>{const receive=(event:Event)=>{const{mode,questions:extracted}=(event as CustomEvent<{mode:"append"|"replace";questions:ExtractedWordQuestion[]}>).detail;setQuestions(current=>{const fingerprints=new Set(current.map(item=>item.source_fingerprint).filter(Boolean));const imported=extracted.filter(item=>!fingerprints.has(item.fingerprint)).map((item,index):EditorQuestion=>({clientId:crypto.randomUUID(),selected:false,source_fingerprint:item.fingerprint,number:item.number,instruction:item.text,marks:Number.NaN,section:item.section,display_order:index+1,is_visible:true}));if(!imported.length){alert("These extracted questions are already present.");return current}return normalize(mode==="replace"?imported:[...current,...imported])})};window.addEventListener("word-efficiency:questions-import",receive);return()=>window.removeEventListener("word-efficiency:questions-import",receive)},[]);
 useEffect(()=>{const restore=(event:Event)=>{const raw=(event as CustomEvent<Record<string,string|string[]>>).detail.questions;if(typeof raw!=="string")return;try{const parsed=JSON.parse(raw)as WordQuestion[];if(parsed.length)setQuestions(normalize(parsed.map(question=>({...question,marks:question.marks===null?Number.NaN:Number(question.marks),clientId:crypto.randomUUID(),selected:false}))))}catch{}};window.addEventListener("word-efficiency:draft-restored",restore);return()=>window.removeEventListener("word-efficiency:draft-restored",restore)},[]);
 const summary=useMemo(()=>calculateWordQuestionSummary(questions),[questions]);
 const update=(id:string,patch:Partial<EditorQuestion>)=>setQuestions(items=>items.map(item=>item.clientId===id?{...item,...patch}:item));
 const move=(index:number,direction:-1|1)=>setQuestions(items=>{const next=[...items];const target=index+direction;if(target<0||target>=next.length)return items;[next[index],next[target]]=[next[target],next[index]];return normalize(next)});
 const add=()=>setQuestions(items=>[...items,fresh(Math.max(0,...items.map(item=>item.number))+1)]);
 const duplicate=(index:number)=>setQuestions(items=>{const source=items[index];const copy={...source,id:undefined,clientId:crypto.randomUUID(),number:Math.max(0,...items.map(item=>item.number))+1,selected:false};const next=[...items];next.splice(index+1,0,copy);return normalize(next)});
 const remove=(id:string)=>{if(questions.length===1||confirm("Delete this question?"))setQuestions(items=>normalize(items.filter(item=>item.clientId!==id)))};
 const applyBulk=(selectedOnly:boolean)=>{const marks=Number(bulkMarks);if(!Number.isFinite(marks)||marks<=0||marks>MAX_WORD_QUESTION_MARKS)return alert(`Enter marks between 0 and ${MAX_WORD_QUESTION_MARKS}.`);const targets=selectedOnly?questions.filter(item=>item.selected):questions;if(!targets.length)return alert("Select at least one question.");if(!confirm(`Replace marks on ${targets.length} question${targets.length===1?"":"s"}?`))return;setQuestions(items=>items.map(item=>(!selectedOnly||item.selected)?{...item,marks}:item))};
 const distribute=()=>{const total=Number(prompt("Enter the total marks to distribute equally:"));if(!Number.isFinite(total)||total<=0)return;const marks=Number((total/questions.length).toFixed(2));if(marks<=0||marks>MAX_WORD_QUESTION_MARKS)return alert("The resulting per-question marks are outside the allowed range.");if(Number((marks*questions.length).toFixed(2))!==Number(total.toFixed(2)))return alert("This total cannot be distributed equally to two decimal places.");if(confirm(`Set every question to ${marks} marks?`))setQuestions(items=>items.map(item=>({...item,marks})))};
 const serialized=questions.map(question=>({id:question.id,source_fingerprint:question.source_fingerprint,number:question.number,instruction:question.instruction,marks:Number.isFinite(question.marks)?question.marks:null,section:question.section,display_order:question.display_order,is_visible:question.is_visible,gradingRule:question.gradingRule}));
 return <section className="rounded-2xl border border-slate-200 p-4 sm:p-5">
  <DraftPreserver/>
  <input type="hidden" name="questions" value={JSON.stringify(serialized)}/><input type="hidden" name="questionCount" value={summary.questionCount}/><input type="hidden" name="maximumMarks" value={summary.maximumMarks}/>
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-black">Question editor</h3><p className="text-sm text-slate-500">Marks are assigned per question. The test total is calculated automatically.</p></div><div className="flex gap-2"><button type="button" onClick={()=>setPreview(true)} className="rounded-lg bg-violet-100 px-3 py-2 text-sm font-bold text-violet-800">Preview Question Paper</button><button type="button" onClick={add} className="rounded-lg bg-blue-700 px-3 py-2 text-sm font-bold text-white">Add Question</button></div></div>
  <dl className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><Summary label="Total questions" value={summary.questionCount}/><Summary label="Total maximum marks" value={summary.maximumMarks}/><Summary label="Questions without marks" value={summary.questionsWithoutMarks}/><Summary label="Average marks" value={summary.averageMarks}/></dl>
  <div className="mt-4 flex flex-wrap items-end gap-2 rounded-xl bg-slate-50 p-3"><label className="text-xs font-bold">Bulk marks<input type="number" min="0.01" max={MAX_WORD_QUESTION_MARKS} step="0.01" value={bulkMarks} onChange={event=>setBulkMarks(event.target.value)} className="input mt-1 w-28"/></label><button type="button" onClick={()=>applyBulk(false)} className="rounded-lg bg-slate-800 px-3 py-2 text-sm font-bold text-white">Apply marks to all questions</button><button type="button" onClick={()=>applyBulk(true)} className="rounded-lg bg-slate-200 px-3 py-2 text-sm font-bold">Apply marks to selected questions</button><button type="button" onClick={distribute} className="rounded-lg bg-slate-200 px-3 py-2 text-sm font-bold">Distribute total marks equally</button></div>
  <div className="mt-4 space-y-4">{questions.map((question,index)=><article key={question.clientId} draggable onDragStart={()=>setDragged(index)} onDragOver={event=>event.preventDefault()} onDrop={()=>{if(dragged===null||dragged===index)return;setQuestions(items=>{const next=[...items];const[item]=next.splice(dragged,1);next.splice(index,0,item);return normalize(next)});setDragged(null)}} className="rounded-xl border bg-white p-4 shadow-sm">
   <div className="flex flex-wrap items-center justify-between gap-2"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={question.selected} onChange={event=>update(question.clientId,{selected:event.target.checked})}/>Select</label><span className="cursor-grab text-xs font-bold text-slate-500" title="Drag to reorder">↕ Display order {question.display_order}</span><div className="flex flex-wrap gap-1"><button type="button" onClick={()=>move(index,-1)} disabled={index===0} aria-label={`Move question ${question.number} up`} className="mini">Move Up</button><button type="button" onClick={()=>move(index,1)} disabled={index===questions.length-1} aria-label={`Move question ${question.number} down`} className="mini">Move Down</button><button type="button" onClick={()=>duplicate(index)} className="mini">Duplicate Question</button><button type="button" onClick={()=>remove(question.clientId)} className="mini text-red-700">Delete Question</button></div></div>
   <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Label text="Question number"><input className="input" type="number" min="1" value={question.number} onChange={event=>update(question.clientId,{number:Number(event.target.value)})}/></Label><Label text="Individual maximum marks"><input className="input" type="number" min="0.01" max={MAX_WORD_QUESTION_MARKS} step="0.01" required value={Number.isFinite(question.marks)?question.marks:""} onChange={event=>update(question.clientId,{marks:event.target.value===""?Number.NaN:Number(event.target.value)})}/></Label><Label text="Optional section/topic"><input className="input" value={question.section??""} onChange={event=>update(question.clientId,{section:event.target.value||null})}/></Label><label className="flex items-center gap-2 self-end pb-3 text-sm font-bold"><input type="checkbox" checked={question.is_visible} onChange={event=>update(question.clientId,{is_visible:event.target.checked})}/>Visible on screen</label></div>
   <Label text="Question instruction/text — write or paste from Word/Excel; tables and lists are supported"><QuestionContentEditor ariaLabel={`Question ${question.number} instruction`} required={question.is_visible} value={question.instruction} onChange={value=>update(question.clientId,{instruction:value})}/></Label>
   {/* The "Explicit automatic grading rule" fieldset was removed from this
       form at the admin's request -- it's confusing/unused clutter for
       manually-graded tests. gradingRule stays in the question's state and
       still round-trips through save unchanged, so a question that already
       has one configured (from before this change) keeps it; there is just
       no UI here to create, view, or edit one any more. */}
   {index>0&&<button type="button" onClick={()=>{if(confirm("Copy marks from the previous question?"))update(question.clientId,{marks:questions[index-1].marks})}} className="mt-3 text-sm font-bold text-blue-700">Copy marks from previous question</button>}
  </article>)}</div>
  {preview&&<div role="dialog" aria-modal="true" aria-label="Question paper preview" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4"><section className="max-h-[90dvh] w-full max-w-3xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h3 className="text-xl font-black">Question Paper Preview · {summary.maximumMarks} marks</h3><button type="button" onClick={()=>setPreview(false)} className="font-black">Close</button></div><div className="mt-5 space-y-4">{questions.map(question=><article key={question.clientId} className="rounded-xl border p-4"><h4 className="font-black">Question {question.number} · {question.marks} marks</h4>{question.section&&<p className="text-xs font-bold text-blue-700">{question.section}</p>}{question.is_visible?<div className="mt-2"><QuestionContent text={question.instruction}/></div>:<p className="mt-2">See Question {question.number} in the downloaded PDF — {question.marks} marks</p>}</article>)}</div></section></div>}
 </section>
}
function Label({text,children}:{text:string;children:React.ReactNode}){return <label className="grid gap-1 text-sm font-bold text-slate-700"><span>{text}</span>{children}</label>}
function Summary({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-blue-50 p-3"><dt className="text-xs font-bold text-blue-700">{label}</dt><dd className="mt-1 text-xl font-black">{value}</dd></div>}
