"use client";
import { useState, useTransition } from "react";
import type { MatterParagraph, WorkingMatterSnapshot } from "@/lib/word-docx";
import { extractWorkingMatterDocx } from "./actions";

export function WorkingMatterDocxFields({ initialSnapshot }: { initialSnapshot: WorkingMatterSnapshot | null }) {
  const [snapshot, setSnapshot] = useState(initialSnapshot);
  const [error, setError] = useState("");
  const [pending, startTransition] = useTransition();
  const extract = (file: File | null) => { if (!file) return; const form = new FormData(); form.set("workingMatterFile", file); startTransition(async () => { const result = await extractWorkingMatterDocx(form); if (!result.ok || !result.snapshot) { setError(result.error ?? "DOCX import failed."); return; } setSnapshot(result.snapshot); setError(""); }); };
  const update = (id: string, patch: Partial<MatterParagraph>) => setSnapshot(current => current ? { ...current, paragraphs: current.paragraphs.map(paragraph => paragraph.id === id ? { ...paragraph, ...patch } : paragraph) } : current);
  return <fieldset className="rounded-2xl border border-emerald-200 bg-emerald-50/40 p-4"><legend className="px-2 font-black">Upload Working Matter (.docx)</legend><p className="text-sm text-slate-600">This editable DOCX matter is separate from the private Question Paper PDF.</p><input className="input mt-3" type="file" name="workingMatterFile" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={event => extract(event.target.files?.[0] ?? null)}/>{pending && <p role="status" className="mt-2 font-bold text-blue-700">Importing and sanitizing DOCX…</p>}{error && <p role="alert" className="mt-2 font-bold text-red-700">{error}</p>}
    {snapshot && <section className="mt-4 rounded-xl bg-white p-4"><input type="hidden" name="workingMatterSnapshot" value={JSON.stringify(snapshot)}/><div className="grid gap-2 text-sm sm:grid-cols-3"><Meta label="Filename" value={snapshot.source?.fileName ?? "Saved snapshot"}/><Meta label="Size" value={snapshot.source ? `${snapshot.source.sizeBytes.toLocaleString()} bytes` : "Stored version"}/><Meta label="Detected language" value={snapshot.language}/><Meta label="Paragraphs" value={String(snapshot.formattingSummary.paragraphs)}/><Meta label="List items" value={String(snapshot.formattingSummary.listItems)}/><Meta label="Formatting" value={`${snapshot.formattingSummary.italicParagraphs} italic · ${snapshot.formattingSummary.justifiedParagraphs} justified`}/></div>{snapshot.warnings.map(warning => <p key={warning} className="mt-3 rounded-lg bg-amber-50 p-3 text-sm font-bold text-amber-800">{warning}</p>)}<h3 className="mt-5 font-black">Paragraph and list preview</h3><p className="text-xs text-slate-500">Correct paragraph numbering or group short lines as list items before publishing.</p><div className="mt-3 max-h-96 space-y-2 overflow-auto">{snapshot.paragraphs.map(paragraph => <article key={paragraph.id} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-[110px_90px_1fr]"><select aria-label={`Block type ${paragraph.id}`} value={paragraph.type} onChange={event => update(paragraph.id, { type: event.target.value as MatterParagraph["type"], paragraphNumber: event.target.value === "list-item" ? null : paragraph.paragraphNumber })} className="input"><option value="paragraph">Paragraph</option><option value="list-item">List item</option></select><input aria-label={`Paragraph number ${paragraph.id}`} className="input" type="number" min="1" disabled={paragraph.type === "list-item"} value={paragraph.paragraphNumber ?? ""} onChange={event => update(paragraph.id, { paragraphNumber: Number(event.target.value) })}/><div><p className="whitespace-pre-wrap text-sm" style={{ fontStyle: paragraph.runs.some(run => run.italic) ? "italic" : "normal", textAlign: paragraph.alignment }}>{paragraph.runs.map(run => run.text).join("")}</p><span className="text-[10px] font-bold uppercase text-slate-400">{paragraph.alignment} · {paragraph.runs.length} run{paragraph.runs.length === 1 ? "" : "s"}</span></div></article>)}</div></section>}
  </fieldset>;
}
function Meta({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-2"><strong className="block text-[10px] uppercase text-slate-500">{label}</strong>{value}</div>; }
